Repository JanusGraph/janusgraph, pull requests merged in 2018-07, with the labels that each got.

#1141 Delete only janusgraph-aliased indices in Elasticsearch clearStorage
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestElasticSearchClient.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticSearchIndexTest.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticSearchMultiTypeIndexTest.java
Labels: cla: yes

#1151 Merge 0.2 into master
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestElasticSearchClient.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticSearchIndexTest.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticSearchMultiTypeIndexTest.java
Labels: cla: yes

#1126 Issue #1066 - Fixed automatic type detection issue for edge properties
  janusgraph-core/src/main/java/org/janusgraph/graphdb/relations/AbstractTypedRelation.java
  janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
Labels: cla: yes

#1135 No longer use COMPACT STORAGE for Cassandra 3+ with CQL backend
  docs/basics.adoc
  docs/cassandra.adoc
  docs/configuredgraphfactory.adoc
  docs/exampleconfig.adoc
  docs/hadoop.adoc
  docs/intro.adoc
  docs/reindex.adoc
  docs/solr.adoc
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java
  janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLStoreTest.java
  janusgraph-dist/src/assembly/cfilter/conf/janusgraph-cql-configurationgraph.properties
  janusgraph-dist/src/assembly/cfilter/conf/janusgraph-cql-es.properties
  janusgraph-dist/src/assembly/cfilter/conf/janusgraph-cql-solr.properties
  janusgraph-dist/src/assembly/cfilter/conf/janusgraph-cql.properties
  janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-configuration.yaml
  janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server.yaml
  janusgraph-dist/src/assembly/static/conf/gremlin-server/janusgraph-cql-es-server.properties
  pom.xml
Labels: cla: yes

#998 Added STORAGE_FORMAT_VERSION and check and updated version check
  docs/basics.adoc
  docs/migrating.adoc
  docs/upgrade.adoc
  docs/versions.adoc
  janusgraph-cassandra/src/test/java/org/janusgraph/graphdb/CassandraGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/ModifiableConfiguration.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/JanusGraphConstants.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java
  janusgraph-core/src/main/resources/org/janusgraph/graphdb/configuration/janusgraph.internal.properties
  pom.xml
Labels: cla: yes

#1158 Add Qihoo 360 as a production user [skip ci]
  README.md
Labels: cla: yes

#1154 Add Red Hat to list of production users [skip ci]
  README.md
Labels: cla: yes, docs

#1160 JanusGraph 0.2.1 release
  docs/changelog.adoc
  docs/versions.adoc
  janusgraph-all/pom.xml
  janusgraph-berkeleyje/pom.xml
  janusgraph-bigtable/pom.xml
  janusgraph-cassandra/pom.xml
  janusgraph-codepipelines-ci/pom.xml
  janusgraph-core/pom.xml
  janusgraph-cql/pom.xml
  janusgraph-dist/janusgraph-dist-hadoop-2/pom.xml
  janusgraph-dist/pom.xml
  janusgraph-doc/pom.xml
  janusgraph-es/pom.xml
  janusgraph-examples/example-berkeleyje/pom.xml
  janusgraph-examples/example-cassandra/pom.xml
  janusgraph-examples/example-common/pom.xml
  janusgraph-examples/example-cql/pom.xml
  janusgraph-examples/example-hbase/pom.xml
  janusgraph-examples/example-remotegraph/pom.xml
  janusgraph-examples/example-tinkergraph/pom.xml
  janusgraph-examples/pom.xml
  janusgraph-hadoop-parent/janusgraph-hadoop-2/pom.xml
  janusgraph-hadoop-parent/janusgraph-hadoop-core/pom.xml
  janusgraph-hadoop-parent/janusgraph-hadoop/pom.xml
  janusgraph-hadoop-parent/pom.xml
  janusgraph-hbase-parent/janusgraph-hbase-098/pom.xml
  janusgraph-hbase-parent/janusgraph-hbase-10/pom.xml
  janusgraph-hbase-parent/janusgraph-hbase-core/pom.xml
  janusgraph-hbase-parent/janusgraph-hbase/pom.xml
  janusgraph-hbase-parent/pom.xml
  janusgraph-lucene/pom.xml
  janusgraph-solr/pom.xml
  janusgraph-test/pom.xml
  pom.xml
Labels: cla: yes

#1168 Returned to 0.2.2-SNAPSHOT
  docs/changelog.adoc
  janusgraph-all/pom.xml
  janusgraph-berkeleyje/pom.xml
  janusgraph-bigtable/pom.xml
  janusgraph-cassandra/pom.xml
  janusgraph-codepipelines-ci/pom.xml
  janusgraph-core/pom.xml
  janusgraph-cql/pom.xml
  janusgraph-dist/janusgraph-dist-hadoop-2/pom.xml
  janusgraph-dist/pom.xml
  janusgraph-doc/pom.xml
  janusgraph-es/pom.xml
  janusgraph-examples/example-berkeleyje/pom.xml
  janusgraph-examples/example-cassandra/pom.xml
  janusgraph-examples/example-common/pom.xml
  janusgraph-examples/example-cql/pom.xml
  janusgraph-examples/example-hbase/pom.xml
  janusgraph-examples/example-remotegraph/pom.xml
  janusgraph-examples/example-tinkergraph/pom.xml
  janusgraph-examples/pom.xml
  janusgraph-hadoop-parent/janusgraph-hadoop-2/pom.xml
  janusgraph-hadoop-parent/janusgraph-hadoop-core/pom.xml
  janusgraph-hadoop-parent/janusgraph-hadoop/pom.xml
  janusgraph-hadoop-parent/pom.xml
  janusgraph-hbase-parent/janusgraph-hbase-098/pom.xml
  janusgraph-hbase-parent/janusgraph-hbase-10/pom.xml
  janusgraph-hbase-parent/janusgraph-hbase-core/pom.xml
  janusgraph-hbase-parent/janusgraph-hbase/pom.xml
  janusgraph-hbase-parent/pom.xml
  janusgraph-lucene/pom.xml
  janusgraph-solr/pom.xml
  janusgraph-test/pom.xml
  pom.xml
Labels: cla: yes

#1171 Use column name offset in HBase ColumnPaginationFilter #1170
  janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/org/janusgraph/diskstorage/hbase/HBaseKeyColumnValueStore.java
Labels: cla: yes, hbase

#1161 Merge to master
  docs/basics.adoc
  docs/cassandra.adoc
  docs/changelog.adoc
  docs/configuredgraphfactory.adoc
  docs/exampleconfig.adoc
  docs/hadoop.adoc
  docs/intro.adoc
  docs/reindex.adoc
  docs/solr.adoc
  docs/versions.adoc
  janusgraph-core/src/main/java/org/janusgraph/graphdb/relations/AbstractTypedRelation.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java
  janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLStoreTest.java
  janusgraph-dist/src/assembly/cfilter/conf/janusgraph-cql-configurationgraph.properties
  janusgraph-dist/src/assembly/cfilter/conf/janusgraph-cql-es.properties
  janusgraph-dist/src/assembly/cfilter/conf/janusgraph-cql-solr.properties
  janusgraph-dist/src/assembly/cfilter/conf/janusgraph-cql.properties
  janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-configuration.yaml
  janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server.yaml
  janusgraph-dist/src/assembly/static/conf/gremlin-server/janusgraph-cql-es-server.properties
  janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  pom.xml
Labels: cla: yes

#1129 Run CI batch compile even when not doing coverity scan.
  .travis.yml
Labels: cla: yes

#1187 Document Deployment Scenarios #119 [skip ci]
  docs/basics.adoc
  docs/deploymentscenarios.adoc
  docs/partitioning.adoc
  docs/static/images/advanced-scenario.svg
  docs/static/images/advanced-scenario.xml
  docs/static/images/getting-started-scenario.svg
  docs/static/images/getting-started-scenario.xml
  docs/static/images/minimalist-scenario.svg
  docs/static/images/minimalist-scenario.xml
Labels: cla: yes, docs

#1195 merge 0.2 fixes to master
  .travis.yml
  docs/basics.adoc
  docs/deploymentscenarios.adoc
  docs/hadoop.adoc
  docs/partitioning.adoc
  docs/static/images/advanced-scenario.svg
  docs/static/images/advanced-scenario.xml
  docs/static/images/getting-started-scenario.svg
  docs/static/images/getting-started-scenario.xml
  docs/static/images/minimalist-scenario.svg
  docs/static/images/minimalist-scenario.xml
Labels: cla: yes

#1196 JanusGraph 0.3.0 release
  docs/changelog.adoc
  docs/versions.adoc
  janusgraph-all/pom.xml
  janusgraph-berkeleyje/pom.xml
  janusgraph-bigtable/pom.xml
  janusgraph-cassandra/pom.xml
  janusgraph-codepipelines-ci/pom.xml
  janusgraph-core/pom.xml
  janusgraph-cql/pom.xml
  janusgraph-dist/janusgraph-dist-hadoop-2/pom.xml
  janusgraph-dist/pom.xml
  janusgraph-doc/pom.xml
  janusgraph-es/pom.xml
  janusgraph-examples/example-berkeleyje/pom.xml
  janusgraph-examples/example-cassandra/pom.xml
  janusgraph-examples/example-common/pom.xml
  janusgraph-examples/example-cql/pom.xml
  janusgraph-examples/example-hbase/pom.xml
  janusgraph-examples/example-remotegraph/pom.xml
  janusgraph-examples/example-tinkergraph/pom.xml
  janusgraph-examples/pom.xml
  janusgraph-hadoop-parent/janusgraph-hadoop-2/pom.xml
  janusgraph-hadoop-parent/janusgraph-hadoop-core/pom.xml
  janusgraph-hadoop-parent/janusgraph-hadoop/pom.xml
  janusgraph-hadoop-parent/pom.xml
  janusgraph-hbase-parent/janusgraph-hbase-10/pom.xml
  janusgraph-hbase-parent/janusgraph-hbase-core/pom.xml
  janusgraph-hbase-parent/janusgraph-hbase-server/pom.xml
  janusgraph-hbase-parent/janusgraph-hbase/pom.xml
  janusgraph-hbase-parent/pom.xml
  janusgraph-lucene/pom.xml
  janusgraph-server/pom.xml
  janusgraph-solr/pom.xml
  janusgraph-test/pom.xml
  pom.xml
Labels: cla: yes
