Repository JanusGraph/janusgraph, pull requests merged in 2019-03, with the labels that each got.

#1440 Cover ReadConfigurationBuilder with unit tests
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/builder/ReadConfigurationBuilder.java
  janusgraph-test/src/test/java/org/janusgraph/diskstorage/configuration/builder/ReadConfigurationBuilderTest.java
Labels: cla: yes

#1409 Use testcontainers as runner for elasticsearch #1014
  .travis.yml
  TESTING.md
  janusgraph-all/pom.xml
  janusgraph-codepipelines-ci/pipe.yml
  janusgraph-core/pom.xml
  janusgraph-dist/janusgraph-dist-hadoop-2/pom.xml
  janusgraph-dist/pom.xml
  janusgraph-dist/src/test/java/org/janusgraph/pkgtest/CassandraThriftESAssemblyIT.java
  janusgraph-es/pom.xml
  janusgraph-es/src/test/config/elasticsearch.docker.yml
  janusgraph-es/src/test/config/elasticsearch.yml
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/BerkeleyElasticsearchTest.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticsearchConfigTest.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticsearchIndexTest.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticsearchMultiTypeIndexTest.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticsearchRunner.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticsearchStatus.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/JanusGraphElasticsearchContainer.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ThriftElasticsearchTest.java
  janusgraph-es/src/test/resources/elasticsearch-old.yml
  janusgraph-examples/example-remotegraph/pom.xml
  janusgraph-examples/example-tinkergraph/pom.xml
  janusgraph-hadoop-parent/pom.xml
  janusgraph-server/pom.xml
  janusgraph-test/pom.xml
  pom.xml
Labels: cla: yes

#1450 add non-es berkeleyje configuration #1203
  janusgraph-dist/janusgraph-dist-hadoop-2/docker-compose.yml
  janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-berkeleyje-es.yaml
  janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-berkeleyje.yaml
Labels: cla: yes

#1470 Mark Flaky Berkeley test as flaky
  janusgraph-berkeleyje/src/test/java/org/janusgraph/graphdb/berkeleyje/BerkeleyOperationCountingTest.java
  janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphOperationCountingTest.java
Labels: cla: yes

#1392 Fix tx leaks in ConfigurationManagementGraph
  janusgraph-core/src/main/java/org/janusgraph/graphdb/management/ConfigurationManagementGraph.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/management/ConfigurationManagementGraphTest.java
Labels: cla: yes

#1380 Prevent deadlock when vertices are removed in parallel
  janusgraph-core/src/main/java/org/janusgraph/graphdb/vertices/StandardVertex.java
Labels: cla: yes

#1362 Fix Apache license copyright template. [skip ci]
  APACHE-2.0.txt
  LICENSE.txt
Labels: cla: yes

#1463 Remove all mentions of Giraph
  docs/hadoop.adoc
  janusgraph-dist/src/assembly/static/conf/hadoop-graph/hadoop-graphson.properties
  janusgraph-dist/src/assembly/static/conf/hadoop-graph/hadoop-gryo.properties
  janusgraph-dist/src/assembly/static/conf/hadoop-graph/hadoop-load.properties
  janusgraph-dist/src/assembly/static/conf/hadoop-graph/hadoop-script.properties
  janusgraph-dist/src/assembly/static/ext/plugins.txt
  janusgraph-dist/src/release/index.html
  janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/cassandra/Cassandra3InputFormat.java
  janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/cassandra/CassandraInputFormat.java
  janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/hbase/HBaseInputFormat.java
  janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/hbase/HBaseSnapshotInputFormat.java
  janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/util/HadoopInputFormat.java
  janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/util/HadoopRecordReader.java
  janusgraph-hadoop-parent/janusgraph-hadoop-core/src/test/resources/cassandra-read.properties
  janusgraph-hadoop-parent/janusgraph-hadoop-core/src/test/resources/hbase-read-snapshot.properties
  janusgraph-hadoop-parent/janusgraph-hadoop-core/src/test/resources/hbase-read.properties
Labels: cla: yes, kind/cleanup

#1487 Merge 0.2 commits licenses
  APACHE-2.0.txt
  LICENSE.txt
Labels: cla: yes

#1488 Merge 0.3 license
  APACHE-2.0.txt
  LICENSE.txt
Labels: cla: yes

#1478 Partial cleanup of JanusGraphTest
  janusgraph-berkeleyje/pom.xml
  janusgraph-test/pom.xml
  janusgraph-test/src/main/java/org/janusgraph/TestCategory.java
  janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/inmemory/InMemoryGraphTest.java
Labels: area/testing, cla: yes, kind/cleanup

#1489 Add Arcade Analytics visualization tool [skip ci]
  README.md
Labels: cla: yes

#1456 Convert HBase TTL param from Integer to long JanusGraph#1454
  janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/org/janusgraph/diskstorage/hbase/HBaseStoreManager.java
  janusgraph-hbase-parent/janusgraph-hbase-core/src/test/java/org/janusgraph/diskstorage/hbase/HBaseStoreManagerMutationTest.java
Labels: cla: yes

#1486 Add deadlock on parallel vertex removal test #1451
  janusgraph-test/src/test/java/org/janusgraph/graphdb/vertices/StandardVertexTest.java
Labels: cla: yes

#1503 Merge 0.2 into 0.3
  janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/org/janusgraph/diskstorage/hbase/HBaseStoreManager.java
  janusgraph-hbase-parent/janusgraph-hbase-core/src/test/java/org/janusgraph/diskstorage/hbase/HBaseStoreManagerMutationTest.java
Labels: cla: yes

#1502 Fix for incorrect CFG documentation #1372
  docs/configuredgraphfactory.adoc
Labels: cla: yes

#1507 Removed support for Elasticsearch versions < 5.0.0 #1490
  .gitignore
  .travis.yml
  TESTING.md
  docs/versions.adoc
  janusgraph-es/pom.xml
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticMajorVersion.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/compat/ES1Compat.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/compat/ES2Compat.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestElasticSearchClient.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticsearchConfigTest.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticsearchIndexTest.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticsearchMultiTypeIndexTest.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/JanusGraphElasticsearchContainer.java
  janusgraph-es/src/test/resources/elasticsearch-old.yml
Labels: cla: yes

#1505 Fix removal of relations in other transaction
  .travis.yml
  janusgraph-core/src/main/java/org/janusgraph/graphdb/relations/AbstractTypedRelation.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/relations/CacheVertexProperty.java
  janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
Labels: cla: yes
