Repository JanusGraph/janusgraph, pull requests merged in 2019-10, with the labels that each got.

#1801 Make index management more reachable [doc only]
  docs/advanced-topics/advschema.md
  docs/advanced-topics/partitioning.md
  docs/basics/schema.md
  docs/index-backend/direct-index-query.md
  docs/index-backend/elasticsearch.md
  docs/index-backend/solr.md
  docs/index-management/index-lifecycle.md
  docs/index-management/index-lifecycle.png
  docs/index-management/index-performance.md
  docs/index-management/index-reindexing.md
  docs/index-management/index-removal.md
  mkdocs.yml
Labels: area/docs, cla: yes, kind/cleanup

#1814 Fix for reindexing OOM issue with CQL backend
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLResultSetKeyIterator.java
Labels: cla: yes

#1822 Use cardinality from a gremlin query to auto create a propertyKey
  janusgraph-core/src/main/java/org/janusgraph/core/Multiplicity.java
  janusgraph-core/src/main/java/org/janusgraph/core/schema/PropertyKeyMaker.java
  janusgraph-core/src/main/java/org/janusgraph/core/schema/SchemaInspector.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphDefaultSchemaMaker.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/types/StandardPropertyKeyMaker.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/types/StandardRelationTypeMaker.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/vertices/AbstractVertex.java
  janusgraph-test/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/JanusGraphDefaultSchemaMakerTest.java
Labels: cla: yes

#1828 Follow up of the Hadoop merge
  janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/formats/cassandra/CassandraBinaryInputFormat.java
  janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/formats/cql/CqlBinaryInputFormat.java
  janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/formats/util/HadoopInputFormat.java
  janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/formats/util/JanusGraphVertexDeserializer.java
  janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/formats/util/input/JanusGraphHadoopSetup.java
  janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/formats/util/input/JanusGraphHadoopSetupCommon.java
  janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/formats/util/input/current/JanusGraphHadoopSetupImpl.java
Labels: cla: yes

#1827 Update properties files to add `gremlin.graph` setting [doc only]
  janusgraph-dist/src/assembly/cfilter/conf/janusgraph-berkeleyje-es.properties
  janusgraph-dist/src/assembly/cfilter/conf/janusgraph-berkeleyje-lucene.properties
  janusgraph-dist/src/assembly/cfilter/conf/janusgraph-berkeleyje-solr.properties
  janusgraph-dist/src/assembly/cfilter/conf/janusgraph-berkeleyje.properties
  janusgraph-dist/src/assembly/cfilter/conf/janusgraph-cassandra-embedded-es.properties
  janusgraph-dist/src/assembly/cfilter/conf/janusgraph-cassandra-embedded-solr.properties
  janusgraph-dist/src/assembly/cfilter/conf/janusgraph-cassandra-embedded.properties
  janusgraph-dist/src/assembly/cfilter/conf/janusgraph-cassandra-es.properties
  janusgraph-dist/src/assembly/cfilter/conf/janusgraph-cassandra-solr.properties
  janusgraph-dist/src/assembly/cfilter/conf/janusgraph-cassandra.properties
  janusgraph-dist/src/assembly/cfilter/conf/janusgraph-cql-es.properties
  janusgraph-dist/src/assembly/cfilter/conf/janusgraph-cql-solr.properties
  janusgraph-dist/src/assembly/cfilter/conf/janusgraph-cql.properties
  janusgraph-dist/src/assembly/cfilter/conf/janusgraph-hbase-es.properties
  janusgraph-dist/src/assembly/cfilter/conf/janusgraph-hbase-solr.properties
  janusgraph-dist/src/assembly/cfilter/conf/janusgraph-hbase.properties
Labels: cla: no

#1732 Use shared cache by default for berkeleydb
  docs/basics/janusgraph-cfg.md
  docs/changelog.md
  docs/storage-backend/bdb.md
  janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJEStoreManager.java
Labels: cla: yes

#1698 Fix conflicting versions of high-scale-lib
  janusgraph-core/pom.xml
  pom.xml
Labels: cla: yes

#1819 Add issue templates to speed up development process
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/flaky-test.md
  .github/ISSUE_TEMPLATE/question.md
Labels: cla: yes

#1862 issue#1763 removed unneeded stack trace
  janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJEStoreManager.java
Labels: cla: no

#1855 Dependences cleanup
  NOTICE.txt
  janusgraph-all/pom.xml
  janusgraph-es/pom.xml
  janusgraph-hadoop/pom.xml
  janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/AbstractGremlinServerIntegrationTest.java
  janusgraph-solr/pom.xml
  janusgraph-test/pom.xml
  pom.xml
Labels: cla: yes, kind/cleanup
