Repository JanusGraph/janusgraph, pull requests merged in 2019-09, with the labels that each got.

#1777 Check repo before deployment
  .travis.yml
Labels: cla: yes

#1785 Remove v0.3 specific doc notes [doc only]
  docs/advanced-topics/serializer.md
  docs/index-backend/field-mapping.md
Labels: cla: yes

#1784 Add index lifecycle documentation [doc only]
  docs/basics/index-lifecycle.md
  docs/basics/index-lifecycle.png
  docs/basics/index-performance.md
  mkdocs.yml
Labels: cla: yes

#1782 Fix Unifi link [doc only]
  README.md
Labels: cla: yes

#1796 Fix broken links to docs [doc only]
  .github/ISSUE_TEMPLATE.md
  RELEASING.md
  janusgraph-core/src/main/java/org/janusgraph/core/JanusGraphFactory.java
  janusgraph-core/src/main/java/org/janusgraph/core/RelationType.java
  janusgraph-core/src/main/java/org/janusgraph/core/attribute/AttributeSerializer.java
  janusgraph-examples/example-berkeleyje/README.md
  janusgraph-examples/example-cassandra/README.md
  janusgraph-examples/example-common/README.md
  janusgraph-examples/example-cql/README.md
  janusgraph-examples/example-hbase/README.md
  janusgraph-examples/example-remotegraph/README.md
Labels: area/docs, cla: yes

#1798 Support hadoop index management for cql
  janusgraph-cql/pom.xml
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java
  janusgraph-cql/src/test/java/org/janusgraph/JanusGraphCassandraContainer.java
  janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/MapReduceIndexJobs.java
  janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/MapReduceIndexManagement.java
  janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/formats/cql/CqlBinaryInputFormat.java
  janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/scan/AbstractHadoopScanRunner.java
  janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/scan/CQLHadoopScanRunner.java
  janusgraph-hadoop-parent/janusgraph-hadoop-core/src/test/java/org/janusgraph/hadoop/AbstractInputFormatIT.java
  janusgraph-hadoop-parent/janusgraph-hadoop-core/src/test/java/org/janusgraph/hadoop/CQLIndexManagementIT.java
  janusgraph-hadoop-parent/janusgraph-hadoop-core/src/test/java/org/janusgraph/hadoop/CQLInputFormatIT.java
  janusgraph-hadoop-parent/janusgraph-hadoop-core/src/test/java/org/janusgraph/hadoop/CQLScanJobIT.java
  janusgraph-hadoop-parent/pom.xml
Labels: area/hadoop, cla: yes, kind/enhancement, storage/cassandra

#1712 Fix deletion a non-existing key in berkeleydb
  janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJEKeyValueStore.java
  janusgraph-test/src/main/java/org/janusgraph/diskstorage/KeyColumnValueStoreTest.java
Labels: cla: yes

#1804 retry_on_conflict for mixed index
  docs/basics/janusgraph-cfg.md
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestClientSetup.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestElasticSearchClient.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/rest/RestClientSetupTest.java
Labels: index/elasticsearch

#1406 Fix lucene tokenize if single token #1405
  janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java
  janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java
  janusgraph-test/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java
Labels: cla: yes

#1731 Fix GhostVertexRemover
  janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/job/GhostVertexRemover.java
  janusgraph-test/src/main/java/org/janusgraph/olap/OLAPTest.java
Labels: cla: yes

#1753 Make berkeleyje return real iterator
  janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJEKeyValueStore.java
Labels: cla: yes

#1755 Improve reindex for mixed indexes
  janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/job/IndexRepairJob.java
Labels: cla: yes

#1810 Update contributing and release as follow up for mkdocs switch
  .travis.yml
  CONTRIBUTING.md
  RELEASING.md
  docs/basics/janusgraph-cfg.md
  janusgraph-core/src/main/java/org/janusgraph/util/system/ConfigurationPrinter.java
Labels: area/docs, cla: yes
