Repository JanusGraph/janusgraph, pull requests merged in 2020-01, with the labels that each got.

#1906 JANUSGRAPH-1866 Filter out only system vertices in Hadoop Vertex dese…
  janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/formats/util/JanusGraphVertexDeserializer.java
  janusgraph-hadoop/src/test/java/org/janusgraph/hadoop/AbstractInputFormatIT.java
  janusgraph-hadoop/src/test/java/org/janusgraph/hadoop/HBaseSnapshotInputFormatIT.java
Labels: area/hadoop, cla: yes

#1915 Update to TinkerPop 3.4.4
  docs/basics/schema.md
  docs/changelog.md
  mkdocs.yml
  pom.xml
Labels: cla: yes

#1926 * Improve the CQLIterator performance by using getPagingStateUnsafe
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java
Labels: cla: external

#1872 Issue #1871: Close graph instance at end of mapper run.
  janusgraph-hadoop-parent/janusgraph-hadoop-core/src/main/java/org/janusgraph/hadoop/scan/HadoopVertexScanMapper.java
Labels: cla: yes

#1483 issue #1482 initial contribution of production in-memory backend
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/StaticArrayBuffer.java
  janusgraph-inmemory/src/main/java/org/janusgraph/diskstorage/inmemory/BufferPage.java
  janusgraph-inmemory/src/main/java/org/janusgraph/diskstorage/inmemory/BufferPageUtils.java
  janusgraph-inmemory/src/main/java/org/janusgraph/diskstorage/inmemory/InMemoryColumnValueStore.java
  janusgraph-inmemory/src/main/java/org/janusgraph/diskstorage/inmemory/InMemoryKeyColumnValueStore.java
  janusgraph-inmemory/src/main/java/org/janusgraph/diskstorage/inmemory/InMemoryKeyColumnValueStoreFragmentationReport.java
  janusgraph-inmemory/src/main/java/org/janusgraph/diskstorage/inmemory/InMemoryStoreManager.java
  janusgraph-inmemory/src/main/java/org/janusgraph/diskstorage/inmemory/MemoryEntryList.java
  janusgraph-inmemory/src/main/java/org/janusgraph/diskstorage/inmemory/MultiPageEntryBuffer.java
  janusgraph-inmemory/src/main/java/org/janusgraph/diskstorage/inmemory/SharedEntryBuffer.java
  janusgraph-inmemory/src/main/java/org/janusgraph/diskstorage/inmemory/SharedEntryBufferFragmentationReport.java
  janusgraph-inmemory/src/main/java/org/janusgraph/diskstorage/inmemory/SinglePageEntryBuffer.java
  janusgraph-inmemory/src/test/java/org/janusgraph/diskstorage/inmemory/BufferPageTest.java
  janusgraph-inmemory/src/test/java/org/janusgraph/diskstorage/inmemory/InMemoryColumnValueStoreTest.java
  janusgraph-inmemory/src/test/java/org/janusgraph/diskstorage/inmemory/InMemoryStoreManagerTest.java
  janusgraph-inmemory/src/test/java/org/janusgraph/diskstorage/inmemory/MultiPageEntryBufferTest.java
  janusgraph-inmemory/src/test/java/org/janusgraph/diskstorage/inmemory/TestPagedBufferColumnValueStore.java
Labels: cla: yes

#1909 Add 'Getting Started' guide to documentation [doc only]
  docs/basics/gremlin.md
  docs/getting-started/architecture-layer-diagram.svg
  docs/getting-started/architecture.md
  docs/getting-started/basic-usage.md
  docs/getting-started/graph-of-the-gods-2.png
  docs/getting-started/installation.md
  docs/index.md
  mkdocs.yml
Labels: cla: external

#1931 JanusGraph release 0.4.1 [full build]
  docs/changelog.md
  janusgraph-all/pom.xml
  janusgraph-berkeleyje/pom.xml
  janusgraph-bigtable/pom.xml
  janusgraph-cassandra/pom.xml
  janusgraph-codepipelines-ci/pom.xml
  janusgraph-core/pom.xml
  janusgraph-cql/pom.xml
  janusgraph-dist/janusgraph-dist-hadoop-2/pom.xml
  janusgraph-dist/pom.xml
  janusgraph-doc/pom.xml
  janusgraph-es/pom.xml
  janusgraph-examples/example-berkeleyje/pom.xml
  janusgraph-examples/example-cassandra/pom.xml
  janusgraph-examples/example-common/pom.xml
  janusgraph-examples/example-cql/pom.xml
  janusgraph-examples/example-hbase/pom.xml
  janusgraph-examples/example-remotegraph/pom.xml
  janusgraph-examples/example-tinkergraph/pom.xml
  janusgraph-examples/pom.xml
  janusgraph-hadoop-parent/janusgraph-hadoop-2/pom.xml
  janusgraph-hadoop-parent/janusgraph-hadoop-core/pom.xml
  janusgraph-hadoop-parent/janusgraph-hadoop/pom.xml
  janusgraph-hadoop-parent/pom.xml
  janusgraph-hbase-parent/janusgraph-hbase-10/pom.xml
  janusgraph-hbase-parent/janusgraph-hbase-core/pom.xml
  janusgraph-hbase-parent/janusgraph-hbase-server/pom.xml
  janusgraph-hbase-parent/janusgraph-hbase/pom.xml
  janusgraph-hbase-parent/pom.xml
  janusgraph-lucene/pom.xml
  janusgraph-server/pom.xml
  janusgraph-solr/pom.xml
  janusgraph-test/pom.xml
  mkdocs.yml
  pom.xml
Labels: cla: yes

#1934 Update in-memory backend documentation
  docs/storage-backend/inmemorybackend.md
Labels: cla: yes

#1940 Split up hadoop implementations [full build]
  .travis.yml
  docs/advanced-topics/hadoop.md
  docs/changelog.md
  janusgraph-all/pom.xml
  janusgraph-cassandra/pom.xml
  janusgraph-cassandra/src/main/java/org/janusgraph/diskstorage/cassandra/AbstractCassandraStoreManager.java
  janusgraph-cassandra/src/main/java/org/janusgraph/hadoop/CassandraHadoopStoreManager.java
  janusgraph-cassandra/src/main/java/org/janusgraph/hadoop/CassandraMapReduceIndexJobsUtils.java
  janusgraph-cassandra/src/main/java/org/janusgraph/hadoop/formats/cassandra/CassandraBinaryInputFormat.java
  janusgraph-cassandra/src/main/java/org/janusgraph/hadoop/formats/cassandra/CassandraBinaryRecordReader.java
  janusgraph-cassandra/src/main/java/org/janusgraph/hadoop/formats/cassandra/CassandraInputFormat.java
  janusgraph-cassandra/src/main/java/org/janusgraph/hadoop/scan/CassandraHadoopScanRunner.java
  janusgraph-cassandra/src/test/java/org/janusgraph/hadoop/CassandraIndexManagementIT.java
  janusgraph-cassandra/src/test/java/org/janusgraph/hadoop/CassandraInputFormatIT.java
  janusgraph-cassandra/src/test/java/org/janusgraph/hadoop/CassandraScanJobIT.java
  janusgraph-cassandra/src/test/resources/cassandra-read.properties
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/StoreManager.java
  janusgraph-cql/pom.xml
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java
  janusgraph-cql/src/main/java/org/janusgraph/hadoop/CqlHadoopStoreManager.java
  janusgraph-cql/src/main/java/org/janusgraph/hadoop/CqlMapReduceIndexJobsUtils.java
  janusgraph-cql/src/main/java/org/janusgraph/hadoop/formats/cql/CqlBinaryInputFormat.java
  janusgraph-cql/src/main/java/org/janusgraph/hadoop/formats/cql/CqlBinaryRecordReader.java
  janusgraph-cql/src/main/java/org/janusgraph/hadoop/formats/cql/CqlInputFormat.java
  janusgraph-cql/src/main/java/org/janusgraph/hadoop/scan/CQLHadoopScanRunner.java
  janusgraph-cql/src/test/java/org/janusgraph/hadoop/CQLIndexManagementIT.java
  janusgraph-cql/src/test/java/org/janusgraph/hadoop/CQLInputFormatIT.java
  janusgraph-cql/src/test/java/org/janusgraph/hadoop/CQLScanJobIT.java
  janusgraph-cql/src/test/resources/cql-read.properties
  janusgraph-dist/src/assembly/static/conf/hadoop-graph/read-cassandra-3.properties
  janusgraph-driver/pom.xml
  janusgraph-hadoop/pom.xml
  janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/HadoopStoreManager.java
  janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/MapReduceIndexJobs.java
  janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/MapReduceIndexManagement.java
  janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/formats/cassandra/Cassandra3BinaryInputFormat.java
  janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/formats/cassandra/CqlBridgeRecordReader.java
  janusgraph-hadoop/src/test/java/org/janusgraph/hadoop/Cassandra3InputFormatIT.java
  janusgraph-hbase-parent/janusgraph-hbase-10/pom.xml
  janusgraph-hbase-parent/janusgraph-hbase-core/pom.xml
  janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/org/janusgraph/diskstorage/hbase/HBaseStoreManager.java
  janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/org/janusgraph/hadoop/HBaseHadoopStoreManager.java
  janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/org/janusgraph/hadoop/HBaseMapReduceIndexJobsUtils.java
  janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/org/janusgraph/hadoop/formats/hbase/HBaseBinaryInputFormat.java
  janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/org/janusgraph/hadoop/formats/hbase/HBaseBinaryRecordReader.java
  janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/org/janusgraph/hadoop/formats/hbase/HBaseInputFormat.java
  janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/org/janusgraph/hadoop/formats/hbase/HBaseSnapshotBinaryInputFormat.java
  janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/org/janusgraph/hadoop/formats/hbase/HBaseSnapshotInputFormat.java
  janusgraph-hbase-parent/janusgraph-hbase-core/src/main/java/org/janusgraph/hadoop/scan/HBaseHadoopScanRunner.java
  janusgraph-hbase-parent/janusgraph-hbase-core/src/test/java/org/janusgraph/hadoop/HBaseIndexManagementIT.java
  janusgraph-hbase-parent/janusgraph-hbase-core/src/test/java/org/janusgraph/hadoop/HBaseInputFormatIT.java
  janusgraph-hbase-parent/janusgraph-hbase-core/src/test/java/org/janusgraph/hadoop/HBaseSnapshotInputFormatIT.java
  janusgraph-hbase-parent/janusgraph-hbase-core/src/test/resources/hbase-read-snapshot.properties
  janusgraph-hbase-parent/janusgraph-hbase-core/src/test/resources/hbase-read.properties
Labels: area/hadoop, cla: yes, kind/cleanup

#1941 Bump jackson2.version from 2.6.6 to 2.10.2
  pom.xml
Labels: cla: yes, dependencies, kind/security
