Repository JanusGraph/janusgraph, pull requests merged in 2020-02, with the labels that each got.

#1918 Add a new DefaultSchemaMaker that logs auto created objects #1917
  docs/basics/janusgraph-cfg.md
  janusgraph-core/src/main/java/org/janusgraph/core/schema/LoggingSchemaMaker.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java
Labels: cla: external

#1884 Await id block only for distributed stores
  janusgraph-backend-testutils/src/main/java/org/janusgraph/diskstorage/IDAuthorityTest.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/idmanagement/ConsistentKeyIDAuthority.java
Labels: cla: yes

#1943 Copy labels during optimizing Or steps
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/HasStepFolder.java
  janusgraph-test/src/test/java/org/janusgraph/blueprints/process/traversal/strategy/optimization/JanusGraphStepStrategyTest.java
Labels: cla: yes

#1886 Optimize single index query
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/GraphCentricQueryBuilder.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/JointIndexQuery.java
Labels: cla: yes

#1952 Bump datastax cassandra driver to 3.8.0 [full build]
  pom.xml
Labels: cla: yes, dependencies

#1954 Update Tinkerpop to 3.4.5
  docs/changelog.md
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphPropertiesStep.java
  mkdocs.yml
  pom.xml
Labels: cla: yes

#1956 [SECURITY] Use HTTPS to resolve dependencies in Maven Build
  janusgraph-berkeleyje/pom.xml
  pom.xml
Labels: cla: external

#1949 Set RelationTypeIndex status to ENABLED when the index uses a new key
  docs/index-management/index-performance.md
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java
Labels: cla: external

#1959 Bump ElasticSearch to 7.6.0
  docs/changelog.md
  janusgraph-es/pom.xml
  pom.xml
Labels: cla: yes, dependencies, index/elasticsearch

#1951 Fix missing plugins javadoc and maven plugins for driver module
  janusgraph-all/pom.xml
  janusgraph-core/pom.xml
  janusgraph-driver/pom.xml
Labels: cla: yes

#1964 Add G DATA use case blog post [doc only]
  README.md
Labels: cla: yes

#1966 Pass HadoopManager through MetricInstrumentedStoreManager
  janusgraph-backend-testutils/pom.xml
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/MetricInstrumentedStoreManager.java
  janusgraph-server/pom.xml
  janusgraph-test/src/test/java/org/janusgraph/diskstorage/util/MetricInstrumentedStoreManagerTest.java
  pom.xml
Labels: cla: yes

#1977 Fix range interval intersection
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/util/datastructures/RangeInterval.java
Labels: cla: yes

#1960 Optimize hasId() in the same way as is()
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/AdjacentVertexFilterOptimizerStrategy.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/AdjacentVertexFilterOptimizerStrategyTest.java
Labels: cla: external

#1829 Make "janusgraphmr.ioformat.filter-partitioned-vertices" option work
  janusgraph-cassandra/src/test/java/org/janusgraph/hadoop/CassandraScanJobIT.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/AbstractConfiguration.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/BasicConfiguration.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/Configuration.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/MergedConfiguration.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/MixedConfiguration.java
  janusgraph-cql/src/test/java/org/janusgraph/hadoop/CQLScanJobIT.java
  janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/formats/util/input/current/JanusGraphHadoopSetupImpl.java
  janusgraph-hadoop/src/test/java/org/janusgraph/hadoop/ConfigurationTest.java
Labels: cla: external

#1963 Improve lucene tokenizer
  janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java
Labels: cla: external

#1982 Update Tinkerpop to 3.4.6
  docs/changelog.md
  mkdocs.yml
  pom.xml
Labels: cla: yes

#1972 Add TEXTSTRING support for lucene index
  janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneCustomAnalyzer.java
  janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java
Labels: cla: external

#1986 Fix scroll leak in scroll handling.
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchScroll.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticSearchScrollTest.java
Labels: cla: no

#1978 Activate automated release build tests
  .travis.yml
  docs/changelog.md
  janusgraph-cassandra/pom.xml
  janusgraph-dist/pom.xml
  janusgraph-dist/src/assembly/descriptor/cassandra.component.xml
  janusgraph-dist/src/assembly/static/bin/cassandra.in.sh
  janusgraph-dist/src/assembly/static/bin/gremlin-server.bat
  janusgraph-dist/src/assembly/static/bin/gremlin-server.sh
  janusgraph-dist/src/assembly/static/conf/es/elasticsearch.yml
  janusgraph-dist/src/assembly/static/log/cassandra.log
  janusgraph-dist/src/pkg/static/debian/.gitignore
  janusgraph-dist/src/release/commit-compat-version.sh
  janusgraph-dist/src/release/release.sh
  janusgraph-dist/src/release/rewrite-tag.sh
  janusgraph-dist/src/test/expect/compat-test.expect.vm
  janusgraph-dist/src/test/expect/getting-started.expect.vm
  janusgraph-dist/src/test/expect/gremlin-shell-args.expect.vm
  janusgraph-dist/src/test/expect/janusgraph-sh.expect.vm
  janusgraph-dist/src/test/expect/single-vertex.expect.vm
  janusgraph-dist/src/test/java/org/janusgraph/pkgtest/AbstractJanusGraphAssemblyIT.java
  janusgraph-dist/src/test/java/org/janusgraph/pkgtest/BerkeleyESAssemblyIT.java
  janusgraph-dist/src/test/java/org/janusgraph/pkgtest/CassandraEmbeddedESAssemblyIT.java
  janusgraph-dist/src/test/java/org/janusgraph/pkgtest/CassandraThriftAssemblyIT.java
  janusgraph-dist/src/test/java/org/janusgraph/pkgtest/CqlAssemblyIT.java
  janusgraph-dist/src/test/java/org/janusgraph/pkgtest/CqlESAssemblyIT.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/JanusGraphElasticsearchContainer.java
  pom.xml
Labels: area/testing, cla: yes, kind/cleanup, kind/enhancement
