Repository JanusGraph/janusgraph, pull requests merged in 2020-03, with the labels that each got.

#1995 Fix kvstore iterator
  janusgraph-backend-testutils/src/main/java/org/janusgraph/olap/OLAPTest.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/keyvalue/OrderedKeyValueStoreAdapter.java
Labels: cla: external

#1992 Emphasize that property key cannot be of primitive type [doc only]
  docs/basics/schema.md
  janusgraph-core/src/main/java/org/janusgraph/graphdb/types/StandardPropertyKeyMaker.java
Labels: cla: external

#2003 Bump netty to 4.1.45
  pom.xml
Labels: cla: yes

#2000 Support range limit -1 in gremlin query
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/QueryUtil.java
Labels: cla: external

#1993 Fix adjacent query bug when label is null and direction is both
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/BasicVertexCentricQueryBuilder.java
Labels: cla: external

#1961 Apply optimizations to queries to make use of adjacent ids
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/StandardJanusGraph.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/AdjacentVertexHasIdOptimizerStrategy.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/AdjacentVertexIsOptimizerStrategy.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/AdjacentVertexOptimizerStrategy.java
Labels: cla: external, kind/performance

#1994 BasicVertexCentricQueryBuilder: Reduce duplicate constructQuery calls
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/BasicVertexCentricQueryBuilder.java
Labels: cla: external

#2002 Unify headers and use file names in hadoop [doc only]
  TESTING.md
  docs/advanced-topics/advschema.md
  docs/advanced-topics/bulk-loading.md
  docs/advanced-topics/eventual-consistency.md
  docs/advanced-topics/hadoop.md
  docs/advanced-topics/migrating.md
  docs/advanced-topics/monitoring.md
  docs/advanced-topics/recovery.md
  docs/advanced-topics/serializer.md
  docs/basics/cache.md
  docs/basics/common-questions.md
  docs/basics/configuration-reference.md
  docs/basics/configuration.md
  docs/basics/deployment.md
  docs/basics/example-config.md
  docs/basics/gremlin.md
  docs/basics/technical-limitations.md
  docs/basics/transaction-log.md
  docs/basics/transactions.md
  docs/connecting/java.md
  docs/index-backend/direct-index-query.md
  docs/index-backend/elasticsearch.md
  docs/index-backend/field-mapping.md
  docs/index-backend/lucene.md
  docs/index-backend/solr.md
  docs/index-backend/text-search.md
  docs/index-management/index-lifecycle.md
  docs/index-management/index-performance.md
  docs/storage-backend/bdb.md
  docs/storage-backend/bigtable.md
  docs/storage-backend/cassandra.md
  docs/storage-backend/hbase.md
  docs/storage-backend/inmemorybackend.md
  janusgraph-dist/README.md
Labels: area/docs, cla: yes, kind/cleanup

#2008 Remove outdated note about order [doc only]
  docs/index-management/index-performance.md
Labels: cla: yes

#2012 Bump junit to 5.5.2
  pom.xml
Labels: cla: yes, dependencies

#1975 Fix lucene docid tokenization
  janusgraph-backend-testutils/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java
  janusgraph-inmemory/src/test/java/org/janusgraph/graphdb/inmemory/InMemoryOLAPTest.java
  janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneCustomAnalyzer.java
  janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java
Labels: cla: external

#2025 Fix issues with release build tests
  janusgraph-dist/pom.xml
  janusgraph-dist/src/assembly/descriptor/common.component.xml
  janusgraph-dist/src/assembly/static/bin/janusgraph.sh
  janusgraph-dist/src/assembly/static/conf/es/jvm.options
Labels: cla: yes

#2014 Fix created logs are not added into processorLogs
  janusgraph-core/src/main/java/org/janusgraph/graphdb/log/StandardLogProcessorFramework.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/log/StandardLogProcessorFrameworkTest.java
Labels: cla: yes

#2027 Bump ElasticSearch to 7.6.1
  docs/changelog.md
  janusgraph-es/pom.xml
  pom.xml
Labels: cla: yes

#2031 Bump jacoco to 0.8.5
  pom.xml
Labels: cla: yes

#2029 Move reflections to reflections8
  janusgraph-core/pom.xml
  janusgraph-core/src/main/java/org/janusgraph/core/util/ReflectiveConfigOptionLoader.java
  janusgraph-test/src/test/java/org/janusgraph/core/util/ReflectiveConfigOptionLoaderTest.java
  pom.xml
Labels: cla: yes

#2034 JanusGraph release 0.5.0 [full build]
  NOTICE.txt
  docs/changelog.md
  janusgraph-all/pom.xml
  janusgraph-backend-testutils/pom.xml
  janusgraph-berkeleyje/pom.xml
  janusgraph-bigtable/pom.xml
  janusgraph-cassandra/pom.xml
  janusgraph-codepipelines-ci/pom.xml
  janusgraph-core/pom.xml
  janusgraph-cql/pom.xml
  janusgraph-dist/pom.xml
  janusgraph-doc/pom.xml
  janusgraph-driver/pom.xml
  janusgraph-es/pom.xml
  janusgraph-examples/example-berkeleyje/pom.xml
  janusgraph-examples/example-cassandra/pom.xml
  janusgraph-examples/example-common/pom.xml
  janusgraph-examples/example-cql/pom.xml
  janusgraph-examples/example-hbase/pom.xml
  janusgraph-examples/example-remotegraph/pom.xml
  janusgraph-examples/example-tinkergraph/pom.xml
  janusgraph-examples/pom.xml
  janusgraph-hadoop/pom.xml
  janusgraph-hbase-parent/janusgraph-hbase-10/pom.xml
  janusgraph-hbase-parent/janusgraph-hbase-core/pom.xml
  janusgraph-hbase-parent/janusgraph-hbase-server/pom.xml
  janusgraph-hbase-parent/janusgraph-hbase/pom.xml
  janusgraph-hbase-parent/pom.xml
  janusgraph-inmemory/pom.xml
  janusgraph-lucene/pom.xml
  janusgraph-server/pom.xml
  janusgraph-solr/pom.xml
  janusgraph-test/pom.xml
  pom.xml
Labels: cla: yes

#2039 Fix ElasticSearch scroll result is created even on no scroll CTR
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphBaseTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java
Labels: cla: yes

#2047 Fix wrong example in index-performance.md [doc only]
  docs/index-management/index-performance.md
Labels: cla: external

#2021 Remove codepipelines-ci
  NOTICE.txt
  janusgraph-codepipelines-ci/README.md
  janusgraph-codepipelines-ci/pipe.yml
  janusgraph-codepipelines-ci/pom.xml
  janusgraph-codepipelines-ci/src/main/java/org/janusgraph/codepipelines/AwsCodePipelinesCi.java
  janusgraph-codepipelines-ci/src/main/java/org/janusgraph/codepipelines/AwsCodePipelinesLogic.java
  janusgraph-codepipelines-ci/src/main/java/org/janusgraph/codepipelines/model/EnvironmentMapping.java
  janusgraph-codepipelines-ci/src/main/java/org/janusgraph/codepipelines/model/ParallelBuildAction.java
  janusgraph-codepipelines-ci/src/main/java/org/janusgraph/codepipelines/model/PipelineDefinition.java
  janusgraph-codepipelines-ci/src/main/java/org/janusgraph/codepipelines/model/PipelineDefinitions.java
  janusgraph-codepipelines-ci/src/main/resources/log4j.properties
  janusgraph-codepipelines-ci/src/test/java/org/janusgraph/codepipelines/TestContainerOne.java
  janusgraph-codepipelines-ci/src/test/java/org/janusgraph/codepipelines/TestContainerTwo.java
  janusgraph-codepipelines-ci/src/test/resources/excludes
  janusgraph-codepipelines-ci/src/test/resources/longTests1
  janusgraph-codepipelines-ci/src/test/resources/longTests2
  janusgraph-codepipelines-ci/tp-pipe.yml
  pom.xml
Labels: cla: yes

#2057 Disable ML feature in testing ES distribution
  janusgraph-dist/src/assembly/static/conf/es/elasticsearch.yml
Labels: cla: yes

#2045 [doc only] #2044 Some properties like index.*.elastic…
  docs/basics/common-questions.md
  docs/basics/janusgraph-cfg.md
  janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java
Labels: cla: external

#1991 Add janusgraph-inmemory.properties and introduce in basic usage [doc only]
  docs/getting-started/basic-usage.md
  janusgraph-dist/src/assembly/cfilter/conf/janusgraph-inmemory.properties
Labels: cla: external

#2059 JanusGraph release 0.5.1 [full build]
  docs/changelog.md
  janusgraph-all/pom.xml
  janusgraph-backend-testutils/pom.xml
  janusgraph-berkeleyje/pom.xml
  janusgraph-bigtable/pom.xml
  janusgraph-cassandra/pom.xml
  janusgraph-codepipelines-ci/pom.xml
  janusgraph-core/pom.xml
  janusgraph-cql/pom.xml
  janusgraph-dist/pom.xml
  janusgraph-doc/pom.xml
  janusgraph-driver/pom.xml
  janusgraph-es/pom.xml
  janusgraph-examples/example-berkeleyje/pom.xml
  janusgraph-examples/example-cassandra/pom.xml
  janusgraph-examples/example-common/pom.xml
  janusgraph-examples/example-cql/pom.xml
  janusgraph-examples/example-hbase/pom.xml
  janusgraph-examples/example-remotegraph/pom.xml
  janusgraph-examples/example-tinkergraph/pom.xml
  janusgraph-examples/pom.xml
  janusgraph-hadoop/pom.xml
  janusgraph-hbase-parent/janusgraph-hbase-10/pom.xml
  janusgraph-hbase-parent/janusgraph-hbase-core/pom.xml
  janusgraph-hbase-parent/janusgraph-hbase-server/pom.xml
  janusgraph-hbase-parent/janusgraph-hbase/pom.xml
  janusgraph-hbase-parent/pom.xml
  janusgraph-inmemory/pom.xml
  janusgraph-lucene/pom.xml
  janusgraph-server/pom.xml
  janusgraph-solr/pom.xml
  janusgraph-test/pom.xml
  mkdocs.yml
  pom.xml
Labels: cla: yes

#2064 Update Bigtable version to 1.14.0 and switch shaded dependency to 2x
  docs/changelog.md
  docs/storage-backend/bigtable.md
  janusgraph-bigtable/pom.xml
  pom.xml
Labels: cla: external
