Repository JanusGraph/janusgraph, pull requests merged in 2020-09, with the labels that each got.

#2207 GraphCentricQueryBuilder: Fix wrong query limit estimate
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/GraphCentricQueryBuilder.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/query/QueryTest.java
Labels: cla: external

#2209 Include step labels in optimized queries
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/AdjacentVertexOptimizerStrategy.java
Labels: cla: external

#2198 Allow nesting CONTAIN predicates with and/or
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/QueryUtil.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/condition/PredicateCondition.java
Labels: cla: external

#2131 Replace the gremlin-server.sh with a janusgraph-server.sh
  docs/basics/server.md
  docs/changelog.md
  docs/getting-started/installation.md
  docs/storage-backend/cassandra.md
  janusgraph-dist/docker-compose.yml
  janusgraph-dist/src/assembly/static/bin/gremlin-server.sh
  janusgraph-dist/src/assembly/static/bin/janusgraph-server.sh
  janusgraph-dist/src/assembly/static/bin/janusgraph.sh
  janusgraph-dist/src/assembly/static/conf/jvm.options
  janusgraph-dist/src/assembly/static/conf/log4j-server.properties
  janusgraph-dist/src/test/expect/janusgraph-server-sh.after.expect.vm
  janusgraph-dist/src/test/expect/janusgraph-server-sh.before.expect.vm
  janusgraph-dist/src/test/expect/janusgraph-sh.expect.vm
  janusgraph-dist/src/test/java/org/janusgraph/pkgtest/AbstractJanusGraphAssemblyIT.java
  janusgraph-dist/src/test/java/org/janusgraph/pkgtest/BerkeleyAssemblyIT.java
  janusgraph-dist/src/test/java/org/janusgraph/pkgtest/BerkeleyESAssemblyIT.java
  janusgraph-dist/src/test/java/org/janusgraph/pkgtest/CqlAssemblyIT.java
  janusgraph-dist/src/test/java/org/janusgraph/pkgtest/CqlESAssemblyIT.java
  janusgraph-dist/src/test/java/org/janusgraph/pkgtest/InMemoryAssemblyIT.java
  janusgraph-examples/example-remotegraph/README.md
Labels: cla: external

#2178 Bump guava 29.0-jre [full build]
  janusgraph-server/pom.xml
  pom.xml
Labels: cla: external, dependencies

#2215 Bump junit and testcontainers and drop some packages
  NOTICE.txt
  pom.xml
Labels: cla: external, dependencies, kind/cleanup

#2163 Add IgnorePropertySchemaMaker
  docs/basics/janusgraph-cfg.md
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/core/EmptyJanusGraphVertexProperty.java
  janusgraph-core/src/main/java/org/janusgraph/core/JanusGraphVertexProperty.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/relations/AbstractTypedRelation.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/types/typemaker/DisableDefaultSchemaMaker.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/types/typemaker/IgnorePropertySchemaMaker.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/vertices/AbstractVertex.java
  janusgraph-inmemory/src/test/java/org/janusgraph/graphdb/inmemory/InMemoryGraphTest.java
Labels: cla: external
