Repository JanusGraph/janusgraph, pull requests merged in 2020-12, with the labels that each got.

#2158 Add optional datastax request logger
  docs/basics/janusgraph-cfg.md
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java
  janusgraph-cql/src/test/java/org/janusgraph/graphdb/cql/CQLGraphTest.java
Labels: cla: external

#2265 Fix neq and null condition query behavior
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/QueryUtil.java
  janusgraph-driver/src/main/java/org/janusgraph/core/attribute/Cmp.java
Labels: cla: external

#2266 Move release tests and doc to GitHub Actions
  .editorconfig
  .github/workflows/ci-docs.yml
  .github/workflows/ci-release.yml
  .travis.yml
  RELEASING.md
  docs/changelog.md
  docs/docs.Dockerfile
  docs/requirements.txt
  janusgraph-berkeleyje/pom.xml
  janusgraph-cql/src/test/resources/docker/docker-compose.yml
  pom.xml
Labels: area/docs, area/testing, cla: external

#2274 Fix changes on master branch [doc only]
  .github/workflows/ci-docs.yml
Labels: cla: external

#2275 Fix documentation deployment [doc only]
  .github/workflows/ci-docs.yml
  .github/workflows/ci-release.yml
  docs.Dockerfile
  requirements.txt
Labels: cla: external

#2276 Remove doc build from travis and update dockerfiles [doc only]
  .travis.yml
  docs.Dockerfile
  docs/changelog.md
  mkdocs.yml
  requirements.txt
Labels: cla: external

#2277 Replace custom FlakyTest extensions
  TESTING.md
  janusgraph-backend-testutils/pom.xml
  janusgraph-backend-testutils/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/diskstorage/log/LogTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/testutil/FlakyTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/testutil/FlakyTestExtension.java
  janusgraph-berkeleyje/src/test/java/org/janusgraph/graphdb/berkeleyje/BerkeleyOperationCountingTest.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/BerkeleyElasticsearchTest.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/CQLElasticsearchTest.java
  janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/SolrJanusGraphIndexTest.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/vertices/StandardVertexTest.java
  pom.xml
Labels: cla: external

#2253 Add serializiation fallback for older janusgraph drivers
  docs/changelog.md
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/DeprecatedJanusGraphPSerializer.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphIoRegistry.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphIoRegistryV1d0.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphPSerializer.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/graphson/JanusGraphSONModule.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/graphson/JanusGraphSONModuleV2d0.java
  janusgraph-driver/src/test/java/org/janusgraph/graphdb/tinkerpop/JanusGraphIoRegistryTest.java
Labels: cla: external

#2284 Add eBay to production users
  README.md
Labels: cla: external

#2293 Improve tp-tests running behavior [tp-tests]
  .github/workflows/ci-release.yml
Labels: cla: external

#2204 Update TinkerPop to 3.4.9 [tp-tests]
  docs/changelog.md
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphPropertiesStep.java
  janusgraph-hbase-parent/janusgraph-hbase-10/pom.xml
  mkdocs.yml
  pom.xml
Labels: cla: external, dependencies

#2290 Use available page size for CQL result set instead of forced page size [full build]
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java
Labels: cla: external

#2298 Refactor MultiIterator to reduce iteration cycles
  janusgraph-core/src/main/java/org/janusgraph/graphdb/util/MultiIterator.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/util/MultiIteratorTest.java
Labels: cla: external

#2301 JanusGraph release v0.5.3 [full build]
  docs/changelog.md
  janusgraph-all/pom.xml
  janusgraph-backend-testutils/pom.xml
  janusgraph-berkeleyje/pom.xml
  janusgraph-bigtable/pom.xml
  janusgraph-cassandra/pom.xml
  janusgraph-codepipelines-ci/pom.xml
  janusgraph-core/pom.xml
  janusgraph-cql/pom.xml
  janusgraph-dist/pom.xml
  janusgraph-doc/pom.xml
  janusgraph-driver/pom.xml
  janusgraph-es/pom.xml
  janusgraph-examples/example-berkeleyje/pom.xml
  janusgraph-examples/example-cassandra/pom.xml
  janusgraph-examples/example-common/pom.xml
  janusgraph-examples/example-cql/pom.xml
  janusgraph-examples/example-hbase/pom.xml
  janusgraph-examples/example-remotegraph/pom.xml
  janusgraph-examples/example-tinkergraph/pom.xml
  janusgraph-examples/pom.xml
  janusgraph-hadoop/pom.xml
  janusgraph-hbase-parent/janusgraph-hbase-10/pom.xml
  janusgraph-hbase-parent/janusgraph-hbase-core/pom.xml
  janusgraph-hbase-parent/janusgraph-hbase-server/pom.xml
  janusgraph-hbase-parent/janusgraph-hbase/pom.xml
  janusgraph-hbase-parent/pom.xml
  janusgraph-inmemory/pom.xml
  janusgraph-lucene/pom.xml
  janusgraph-server/pom.xml
  janusgraph-solr/pom.xml
  janusgraph-test/pom.xml
  mkdocs.yml
  pom.xml
Labels: cla: external

#2319 Remove snappy dependency
  pom.xml
Labels: cla: external

#2314 Activate codecov in PRs
  .codecov.yml
Labels: cla: external
