Repository JanusGraph/janusgraph, pull requests merged in 2020-04, with the labels that each got.

#2070 Fix #2069: Replace misleading docs about default storage backend
  docs/getting-started/installation.md
Labels: cla: external

#2062 Use requireUpperBoundDeps to ensure packages are aligned with deps
  janusgraph-hbase-parent/janusgraph-hbase-server/pom.xml
  pom.xml
Labels: cla: yes

#2007 Fix some issues with FulgoraGraphComputer
  janusgraph-backend-testutils/src/main/java/org/janusgraph/olap/OLAPTest.java
  janusgraph-core/src/main/java/org/janusgraph/core/JanusGraph.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/computer/FulgoraGraphComputer.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/computer/FulgoraUtil.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/computer/FulgoraVertexMemory.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/computer/VertexMemoryHandler.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/computer/VertexProgramScanJob.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/computer/VertexState.java
Labels: cla: external

#2073 Update testcontainers and junit 5
  janusgraph-all/pom.xml
  janusgraph-cql/src/test/java/org/janusgraph/JanusGraphCassandraContainer.java
  janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLStoreTest.java
  janusgraph-dist/pom.xml
  janusgraph-driver/pom.xml
  janusgraph-hbase-parent/janusgraph-hbase-10/pom.xml
  janusgraph-hbase-parent/janusgraph-hbase-core/pom.xml
  pom.xml
Labels: cla: yes

#2066 Index repair improvements
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/Backend.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/scan/StandardScannerExecutor.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/IndexSerializer.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/job/IndexRepairJob.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/job/IndexUpdateJob.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/database/IndexSerializerTest.java
Labels: cla: external

#2061 Add support for graph binary
  docs/changelog.md
  docs/connecting/java.md
  janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-berkeleyje-es.yaml
  janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-berkeleyje.yaml
  janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-configuration.yaml
  janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-cql-es.yaml
  janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server.yaml
  janusgraph-dist/src/assembly/static/conf/remote-graph-binary.yaml
  janusgraph-driver/src/main/java/org/janusgraph/core/attribute/Geo.java
  janusgraph-driver/src/main/java/org/janusgraph/core/attribute/Text.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphIoRegistry.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphPSerializer.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/JanusGraphP.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/GeoshapeGraphBinarySerializer.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/GraphBinaryType.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/JanusGraphPBinarySerializer.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/JanusGraphTypeSerializer.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/RelationIdentifierGraphBinarySerializer.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/graphson/JanusGraphSONModule.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/graphson/JanusGraphSONModuleV2d0.java
  janusgraph-driver/src/test/java/org/janusgraph/graphdb/tinkerpop/JanusGraphSerializerBaseIT.java
  janusgraph-driver/src/test/java/org/janusgraph/graphdb/tinkerpop/io/binary/GeoshapeGraphBinarySerializerTest.java
  janusgraph-driver/src/test/java/org/janusgraph/graphdb/tinkerpop/io/binary/JanusGraphPGraphBinarySerializerTest.java
  janusgraph-driver/src/test/java/org/janusgraph/graphdb/tinkerpop/io/binary/RelationIdentifierGraphBinarySerializerTest.java
Labels: area/tinkerpop, cla: yes

#2043 Disable smart limit adjustment for count query
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/GraphCentricQueryBuilder.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphStep.java
Labels: cla: external

#2085 Add janusgraph-dev Gitter room to README [doc only]
  README.md
Labels: cla: yes

#2078 avoid expensive regular regexp operations while getting name of Janus…
  janusgraph-core/src/main/java/org/janusgraph/graphdb/types/vertices/JanusGraphSchemaVertex.java
Labels: cla: external

#2082 Track End-of-Life versions
  docs/changelog.md
Labels: cla: external

#2080 Remove redundant data structure in CQL adapter
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java
Labels: cla: external

#1937 Explain usage of implicit keys for vertex-centric indexes
  docs/index-management/index-performance.md
Labels: cla: external

#2081 Add missing `:remote console` to remote example in docs
  docs/basics/server.md
Labels: cla: external

#2090 Disable CQL metrics when JanusGraph configuration states `metrics.enabled=false`
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java
Labels: cla: external

#2095 Drop support for Cassandra 2 [full build]
  .travis.yml
  docs/basics/janusgraph-cfg.md
  docs/changelog.md
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java
  janusgraph-cql/src/test/java/org/janusgraph/JanusGraphCassandraContainer.java
  janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLStoreTest.java
  janusgraph-cql/src/test/resources/cassandra2-byteordered.yaml
  janusgraph-cql/src/test/resources/cassandra2-murmur-ssl.yaml
  janusgraph-cql/src/test/resources/cassandra2-murmur.yaml
  janusgraph-dist/README.md
  janusgraph-dist/src/assembly/descriptor/common-full.component.xml
  janusgraph-dist/src/assembly/static/cassandra/bin/cassandra
  janusgraph-dist/src/assembly/static/cassandra/conf/cassandra-env.sh
  janusgraph-dist/src/assembly/static/cassandra/conf/cassandra.yaml
  janusgraph-dist/src/assembly/static/cassandra/conf/jvm.options
  janusgraph-dist/src/assembly/static/cassandra/conf/logback.xml
  pom.xml
Labels: cla: yes

#2088 Fix global config overriding
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/builder/ReadConfigurationBuilder.java
  janusgraph-test/src/test/java/org/janusgraph/diskstorage/configuration/builder/ReadConfigurationBuilderTest.java
Labels: cla: external

#2084 EntryArrayList instead of StaticArrayEntryList
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/SliceQuery.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/scan/StandardScannerExecutor.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/EntryArrayList.java
Labels: cla: external

#1976 Improve OLAP queries for BerkeleyDB
  docs/basics/janusgraph-cfg.md
  janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJEKeyValueStore.java
  janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJEStoreManager.java
  janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJETx.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/scan/StandardScannerExecutor.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/log/kcvs/KCVSLog.java
Labels: cla: external
