Repository JanusGraph/janusgraph, pull requests merged in 2021-04, with the labels that each got.

#2548 Add GetEdgeLabelByName
  janusgraph-grpc/README.md
  janusgraph-grpc/src/main/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerClient.java
  janusgraph-grpc/src/main/proto/janusgraph/schema/v1/schema_manager.proto
  janusgraph-grpc/src/main/proto/janusgraph/types/v1/schema_types.proto
  janusgraph-server/src/main/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerImpl.java
  janusgraph-server/src/main/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerProvider.java
  janusgraph-server/src/main/java/org/janusgraph/graphdb/grpc/schema/util/GrpcUtils.java
  janusgraph-server/src/test/java/org/janusgraph/graphdb/grpc/JanusGraphGrpcServerBaseTest.java
  janusgraph-server/src/test/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerClientTest.java
Labels: area/schema, cla: external

#2551 Fix profiling when limit adjusting is enabled
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/KeySliceQuery.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/SliceQuery.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/LimitAdjustingIterator.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/QueryProcessor.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/JointIndexQuery.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/MultiKeySliceQuery.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/query/QueryTest.java
Labels: cla: external

#2564 Add an option to set CQL speculative retry policy
  docs/configs/janusgraph-cfg.md
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java
  janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLStoreTest.java
Labels: cla: external

#2556 Add CQL METADATA_SCHEMA_ENABLED & METADATA_TOKEN_MAP_ENABLED options
  docs/configs/janusgraph-cfg.md
  janusgraph-cql/pom.xml
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java
  janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLConfigTest.java
  janusgraph-cql/src/test/java/org/janusgraph/graphdb/cql/CQLGraphTest.java
Labels: cla: external, storage/cassandra

#2568 CQLKeyColumnValueStore: Avoid fetching WRITETIME and/or TTL if no need
  docs/configs/janusgraph-cfg.md
  janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java
Labels: cla: external, kind/enhancement, storage/cassandra

#2552 Make hard max limit configurable and use Integer.MAX_VALUE by default
  docs/changelog.md
  docs/configs/janusgraph-cfg.md
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/QueryUtil.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/GraphCentricQueryBuilder.java
  janusgraph-test/pom.xml
  janusgraph-test/src/test/java/org/janusgraph/graphdb/query/GraphCentricQueryBenchmark.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/query/QueryUtilTest.java
  pom.xml
Labels: area/core, cla: external, kind/performance

#2578 Fixes sparkDriver port binding issue
  janusgraph-cql/src/test/resources/cql-read.properties
Labels: cla: external

#2569 Enable serial tests for cassandra
  janusgraph-cql/pom.xml
  pom.xml
Labels: area/testing, cla: external

#2562 Fix sorting TEXTSTRING mapped fields in ES
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticsearchIndexTest.java
Labels: cla: external

#2583 Always use the most recent _scroll_id
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchScroll.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticSearchScrollTest.java
Labels: cla: external

#2559 Add negations to all text predicates
  docs/changelog.md
  docs/index-backend/text-search.md
  docs/interactions/search-predicates.md
  janusgraph-backend-testutils/src/main/java/org/janusgraph/core/attribute/TextArgument.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java
  janusgraph-driver/src/main/java/org/janusgraph/core/attribute/Text.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/compat/AbstractESCompat.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticsearchIndexTest.java
  janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java
  janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java
  janusgraph-test/src/test/java/org/janusgraph/core/attribute/GeoshapeTest.java
  janusgraph-test/src/test/java/org/janusgraph/core/attribute/TextTest.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/attribute/TextTest.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/predicate/ConnectiveJanusPredicateTest.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/query/QueryTest.java
Labels: cla: external

#2557 Refactor GhostVertexRemover and VertexJobConverter
  janusgraph-core/src/main/java/org/janusgraph/core/TransactionBuilder.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/AbstractScanJob.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/GraphProvider.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/VertexJobConverter.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/computer/PartitionedVertexProgramExecutor.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/job/GhostVertexRemover.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/job/IndexRemoveJob.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardTransactionBuilder.java
Labels: area/core, cla: external, kind/cleanup
