Repository JanusGraph/janusgraph, pull requests merged in 2021-12, with the labels that each got.

#2872 Change CQL request-timeout default value to 12s
  docs/configs/janusgraph-cfg.md
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java
Labels: cla: external

#2812 CQL default request-timeout should be JanusGraph default
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/builder/CQLProgrammaticConfigurationLoaderBuilder.java
  janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLConfigTest.java
Labels: cla: external

#2845 Use JanusGraphManager by default
  docs/changelog.md
  janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-berkeleyje-es.yaml
  janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-berkeleyje.yaml
  janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-cql-es.yaml
  janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-cql.yaml
  janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server.yaml
  janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/AbstractGremlinServerIntegrationTest.java
  janusgraph-server/src/test/resources/janusgraph-server-integration.yaml
Labels: cla: external

#2860 Add config printer to janusgraph-server.sh
  janusgraph-dist/src/assembly/static/bin/janusgraph-server.sh
  janusgraph-dist/src/assembly/static/conf/jvm-11.options
  janusgraph-dist/src/assembly/static/conf/jvm-8.options
  janusgraph-dist/src/test/expect/janusgraph-server-sh.after.expect.vm
  janusgraph-dist/src/test/expect/janusgraph-server-sh.before.expect.vm
  janusgraph-dist/src/test/java/org/janusgraph/pkgtest/JanusGraphAssemblyBaseIT.java
Labels: cla: external

#2884 Add Astra to Cassandra Backends docs page (#2879)
  docs/storage-backend/cassandra.md
Labels: cla: external

#2892 Add CVE-2021-44228 mitigation for ES
  janusgraph-dist/src/assembly/static/elasticsearch/config/jvm.options
Labels: cla: external

#2896 Refactor JanusGraphManagement.IndexJobFuture
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/core/schema/JanusGraphManagement.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/Backend.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/scan/CompletedJobFuture.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/scan/EmptyScanJobFuture.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/scan/FailedJobFuture.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/scan/ScanJobFuture.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/scan/StandardScanner.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/scan/StandardScannerExecutor.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java
  janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/MapReduceIndexManagement.java
  janusgraph-test/src/test/java/org/janusgraph/diskstorage/keycolumnvalue/scan/CompletedJobFutureTest.java
  janusgraph-test/src/test/java/org/janusgraph/diskstorage/keycolumnvalue/scan/EmptyScanJobFutureTest.java
  janusgraph-test/src/test/java/org/janusgraph/diskstorage/keycolumnvalue/scan/FailedJobFutureTest.java
Labels: kind/cleanup, area/core, cla: external

#2895 Add distribution test for SparkGraphComputer traversal
  janusgraph-dist/src/test/expect/spark-graph-computer.expect.vm
  janusgraph-dist/src/test/java/org/janusgraph/pkgtest/AbstractJanusGraphAssemblyIT.java
  janusgraph-dist/src/test/java/org/janusgraph/pkgtest/BerkeleyAssemblyIT.java
  janusgraph-dist/src/test/java/org/janusgraph/pkgtest/BerkeleyESAssemblyIT.java
  janusgraph-dist/src/test/java/org/janusgraph/pkgtest/CqlAssemblyIT.java
  janusgraph-dist/src/test/java/org/janusgraph/pkgtest/CqlESAssemblyIT.java
  janusgraph-dist/src/test/java/org/janusgraph/pkgtest/InMemoryAssemblyIT.java
  janusgraph-dist/src/test/java/org/janusgraph/pkgtest/JanusGraphAssemblyBaseIT.java
Labels: cla: external

#2901 Add concurrency level config in ManagementSystem::updateIndex
  docs/schema/index-management/index-reindexing.md
  docs/schema/index-management/index-removal.md
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-benchmark/src/main/java/org/janusgraph/MgmtOlapJobBenchmark.java
  janusgraph-benchmark/src/main/resources/log4j.properties
  janusgraph-core/src/main/java/org/janusgraph/core/schema/JanusGraphManagement.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java
Labels: kind/enhancement, kind/performance, area/core, cla: external

#2888 Unix style directory path usage in tests makes build fail on Windows #2887
  janusgraph-test/src/test/java/org/janusgraph/diskstorage/common/LocalStoreManagerTest.java
Labels: cla: external
