Repository JanusGraph/janusgraph, pull requests merged in 2021-06, with the labels that each got.

#2633 Cleanup JanusGraphSettings
  janusgraph-server/src/main/java/org/janusgraph/graphdb/server/JanusGraphServer.java
  janusgraph-server/src/main/java/org/janusgraph/graphdb/server/JanusGraphSettings.java
  janusgraph-server/src/main/java/org/janusgraph/graphdb/server/util/JanusGraphSettingsUtils.java
  janusgraph-server/src/test/java/org/janusgraph/graphdb/server/JanusGraphServerTest.java
  janusgraph-server/src/test/java/org/janusgraph/graphdb/server/JanusGraphSettingsTest.java
  janusgraph-server/src/test/java/org/janusgraph/graphdb/server/util/JanusGraphSettingsUtilsTest.java
Labels: cla: external

#2637 Update spatial4j to version 0.8
  pom.xml
Labels: cla: external

#2638 Add test for HadoopGraph loading comma delimited values
  janusgraph-core/src/main/java/org/janusgraph/util/system/ConfigurationUtil.java
  janusgraph-cql/src/test/java/org/janusgraph/hadoop/CQLInputFormatIT.java
  janusgraph-cql/src/test/resources/cql-read-multi-hosts.properties
  janusgraph-hbase/src/test/java/org/janusgraph/hadoop/HBaseInputFormatIT.java
  janusgraph-hbase/src/test/java/org/janusgraph/hadoop/HBaseSnapshotInputFormatIT.java
Labels: area/testing, cla: external

#2640 Break vertices selection loop for properties prefetching when cache size is reached
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphVertexStep.java
Labels: cla: external

#2618 Add ASSIGN_TIMESTAMP option to allow disabling custom timestamp
  docs/configs/janusgraph-cfg.md
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/common/AbstractStoreManager.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java
  janusgraph-cql/src/test/java/org/janusgraph/graphdb/cql/CQLGraphTest.java
  janusgraph-hbase/src/main/java/org/janusgraph/diskstorage/hbase/HBaseStoreManager.java
  janusgraph-hbase/src/test/java/org/janusgraph/diskstorage/hbase/HBaseStoreManagerMutationTest.java
  janusgraph-hbase/src/test/java/org/janusgraph/graphdb/hbase/HBaseGraphTest.java
Labels: cla: external

#2643 Fix inconsistent state of edge
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/vertices/StandardVertexTest.java
Labels: cla: external

#2649 Use all hosts available in CqlBinaryInputFormat config
  janusgraph-cql/src/main/java/org/janusgraph/hadoop/formats/cql/CqlBinaryInputFormat.java
Labels: cla: external

#2656 MapReduceIndexManagement: Accept optional custom hadoop config
  janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/MapReduceIndexManagement.java
  janusgraph-hadoop/src/test/java/org/janusgraph/hadoop/AbstractIndexManagementIT.java
  janusgraph-hadoop/src/test/java/org/janusgraph/hadoop/MapReduceRemoveIndexApp.java
Labels: cla: external

#2644 Add experimental support for Amazon Managed KeySpace
  docs/changelog.md
  docs/storage-backend/cassandra.md
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/common/AbstractStoreManager.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java
Labels: cla: external

#2659 Update solr to 8.6.3
  docs/changelog.md
  janusgraph-solr/pom.xml
  pom.xml
Labels: cla: external

#2660 Optimize getHasContainers usage
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/HasStepFolder.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphStep.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/AdjacentVertexFilterOptimizerStrategy.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/AdjacentVertexHasIdOptimizerStrategy.java
Labels: cla: external

#2663 [Docs] Explain data type inference in auto schema maker
  docs/schema/index.md
Labels: area/docs, cla: external

#2516 Add config option to use barrier size as batch size limit
  docs/configs/janusgraph-cfg.md
  docs/operations/batch-processing.md
  janusgraph-backend-testutils/src/main/java/org/janusgraph/blueprints/AbstractJanusGraphProvider.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/blueprints/JanusGraphTestListener.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/StandardJanusGraph.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphTraversalUtil.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphMultiQueryStep.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphPropertiesStep.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphVertexStep.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/MultiQueriable.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/JanusGraphLocalQueryOptimizerStrategy.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/JanusGraphMultiQueryStrategy.java
  janusgraph-inmemory/src/test/java/org/janusgraph/blueprints/inmemory/InMemoryMultiQueryGraphProvider.java
  janusgraph-inmemory/src/test/java/org/janusgraph/graphdb/inmemory/InMemoryGraphTest.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphLocalQueryOptimizerStrategyTest.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphMultiQueryStepTest.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphMultiQueryStrategyTest.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphStepStrategyTest.java
  mkdocs.yml
Labels: cla: external

#2662 Add tests and doc for property name change feature
  docs/schema/index.md
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/IndexSerializer.java
Labels: cla: external

#2666 Bump DataStax Cassandra Driver to 4.12.0
  docs/changelog.md
  pom.xml
Labels: cla: external

#2668 Bump Elasticsearch to 7.13.2
  docs/changelog.md
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/JanusGraphElasticsearchContainer.java
  pom.xml
Labels: cla: external

#2665 Do not trigger iteration on small cache in JanusGraphEdgeVertexStep initialization
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/testutil/JanusGraphAssert.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphEdgeVertexStep.java
Labels: cla: external

#2664 Optimize hasContainers addition by ensuring correct size
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/HasStepFolder.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphPropertiesStep.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphStep.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphVertexStep.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphStepStrategyTest.java
Labels: cla: external

#2670 JanusGraph release v0.6.0 [cql-tests] [tp-tests]
  RELEASING.md
  docs/changelog.md
  janusgraph-all/pom.xml
  janusgraph-backend-testutils/pom.xml
  janusgraph-berkeleyje/pom.xml
  janusgraph-bigtable/pom.xml
  janusgraph-core/pom.xml
  janusgraph-cql/pom.xml
  janusgraph-dist/pom.xml
  janusgraph-doc/pom.xml
  janusgraph-driver/pom.xml
  janusgraph-es/pom.xml
  janusgraph-examples/example-berkeleyje/pom.xml
  janusgraph-examples/example-common/pom.xml
  janusgraph-examples/example-cql/pom.xml
  janusgraph-examples/example-hbase/pom.xml
  janusgraph-examples/example-remotegraph/pom.xml
  janusgraph-examples/example-tinkergraph/pom.xml
  janusgraph-examples/pom.xml
  janusgraph-grpc/pom.xml
  janusgraph-hadoop/pom.xml
  janusgraph-hbase/pom.xml
  janusgraph-inmemory/pom.xml
  janusgraph-lucene/pom.xml
  janusgraph-server/pom.xml
  janusgraph-solr/pom.xml
  janusgraph-test/pom.xml
  pom.xml
Labels: cla: external

#2684 Reduce redundant global centric query build
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/GraphCentricQueryBuilder.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/index/AbstractIndexSelectionStrategy.java
Labels: cla: external
