Repository JanusGraph/janusgraph, pull requests merged in 2021-02, with the labels that each got.

#2409 Add missing test dependency on janusgraph-inmemory
  janusgraph-server/pom.xml
Labels: cla: external

#2432 Bump cassandra
  TESTING.md
  docs/changelog.md
  janusgraph-cql/pom.xml
  janusgraph-cql/src/test/java/org/janusgraph/JanusGraphCassandraContainer.java
  janusgraph-cql/src/test/resources/docker/docker-compose.yml
  pom.xml
Labels: cla: external, dependencies, storage/cassandra

#2414 Avoid duplicate jars in classpath
  janusgraph-dist/src/assembly/static/bin/janusgraph-server.sh
Labels: cla: external

#2237 Issue 2236: Remove graph and traversal source from script engine bind…
  janusgraph-core/src/main/java/org/janusgraph/core/ConfiguredGraphFactory.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/management/JanusGraphManager.java
  janusgraph-test/src/test/java/org/janusgraph/core/ConfiguredGraphFactoryTest.java
Labels: cla: yes

#2437 [Doc] Remove mention of Astyanax in data consistency chapter
  docs/advanced-topics/eventual-consistency.md
Labels: cla: external

#2439 [Docs] Enhance indexing documentation
  docs/schema/index-management/index-performance.md
Labels: cla: external

#2148 Fix #2147: graph is created again during the drop process
  .github/workflows/ci-backend-cql.yml
  janusgraph-backend-testutils/pom.xml
  janusgraph-backend-testutils/src/main/java/org/janusgraph/core/AbstractConfiguredGraphFactoryTest.java
  janusgraph-core/src/main/java/org/janusgraph/core/ConfiguredGraphFactory.java
  janusgraph-core/src/main/java/org/janusgraph/core/JanusGraphFactory.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java
  janusgraph-cql/src/test/java/org/janusgraph/JanusGraphCassandraContainer.java
  janusgraph-cql/src/test/java/org/janusgraph/core/cql/CQLConfiguredGraphFactoryTest.java
  janusgraph-inmemory/src/test/java/org/janusgraph/core/inmemory/InmemoryConfiguredGraphFactoryTest.java
  janusgraph-test/pom.xml
  janusgraph-test/src/test/resources/log4j.properties
Labels: cla: external

#2446 Issue 2445: Expose ES rest client connect and socket timeout config options
  docs/configs/janusgraph-cfg.md
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestClientSetup.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestElasticSearchClient.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/rest/RestClientSetupTest.java
Labels: cla: yes

#2430 Make DateSerializer thread-safe
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/serialize/attribute/DateSerializer.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/database/serialize/attribute/DateSerializerTest.java
Labels: cla: external

#2413 Release memory when releasing transaction
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/addedrelations/AddedRelationsContainer.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/addedrelations/SimpleAddedRelations.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/indexcache/ConcurrentIndexCache.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/indexcache/IndexCache.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/indexcache/SimpleIndexCache.java
Labels: cla: external

#2435 Fix memory utilization for long query
  janusgraph-core/src/main/java/org/janusgraph/graphdb/util/MultiDistinctOrderedIterator.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/util/MultiDistinctUnorderedIterator.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/util/MultiDistinctUnorderedIteratorTest.java
Labels: cla: external

#2460 Test Improvement: grouping individual assertions
  janusgraph-backend-testutils/src/main/java/org/janusgraph/diskstorage/configuration/WritableConfigurationTest.java
Labels: cla: external

#2467 Fix CI build failure by specifying javax.el version
  janusgraph-hbase-parent/janusgraph-hbase-server/pom.xml
Labels: cla: external

#2457 Avoid explicit memory clean up when releasing transaction
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java
Labels: cla: external

#1850 Add metric to index provider
  docs/operations/monitoring.md
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/IndexMetricTest.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/Backend.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/MetricInstrumentedIndexProvider.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/StorageRunnable.java
  janusgraph-lucene/src/test/java/org/janusgraph/graphdb/BerkeleyLuceneIndexMetricTest.java
Labels: cla: external

#2469 Fix codecov configs
  .codecov.yml
  .github/workflows/ci-backend-cql.yml
  .github/workflows/ci-backend-hbase.yml
  .github/workflows/ci-core.yml
  .github/workflows/ci-index-es.yml
  .github/workflows/ci-index-solr.yml
Labels: cla: external

#2475 Fix precondition checks
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/common/LocalStoreManager.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/keyvalue/KeySelector.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/validator/CompatibilityValidator.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/IndexSerializer.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/idassigner/placement/PartitionIDRange.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/serialize/attribute/IntegerSerializer.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/serialize/attribute/ShortSerializer.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/internal/ElementLifeCycle.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/management/ConfigurationManagementGraph.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/condition/ConditionUtil.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/BaseVertexCentricQueryBuilder.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/BasicVertexCentricQueryBuilder.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/types/StandardRelationTypeMaker.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/types/TypeDefinitionMap.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/util/IndexHelper.java
  janusgraph-driver/src/main/java/org/janusgraph/util/encoding/LongEncoding.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestClientSetup.java
  janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java
  janusgraph-server/src/main/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/auth/HMACAuthenticator.java
  janusgraph-server/src/main/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/auth/JanusGraphAbstractAuthenticator.java
  janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java
Labels: cla: external

#2410 Fix nested AND/OR profiler group issue
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/BackendQueryHolder.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/GraphCentricQuery.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/JointIndexQuery.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/profile/ProfileObservable.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/profile/QueryProfiler.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/profile/SimpleQueryProfiler.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/BaseVertexCentricQuery.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/profile/TP3ProfileWrapper.java
  janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/SolrJanusGraphIndexTest.java
Labels: cla: external

#2488 Add error message to Preconditions checks
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/BackendTransaction.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/AbstractConfiguration.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/TransactionalConfiguration.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/EdgeSerializer.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementLogger.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/internal/ElementCategory.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/GraphCentricQueryBuilder.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/schema/SchemaElementDefinition.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/vertices/StandardVertex.java
  janusgraph-core/src/main/java/org/janusgraph/util/datastructures/ArraysUtil.java
  janusgraph-core/src/main/java/org/janusgraph/util/stats/NumberUtil.java
Labels: cla: external

#2436 Utilize data model layout when getting edge by id
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphPerformanceMemoryTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/EdgeSerializer.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/relations/RelationIdentifierUtils.java
Labels: cla: external
