Repository JanusGraph/janusgraph, pull requests merged in 2021-03, with the labels that each got.

#2448 Add awesome badge
  README.md
Labels: cla: external

#2489 Fix JanusGraphManagement::printIndexes output
  janusgraph-core/src/main/java/org/janusgraph/core/schema/JanusGraphManagement.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java
  janusgraph-lucene/src/test/java/org/janusgraph/diskstorage/lucene/BerkeleyLuceneTest.java
Labels: cla: external

#2493 Add Management API to retrieve indexOnly constraint
  docs/schema/index-management/index-performance.md
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/core/schema/JanusGraphManagement.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java
Labels: cla: external

#2458 Add client and check basic roundtrip between client and server
  .github/workflows/lint-proto.yml
  janusgraph-all/pom.xml
  janusgraph-driver/pom.xml
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/grpc/JanusGraphManagerClient.java
  janusgraph-grpc/buf.yaml
  janusgraph-grpc/pom.xml
  janusgraph-grpc/src/main/proto/janusgraph/v1/graph_manager.proto
  janusgraph-server/pom.xml
  janusgraph-server/src/main/java/org/janusgraph/graphdb/grpc/JanusGraphManagerServiceImpl.java
  janusgraph-server/src/main/java/org/janusgraph/graphdb/server/JanusGraphServer.java
  janusgraph-server/src/main/proto/graph-manager.proto
  janusgraph-server/src/test/java/org/janusgraph/graphdb/grpc/JanusGraphGrpcServerBaseTest.java
  janusgraph-server/src/test/java/org/janusgraph/graphdb/grpc/JanusGraphManagerClientTest.java
  janusgraph-server/src/test/java/org/janusgraph/graphdb/grpc/JanusGraphManagerImplTest.java
  janusgraph-server/src/test/java/org/janusgraph/graphdb/server/JanusGraphManagerImplTest.java
  pom.xml
Labels: area/server, cla: external, kind/enhancement

#2503 Fix race condition of UniqueInstanceIdRetriever
  janusgraph-core/src/main/java/org/janusgraph/graphdb/idmanagement/UniqueInstanceIdRetriever.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/idmanagement/UniqueInstanceIdRetrieverConcurrencyTest.java
Labels: cla: external

#2518 [Docs] Improve doc for Elasticsearch authentication
  docs/configs/janusgraph-cfg.md
  docs/index-backend/elasticsearch.md
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java
Labels: cla: external

#2501 BasicVertexCentricQueryBuilder: Reduce duplicate getExtendedSortKey calls
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/BasicVertexCentricQueryBuilder.java
Labels: cla: external

#2472 Fix potential ThreadLocal transaction leak [tp-tests]
  docs/changelog.md
  janusgraph-core/src/main/java/org/janusgraph/core/JanusGraph.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphBlueprintsGraph.java
  janusgraph-test/src/test/java/org/janusgraph/core/ThreadLocalTxLeakTest.java
  janusgraph-test/src/test/java/org/janusgraph/core/TransactionTest.java
Labels: cla: external

#2523 Add job to run all TinkerPop tests on schedule
  .github/workflows/ci-release.yml
Labels: cla: external

#2137 Graph Reindexing Issue Fix
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/job/IndexRepairJob.java
Labels: cla: external

#2502 Add CacheVertex::refresh method to allow clearing vertex cache
  docs/operations/cache.md
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/vertices/CacheVertex.java
Labels: cla: external

#2520 Disable smart-limit by default
  docs/changelog.md
  docs/configs/janusgraph-cfg.md
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java
Labels: cla: external, kind/performance

#2529 Upgrade DataStax cassandra driver to 4.11.0
  docs/changelog.md
  janusgraph-cql/pom.xml
  pom.xml
Labels: cla: external

#2530 Update ElasticSearch to 7.12.0
  docs/changelog.md
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/JanusGraphElasticsearchContainer.java
  pom.xml
Labels: cla: external

#2492 Reduce configuration options for CFG
  docs/changelog.md
  docs/operations/configured-graph-factory.md
  docs/operations/dynamic-graphs.md
  janusgraph-core/src/main/java/org/janusgraph/graphdb/management/ConfigurationManagementGraph.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/management/JanusGraphManager.java
  janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-configuration.yaml
  janusgraph-server/src/main/java/org/janusgraph/channelizers/JanusGraphChannelizer.java
  janusgraph-server/src/main/java/org/janusgraph/channelizers/JanusGraphHttpChannelizer.java
  janusgraph-server/src/main/java/org/janusgraph/channelizers/JanusGraphNioChannelizer.java
  janusgraph-server/src/main/java/org/janusgraph/channelizers/JanusGraphWebSocketChannelizer.java
  janusgraph-server/src/main/java/org/janusgraph/channelizers/JanusGraphWsAndHttpChannelizer.java
  janusgraph-server/src/main/java/org/janusgraph/graphdb/server/JanusGraphServer.java
  janusgraph-server/src/main/java/org/janusgraph/graphdb/server/util/GremlinSettingsUtils.java
  janusgraph-server/src/test/java/org/janusgraph/graphdb/server/util/GremlinSettingsUtilsTest.java
  janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/AbstractGremlinServerIntegrationTest.java
  janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/ConfigurationManagementGraphServerTest.java
  janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/JanusGraphChannelizerTest.java
  janusgraph-server/src/test/resources/gremlin-server-integration.yaml
Labels: area/server, cla: external, kind/enhancement

#2528 Add exec to start server
  janusgraph-dist/src/assembly/static/bin/janusgraph-server.sh
Labels: cla: external

#2531 Rewrite vertex-centric reindexing test
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/job/IndexRepairJob.java
Labels: cla: external

#2534 Ignore tests in codecov report and upload jacoco artefacts
  .codecov.yml
  .github/workflows/ci-backend-cql.yml
  .github/workflows/ci-backend-hbase.yml
  .github/workflows/ci-core.yml
  .github/workflows/ci-index-es.yml
  .github/workflows/ci-index-solr.yml
Labels: cla: external

#2535 VertexIDAssigner: close partitionVertexIdPool in close method
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/idassigner/VertexIDAssigner.java
Labels: cla: external

#2532 Remove unused java classes to improve test coverage
  janusgraph-core/src/main/java/org/janusgraph/core/util/JanusGraphCleanup.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/ConsistencyLevel.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/ReadOnlyKeyColumnValueStore.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/indexing/StandardIndexInformation.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/serialize/NoSerializer.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/condition/IncidenceDirectionCondition.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/vertexcache/LRUVertexCache.java
  janusgraph-core/src/main/java/org/janusgraph/util/datastructures/CompactMap.java
  janusgraph-core/src/main/java/org/janusgraph/util/datastructures/Factory.java
  janusgraph-core/src/main/java/org/janusgraph/util/datastructures/IntHashSet.java
  janusgraph-core/src/main/java/org/janusgraph/util/datastructures/IntSet.java
  janusgraph-core/src/main/java/org/janusgraph/util/datastructures/LongCounter.java
  janusgraph-core/src/main/java/org/janusgraph/util/datastructures/Maps.java
  janusgraph-core/src/main/java/org/janusgraph/util/stats/IntegerDoubleFrequency.java
  janusgraph-core/src/main/java/org/janusgraph/util/stats/ObjectAccumulator.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/idmanagement/IDPoolTest.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/util/ArraysUtil.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/util/IntHashSet.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/util/IntSet.java
Labels: cla: external, kind/cleanup

#2527 Add Service for schema management
  janusgraph-driver/pom.xml
  janusgraph-grpc/src/main/java/org/janusgraph/graphdb/grpc/JanusGraphManagerClient.java
  janusgraph-grpc/src/main/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerClient.java
  janusgraph-grpc/src/main/proto/janusgraph/schema/v1/schema_manager.proto
  janusgraph-grpc/src/main/proto/janusgraph/types/v1/graph_types.proto
  janusgraph-grpc/src/main/proto/janusgraph/types/v1/schema_types.proto
  janusgraph-grpc/src/main/proto/janusgraph/v1/graph_manager.proto
  janusgraph-server/src/main/java/org/janusgraph/graphdb/grpc/JanusGraphContextHandler.java
  janusgraph-server/src/main/java/org/janusgraph/graphdb/grpc/JanusGraphManagerServiceImpl.java
  janusgraph-server/src/main/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerImpl.java
  janusgraph-server/src/main/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerProvider.java
  janusgraph-server/src/main/java/org/janusgraph/graphdb/server/JanusGraphServer.java
  janusgraph-server/src/test/java/org/janusgraph/graphdb/grpc/JanusGraphGrpcServerBaseTest.java
  janusgraph-server/src/test/java/org/janusgraph/graphdb/grpc/JanusGraphManagerClientTest.java
  janusgraph-server/src/test/java/org/janusgraph/graphdb/grpc/JanusGraphManagerImplTest.java
  janusgraph-server/src/test/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerClientTest.java
Labels: area/schema, cla: external, kind/enhancement

#2533 Deprecated org.janusgraph.graphdb.schema
  janusgraph-core/src/main/java/org/janusgraph/graphdb/schema/EdgeLabelDefinition.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/schema/PropertyKeyDefinition.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/schema/RelationTypeDefinition.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/schema/SchemaContainer.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/schema/SchemaElementDefinition.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/schema/SchemaProvider.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/schema/VertexLabelDefinition.java
Labels: cla: external, kind/cleanup

#2536 Fix integer overflow bug in StaticArrayEntryList
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/ArrayUtil.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/StaticArrayEntryList.java
  janusgraph-test/src/test/java/org/janusgraph/diskstorage/util/ArrayUtilTest.java
Labels: cla: external
