Repository JanusGraph/janusgraph, pull requests merged in 2021-05, with the labels that each got.

#2560 Add support for query multiple edges and vertices
  .editorconfig
  janusgraph-grpc/README.md
  janusgraph-grpc/src/main/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerClient.java
  janusgraph-grpc/src/main/proto/janusgraph/schema/v1/schema_manager.proto
  janusgraph-grpc/src/main/proto/janusgraph/types/v1/graph_types.proto
  janusgraph-grpc/src/main/proto/janusgraph/types/v1/schema_types.proto
  janusgraph-server/src/main/java/org/janusgraph/graphdb/grpc/JanusGraphManagerServiceImpl.java
  janusgraph-server/src/main/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerImpl.java
  janusgraph-server/src/main/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerProvider.java
  janusgraph-server/src/test/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerClientTest.java
  janusgraph-server/src/test/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerImplTest.java
Labels: area/core, area/schema, cla: external

#2589 Add checkstyle support
  .editorconfig
  janusgraph-backend-testutils/src/main/java/org/janusgraph/TestByteBuffer.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphPartitionGraphTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/testutil/FeatureFlag.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/testutil/FeatureRequirementCondition.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/testutil/RandomGenerator.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/BackendTransaction.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/locking/AbstractLocker.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/log/kcvs/KCVSLog.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/Hex.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/StaticArrayEntry.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/idmanagement/UniqueInstanceIdRetriever.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/internal/ElementLifeCycle.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/internal/OrderList.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/VertexJobConverter.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/computer/FulgoraUtil.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/computer/VertexProgramScanJob.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/job/IndexRemoveJob.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/GraphCentricQueryBuilder.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/relations/RelationIdentifierUtils.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/plugin/JanusGraphGremlinPlugin.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/types/system/SystemTypeManager.java
  janusgraph-core/src/main/java/org/janusgraph/util/system/IOUtils.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLColValGetter.java
  janusgraph-cql/src/main/java/org/janusgraph/hadoop/formats/cql/CqlBinaryRecordReader.java
  janusgraph-dist/src/assembly/descriptor/common-full.component.xml
  janusgraph-dist/src/assembly/descriptor/common.component.xml
  janusgraph-dist/src/test/resources/log4j.properties
  janusgraph-driver/src/main/java/org/janusgraph/core/attribute/Text.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/plugin/JanusGraphGremlinDriverPlugin.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/util/ConnectionKeepAliveConfigCallback.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/rest/RestClientSetupTest.java
  janusgraph-hbase/src/main/java/org/janusgraph/diskstorage/hbase/HBaseCompatLoader.java
  janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneCustomAnalyzer.java
  janusgraph-lucene/src/test/java/org/janusgraph/diskstorage/lucene/LuceneExample.java
  janusgraph-server/src/main/java/org/janusgraph/graphdb/grpc/JanusGraphManagerServiceImpl.java
  janusgraph-server/src/main/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/auth/JanusGraphAbstractAuthenticator.java
  janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/auth/MockedSaslAndHmacAuthenticatorFactory.java
  pom.xml
Labels: cla: external

#2599 Fix profiler timing for fullscan
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java
Labels: cla: external, kind/bug/confirmed

#2593 Add exists clause to negated Text predicates
  janusgraph-backend-testutils/src/main/java/org/janusgraph/core/attribute/TextArgument.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java
Labels: cla: external

#2602 Bump commons-beanutils from 1.8.3 to 1.9.4
  pom.xml
Labels: cla: external

#2597 [docs] Explain cache mechanism in more detail
  docs/operations/cache.md
Labels: cla: external

#2600 Manual cleanup
  janusgraph-backend-testutils/src/main/java/org/janusgraph/TestBed.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/blueprints/AbstractJanusGraphProvider.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/diskstorage/IDAuthorityTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphBaseTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphOperationCountingTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/testutil/TestGraphConfigs.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/Backend.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/scan/StandardScanner.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/BackendOperation.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/cache/StandardSchemaCache.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/idassigner/StandardIDPool.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/idmanagement/IDManager.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/QueryContainer.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/relations/AbstractTypedRelation.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphBlueprintsTransaction.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/types/TypeUtil.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/util/AllEdgesIterable.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/util/AllEdgesIterator.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/util/ConcurrentLRUCache.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/util/PriorityQueue.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/vertices/RemovableRelationIterable.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/vertices/RemovableRelationIterator.java
  janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/config/job/AbstractDistCacheConfigurer.java
  janusgraph-inmemory/src/main/java/org/janusgraph/diskstorage/inmemory/InMemoryStoreManager.java
  janusgraph-test/src/test/java/org/janusgraph/diskstorage/locking/LocalLockMediatorTest.java
Labels: cla: external, kind/cleanup

#2610 Iterator changes for atomic batch mutate to fix #2607
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java
  janusgraph-cql/src/test/java/org/janusgraph/graphdb/cql/CQLGraphTest.java
Labels: cla: yes

#2598 Refactor server.md for janusgraph-server.sh
  docs/getting-started/installation.md
  docs/operations/server.md
  janusgraph-dist/src/assembly/static/bin/janusgraph-server.sh
Labels: area/docs, cla: external

#2617 Remove duplicate addProperty calls in StandardJanusGraphTx:: makeSchemaVertex
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java
Labels: cla: external

#2632 changelog: Update tinkerpop compatibility matrix
  docs/changelog.md
Labels: cla: external
