Repository JanusGraph/janusgraph, pull requests merged in 2021-01, with the labels that each got.

#2264 Rewrite testConcurrentConsistencyEnforcement to properly test lock contention
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/locking/consistentkey/ConsistentKeyLocker.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/StandardJanusGraph.java
Labels: cla: external

#2195 Optimize performance of transaction-wise index query cache
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/testutil/JanusGraphAssert.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/profile/QueryProfiler.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/subquerycache/GuavaSubqueryCache.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/subquerycache/SubqueryCache.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/subquerycache/SubsetSubqueryCache.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/util/SubqueryIterator.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/query/QueryTest.java
Labels: cla: external

#2175 Add mixed index support for has(key) query
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/indexing/IndexFeatures.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/IndexSerializer.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/index/AbstractIndexSelectionStrategy.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/HasStepFolder.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/compat/AbstractESCompat.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/BerkeleyElasticsearchTest.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/CQLElasticsearchTest.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticsearchJanusGraphIndexTest.java
  janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java
  janusgraph-lucene/src/test/java/org/janusgraph/diskstorage/lucene/BerkeleyLuceneTest.java
  janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java
  janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/SolrJanusGraphIndexTest.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphStepStrategyTest.java
Labels: cla: external

#1903 Update Readme.md with new visualization tool [doc only]
  README.md
Labels: cla: external

#2189 Optimize adjacency checks with unique index
  docs/basics/janusgraph-cfg.md
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/StandardJanusGraph.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/GraphCentricQueryBuilder.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/index/IndexSelectionUtil.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/AdjacentVertexFilterOptimizerStrategy.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/AdjacentVertexHasIdOptimizerStrategy.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/AdjacentVertexHasUniquePropertyOptimizerStrategy.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/AdjacentVertexIsOptimizerStrategy.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/AdjacentVertexOptimizerStrategy.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/AdjacentVertexHasUniquePropertyOptimizerStrategyTest.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphLocalQueryOptimizerStrategyTest.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/OptimizerStrategyTest.java
Labels: cla: external

#2337 Bump Elasticsearch version to 7.10.1
  docs/changelog.md
  janusgraph-es/pom.xml
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/JanusGraphElasticsearchContainer.java
  pom.xml
Labels: cla: external

#2346 Allow passing a filter function to getMatchingIndexes
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/GraphCentricQueryBuilder.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/index/IndexSelectionUtil.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/AdjacentVertexHasUniquePropertyOptimizerStrategy.java
Labels: cla: external

#2349 Codecov should notify after 30 reports
  .codecov.yml
Labels: cla: external

#2294 issue #2273 - implement variable length "valuePosition" in page storage
  janusgraph-inmemory/src/main/java/org/janusgraph/diskstorage/inmemory/BufferPage.java
  janusgraph-inmemory/src/main/java/org/janusgraph/diskstorage/inmemory/BufferPageUtils.java
  janusgraph-inmemory/src/test/java/org/janusgraph/diskstorage/inmemory/BufferPageTest.java
Labels: cla: yes

#2350 Compose no longer supports JanusGraph
  README.md
Labels: cla: external

#2353 Update mailing lists to LF AI & Data
  README.md
Labels: cla: external

#2354 Add JanusGraph LinkedIn link
  README.md
Labels: cla: external

#2252 Improve issue templates
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/config.yaml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/flaky-test.md
  .github/ISSUE_TEMPLATE/question.md
  .github/workflows/ci-backend-cql.yml
  .github/workflows/ci-backend-hbase.yml
  .github/workflows/ci-core.yml
  .github/workflows/ci-index-es.yml
  .github/workflows/ci-index-solr.yml
  .github/workflows/ci-release.yml
Labels: cla: external

#2360 Indicate vertex-centric index usage in profiler result
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/KeySliceQuery.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/SliceQuery.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/EdgeSerializer.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/ElementQuery.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/GraphCentricQuery.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/profile/QueryProfiler.java
Labels: cla: external

#2363 Refactor JanusGraphStep::buildGlobalGraphCentricQuery
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/QueryInfo.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphStep.java
Labels: cla: external, kind/cleanup

#2377 Add test for multiple index backends
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/BerkeleyElasticsearchTest.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/CQLElasticsearchTest.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticsearchJanusGraphIndexTest.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/JanusGraphElasticsearchContainer.java
  janusgraph-lucene/src/test/java/org/janusgraph/diskstorage/lucene/BerkeleyLuceneTest.java
  janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/BerkeleySolrTest.java
  janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/CQLSolrTest.java
  janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/JanusGraphSolrContainer.java
  janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/SolrJanusGraphIndexTest.java
Labels: area/testing, cla: external

#2384 [Doc] Remove mention of Faunus
  docs/advanced-topics/eventual-consistency.md
Labels: cla: external

#2385 Reduce redundant calls to getIdValue in addVertex method
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphBlueprintsTransaction.java
Labels: cla: external, kind/cleanup

#2378 Cleanup maven
  janusgraph-dist/pom.xml
  janusgraph-driver/pom.xml
  pom.xml
Labels: cla: external, dependencies, kind/cleanup

#2393 Update ElasticSearch tested compatibility to 7.10.2
  docs/changelog.md
  janusgraph-es/pom.xml
Labels: cla: external

#2364 Refactor JanusGraphServer in preperation for a GRPC server
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/StandardJanusGraph.java
  janusgraph-server/pom.xml
  janusgraph-server/src/main/java/org/janusgraph/graphdb/server/JanusGraphServer.java
  janusgraph-server/src/main/java/org/janusgraph/graphdb/server/utils/GremlinSettingsUtils.java
  janusgraph-server/src/test/java/org/janusgraph/graphdb/server/JanusGraphServerTest.java
  janusgraph-server/src/test/java/org/janusgraph/graphdb/server/utils/GremlinSettingsUtilsTest.java
  janusgraph-server/src/test/resources/conf/janusgraph-inmemory.properties
  janusgraph-server/src/test/resources/invalid-config.yaml
  janusgraph-server/src/test/resources/janusgraph-server-with-serializers.yaml
  janusgraph-server/src/test/resources/janusgraph-server-without-serializers.yaml
  janusgraph-server/src/test/resources/org/janusgraph/graphdb/tinkerpop/gremlin-server-integration.yaml
Labels: area/server, area/testing, cla: external, kind/enhancement

#2365 Enhance GraphCentricQuery profiling
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/testutil/JanusGraphAssert.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/GraphCentricQuery.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/GraphCentricQueryBuilder.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/profile/QueryProfiler.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphStep.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/util/ProfiledIterator.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/util/SubqueryIterator.java
  janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/SolrJanusGraphIndexTest.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/query/QueryTest.java
Labels: cla: external

#2411 Update TinkerPop to 3.4.10 [tp-tests]
  docs/changelog.md
  mkdocs.yml
  pom.xml
Labels: area/tinkerpop, dependencies

#2326 Refactor dist tests
  janusgraph-dist/pom.xml
  janusgraph-dist/src/test/java/org/janusgraph/pkgtest/AbstractJanusGraphAssemblyIT.java
  janusgraph-dist/src/test/java/org/janusgraph/pkgtest/BerkeleyAssemblyIT.java
  janusgraph-dist/src/test/java/org/janusgraph/pkgtest/BerkeleyESAssemblyIT.java
  janusgraph-dist/src/test/java/org/janusgraph/pkgtest/CqlAssemblyIT.java
  janusgraph-dist/src/test/java/org/janusgraph/pkgtest/CqlESAssemblyIT.java
  janusgraph-dist/src/test/java/org/janusgraph/pkgtest/GraphOfTheGodsCompatIT.java
  janusgraph-dist/src/test/java/org/janusgraph/pkgtest/GremlinShellArgsIT.java
  janusgraph-dist/src/test/java/org/janusgraph/pkgtest/InMemoryAssemblyIT.java
  janusgraph-dist/src/test/java/org/janusgraph/pkgtest/JanusGraphAssemblyBaseIT.java
  janusgraph-dist/src/test/java/org/janusgraph/pkgtest/JanusGraphScriptIT.java
Labels: cla: external
