Repository JanusGraph/janusgraph, pull requests merged in 2022-11, with the labels that each got.

#3248 add backport action
  .backportrc.json
  .github/workflows/backport.yml
Labels: cla: external

#3273 [v0.6] Bump commons-text from 1.9 to 1.10.0
  janusgraph-driver/pom.xml
  pom.xml
Labels: cla: external, backport/skip

#3279 Add possibility to invalidate cached indices with indexOnly constraint
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/IndexSerializer.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/util/IndexAppliesToFunction.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/util/IndexRecordUtil.java
Labels: cla: external

#3281 change dependabot for backport
  .github/dependabot.yml
Labels: cla: external

#3262 Cleanup log dependency
  janusgraph-cql/pom.xml
  janusgraph-dist/pom.xml
  janusgraph-dist/src/assembly/static/bin/gremlin.bat
  janusgraph-dist/src/assembly/static/bin/gremlin.sh
  janusgraph-dist/src/assembly/static/bin/janusgraph-server.sh
  janusgraph-dist/src/assembly/static/conf/log4j2-console.xml
  janusgraph-dist/src/assembly/static/conf/log4j2-server.xml
  janusgraph-dist/src/test/log4j2-test.xml
  janusgraph-hadoop/pom.xml
  janusgraph-hbase/pom.xml
  pom.xml
Labels: cla: external

#3280 [v0.6] Bump protobuf-java from 3.21.6 to 3.21.7
  pom.xml
Labels: cla: external, backport/skip

#3299 [v0.6] Bump codecov/codecov-action from 1 to 3
  .github/workflows/ci-backend-cql.yml
  .github/workflows/ci-backend-hbase.yml
  .github/workflows/ci-core.yml
  .github/workflows/ci-index-es.yml
  .github/workflows/ci-index-solr.yml
Labels: cla: external, backport/skip

#3302 [v0.6] Bump actions/setup-python from 2 to 4
  .github/workflows/ci-publish.yml
Labels: cla: external, backport/skip

#3305 build dependabot branches once
  .github/workflows/ci-backend-cql.yml
  .github/workflows/ci-backend-hbase.yml
  .github/workflows/ci-benchmark.yml
  .github/workflows/ci-core.yml
  .github/workflows/ci-docs.yml
  .github/workflows/ci-index-es.yml
  .github/workflows/ci-index-solr.yml
  .github/workflows/ci-release.yml
  .github/workflows/lint-proto.yml
Labels: cla: external

#3307 [v0.6] Bump actions/upload-artifact from 2 to 3
  .github/workflows/ci-backend-cql.yml
  .github/workflows/ci-backend-hbase.yml
  .github/workflows/ci-core.yml
  .github/workflows/ci-docs.yml
  .github/workflows/ci-index-es.yml
  .github/workflows/ci-index-solr.yml
  .github/workflows/ci-release.yml
Labels: cla: external, backport/skip

#3303 [v0.6] Bump cassandra-driver.version from 4.14.1 to 4.15.0
  pom.xml
Labels: cla: external, backport/skip

#3298 [v0.6] Bump actions/checkout from 2 to 3
  .github/workflows/ci-backend-cql.yml
  .github/workflows/ci-backend-hbase.yml
  .github/workflows/ci-core.yml
  .github/workflows/ci-docs.yml
  .github/workflows/ci-index-es.yml
  .github/workflows/ci-index-solr.yml
  .github/workflows/ci-java-11.yml
  .github/workflows/ci-publish.yml
  .github/workflows/ci-release.yml
  .github/workflows/lint-proto.yml
Labels: cla: external, backport/skip

#3308 [v0.6] Bump nimbus-jose-jwt from 9.8.1 to 9.25.6
  pom.xml
Labels: cla: external, backport/skip

#3306 [v0.6] Bump jackson2.version from 2.13.4 to 2.14.0
  pom.xml
Labels: cla: external, backport/skip

#3235 Skip steps with step labels in AdjacentVertexFilterOptimizerStrategy
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/AdjacentVertexFilterOptimizerStrategy.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/AdjacentVertexFilterOptimizerStrategyTest.java
Labels: cla: external

#3327 Add possibility to remove stale mixed index entries for given vertices or edges
  docs/advanced-topics/stale-index.md
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/util/StaleIndexRecordUtil.java
Labels: kind/enhancement, area/index, cla: external

#3331 Test stale composite index force record removal works with indexOnly constraint
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
Labels: area/testing, cla: external

#3309 [v0.6] Bump actions/setup-java from 1 to 3
  .github/workflows/ci-backend-cql.yml
  .github/workflows/ci-backend-hbase.yml
  .github/workflows/ci-core.yml
  .github/workflows/ci-docs.yml
  .github/workflows/ci-index-es.yml
  .github/workflows/ci-index-solr.yml
  .github/workflows/ci-java-11.yml
  .github/workflows/ci-publish.yml
  .github/workflows/ci-release.yml
Labels: cla: external, backport/skip

#3332 [v0.6] Bump actions/cache from 2 to 3
  .github/workflows/ci-backend-cql.yml
  .github/workflows/ci-backend-hbase.yml
  .github/workflows/ci-core.yml
  .github/workflows/ci-docs.yml
  .github/workflows/ci-index-es.yml
  .github/workflows/ci-index-solr.yml
  .github/workflows/ci-java-11.yml
  .github/workflows/ci-release.yml
Labels: cla: external, backport/skip

#3333 CQLStoreFeature updated - AWSKeyspace supports cell level TTL
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/builder/CQLStoreFeaturesBuilder.java
Labels: cla: external

#3343 Bump test dependencies (JUnit & Mockito)
  pom.xml
Labels: dependencies, cla: external, backport, backport/v0.6

#3345 [v0.6] Bump test dependencies (JUnit & Mockito)
  pom.xml
Labels: cla: external, backport/skip
