Repository JanusGraph/janusgraph, pull requests merged in 2022-06, with the labels that each got.

#3041 Report benchmark performance per Pull Request
  .github/workflows/ci-benchmark.yml
  .github/workflows/ci-release.yml
  janusgraph-benchmark/src/main/java/org/janusgraph/BenchmarkRunner.java
  janusgraph-benchmark/src/main/java/org/janusgraph/JanusGraphSpeedBenchmark.java
Labels: cla: external

#3068 Doc: Explain indexing with partial fields present
  docs/schema/index-management/index-performance.md
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
Labels: cla: external

#3072 Guard against NPE when dropping non-existing graphs
  janusgraph-backend-testutils/src/main/java/org/janusgraph/core/AbstractConfiguredGraphFactoryTest.java
  janusgraph-core/src/main/java/org/janusgraph/core/ConfiguredGraphFactory.java
Labels: cla: external

#3084 Add pointer to Discord Server
  .github/ISSUE_TEMPLATE/bug-report.md
  README.md
Labels: cla: external

#3065 Document ConfiguredGraphFactory::getConfiguration method
  docs/operations/configured-graph-factory.md
Labels: area/docs, cla: external

#3087 Mark 0.5.z releases as EOL
  docs/changelog.md
Labels: cla: external

#3088 Fix gremlin version in console
  pom.xml
Labels: cla: external

#3090 Update test dependencies
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/rest/RestClientSetupTest.java
  janusgraph-inmemory/src/test/java/org/janusgraph/diskstorage/inmemory/InMemoryColumnValueStoreTest.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/database/IndexSerializerTest.java
  pom.xml
Labels: cla: external

#3121 Bump SLF4J to v1.7.36
  pom.xml
Labels: dependencies, cla: external
