Repository JanusGraph/janusgraph, pull requests merged in 2022-01, with the labels that each got.

#2904 #2900 Replace high-scale-lib with jctools-core to fix Eclipse errors
  janusgraph-core/pom.xml
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/cache/StandardSchemaCache.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/computer/FulgoraVertexMemory.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/vertexcache/GuavaVertexCache.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/util/ConcurrentLRUCache.java
  pom.xml
Labels: cla: external

#2918 Delete depcrecated schema definition tools
  docs/changelog.md
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/schema/EdgeLabelDefinition.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/schema/PropertyKeyDefinition.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/schema/RelationTypeDefinition.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/schema/SchemaContainer.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/schema/SchemaElementDefinition.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/schema/SchemaProvider.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/schema/VertexLabelDefinition.java
Labels: kind/cleanup, cla: external

#2899 Fix NullPointerException caused by transaction release
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/addedrelations/EmptyAddedRelations.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/indexcache/EmptyIndexCache.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/subquerycache/EmptySubqueryCache.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/vertexcache/EmptyVertexCache.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTxTest.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/transaction/addedrelations/EmptyAddedRelationsTest.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/transaction/indexcache/EmptyIndexCacheTest.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/transaction/subquerycache/EmptySubqueryCacheTest.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/transaction/vertexcache/EmptyVertexCacheTest.java
Labels: cla: external

#2916 Update janusgraph-server.sh
  janusgraph-dist/src/assembly/static/bin/janusgraph-server.sh
Labels: cla: external

#2876 Implement our own GraphBinary Geoshape serialization
  docs/changelog.md
  docs/interactions/search-predicates.md
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/GeoshapeGraphBinaryConstants.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/GeoshapeGraphBinarySerializer.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/geoshape/BoxSerializer.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/geoshape/CircleSerializer.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/geoshape/GeometryCollectionSerializer.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/geoshape/GeoshapeTypeSerializer.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/geoshape/LineSerializer.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/geoshape/MultiLineSerializer.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/geoshape/MultiPointSerializer.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/geoshape/MultiPolygonSerializer.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/geoshape/PointCollectionSerializer.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/geoshape/PointSerializer.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/geoshape/PolygonSerializer.java
  janusgraph-driver/src/test/java/org/janusgraph/graphdb/tinkerpop/io/binary/GeoshapeGraphBinarySerializerTest.java
Labels: area/core, cla: external

#2920 Cleanup deprecated serialization method
  docs/changelog.md
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/DeprecatedJanusGraphPSerializer.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphIoRegistry.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphIoRegistryV1d0.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/graphson/JanusGraphSONModule.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/graphson/JanusGraphSONModuleV2d0.java
  janusgraph-driver/src/test/java/org/janusgraph/graphdb/tinkerpop/JanusGraphIoRegistryTest.java
  janusgraph-driver/src/test/java/org/janusgraph/graphdb/tinkerpop/JanusGraphSerializerBaseIT.java
Labels: kind/cleanup, cla: external

#2919 Cleanup JanusGraph-dist module
  .gitignore
  BUILDING.md
  janusgraph-dist/Dockerfile
  janusgraph-dist/README.md
  janusgraph-dist/docker-compose.yml
  janusgraph-dist/es/elasticsearch.yml
  janusgraph-dist/pom.xml
  janusgraph-dist/src/assembly/descriptor/common-full.component.xml
  janusgraph-dist/src/assembly/descriptor/common.component.xml
  janusgraph-dist/src/assembly/descriptor/pkgtools.xml
  janusgraph-dist/src/pkg/resources/pkgcommon/etc/version.sh
  janusgraph-dist/src/pkg/static/debian/.gitignore
  janusgraph-dist/src/pkg/static/debian/README.packager
  janusgraph-dist/src/pkg/static/debian/build.sh
  janusgraph-dist/src/pkg/static/debian/compat
  janusgraph-dist/src/pkg/static/debian/control
  janusgraph-dist/src/pkg/static/debian/generate-changes.sh
  janusgraph-dist/src/pkg/static/debian/janusgraph.default
  janusgraph-dist/src/pkg/static/debian/janusgraph.dirs
  janusgraph-dist/src/pkg/static/debian/janusgraph.init
  janusgraph-dist/src/pkg/static/debian/janusgraph.install
  janusgraph-dist/src/pkg/static/debian/janusgraph.postinst
  janusgraph-dist/src/pkg/static/debian/reprepro.conf/README.md
  janusgraph-dist/src/pkg/static/debian/reprepro.conf/distributions
  janusgraph-dist/src/pkg/static/debian/reprepro.conf/options
  janusgraph-dist/src/pkg/static/debian/reprepro.conf/override.aurelius
  janusgraph-dist/src/pkg/static/debian/rules
  janusgraph-dist/src/pkg/static/debian/source/format
  janusgraph-dist/src/pkg/static/pkgcommon/bin/build-all.sh
  janusgraph-dist/src/pkg/static/pkgcommon/bin/clean.sh
  janusgraph-dist/src/pkg/static/pkgcommon/bin/install-jars.sh
  janusgraph-dist/src/pkg/static/pkgcommon/bin/install-payload.sh
  janusgraph-dist/src/pkg/static/pkgcommon/bin/partition-jars.sh
  janusgraph-dist/src/pkg/static/pkgcommon/bin/quick-setup-for-debian.sh
  janusgraph-dist/src/pkg/static/pkgcommon/bin/quick-setup-for-redhat.sh
  janusgraph-dist/src/pkg/static/pkgcommon/bin/update-local-repos.sh
  janusgraph-dist/src/pkg/static/pkgcommon/etc/config.sh
  janusgraph-dist/src/pkg/static/pkgcommon/payload/etc/janusgraph/cassandra.yaml
  janusgraph-dist/src/pkg/static/pkgcommon/payload/etc/janusgraph/config.properties
  janusgraph-dist/src/pkg/static/pkgcommon/payload/etc/janusgraph/janusgraph-env.sh
  janusgraph-dist/src/pkg/static/pkgcommon/payload/etc/janusgraph/log4j.properties
  janusgraph-dist/src/pkg/static/pkgcommon/payload/usr/bin/gremlin.sh
  janusgraph-dist/src/pkg/static/pkgcommon/payload/usr/sbin/janusgraph
  janusgraph-dist/src/pkg/static/pkgcommon/payload/usr/share/janusgraph/janusgraph.in.sh
  janusgraph-dist/src/pkg/static/redhat/build.sh
  janusgraph-dist/src/pkg/static/redhat/janusgraph.spec.base
  janusgraph-dist/src/pkg/static/redhat/payload/janusgraph.init
  janusgraph-dist/src/pkg/static/redhat/payload/janusgraph.sysconfig
  pom.xml
Labels: kind/cleanup, cla: external

#2912 Add unordered scan annotation for CQL byteordered partitioner [cql-tests]
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/builder/CQLStoreFeaturesBuilder.java
  janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLStoreTest.java
Labels: cla: external

#2909 Allow CQL compaction-strategy-class without options
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java
  janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStoreTest.java
Labels: cla: external

#2935 Mark cache expiration test as flaky
  janusgraph-test/src/test/java/org/janusgraph/diskstorage/cache/ExpirationCacheTest.java
Labels: cla: external

#2926 Remove deprecated no stream methods
  docs/changelog.md
  docs/index-backend/direct-index-query.md
  janusgraph-backend-testutils/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java
  janusgraph-core/src/main/java/org/janusgraph/core/JanusGraphIndexQuery.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/indexing/IndexTransaction.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/IndexQueryBuilder.java
  janusgraph-hadoop/src/test/resources/org/janusgraph/hadoop/formats/graphson/incremental-custom-cerberus-load.groovy
  janusgraph-hadoop/src/test/resources/org/janusgraph/hadoop/formats/graphson/incremental-load.groovy
  janusgraph-hadoop/src/test/resources/org/janusgraph/hadoop/formats/graphson/incremental-naive-cerberus-load.groovy
Labels: cla: external

#2933 Ensure Jetty versions are aligned
  pom.xml
Labels: dependencies, cla: external

#2928 Remove general deprecated classes
  docs/changelog.md
  janusgraph-core/src/main/java/org/janusgraph/core/util/JanusGraphId.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/util/AllEdgesIterable.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/util/AllEdgesIterator.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/util/ConcurrentLRUCache.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/util/PriorityQueue.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/vertices/RemovableRelationIterable.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/vertices/RemovableRelationIterator.java
  janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/ImmutableConfiguration.java
Labels: cla: external

#2910 Add Management API to run ghost vertex remover
  docs/operations/management.md
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/core/schema/JanusGraphManagement.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java
Labels: kind/enhancement, area/docs, area/core, cla: external

#2949 (#2948) Added G.V() - Gremlin IDE to Visualization section of main RE…
  README.md
Labels: cla: external

#2941 Make automatic release artifacts publishing
  .github/workflows/ci-publish.yml
  KEYS
  RELEASING.md
Labels: cla: external

#2952 JanusGraph release 0.6.1 [cql-tests] [tp-tests]
  docs/changelog.md
  janusgraph-all/pom.xml
  janusgraph-backend-testutils/pom.xml
  janusgraph-berkeleyje/pom.xml
  janusgraph-bigtable/pom.xml
  janusgraph-core/pom.xml
  janusgraph-cql/pom.xml
  janusgraph-dist/pom.xml
  janusgraph-doc/pom.xml
  janusgraph-driver/pom.xml
  janusgraph-es/pom.xml
  janusgraph-examples/example-berkeleyje/pom.xml
  janusgraph-examples/example-common/pom.xml
  janusgraph-examples/example-cql/pom.xml
  janusgraph-examples/example-hbase/pom.xml
  janusgraph-examples/example-remotegraph/pom.xml
  janusgraph-examples/example-tinkergraph/pom.xml
  janusgraph-examples/pom.xml
  janusgraph-grpc/pom.xml
  janusgraph-hadoop/pom.xml
  janusgraph-hbase/pom.xml
  janusgraph-inmemory/pom.xml
  janusgraph-lucene/pom.xml
  janusgraph-server/pom.xml
  janusgraph-solr/pom.xml
  janusgraph-test/pom.xml
  mkdocs.yml
  pom.xml
Labels: cla: external

#2953 Astra DB configuration doc update
  docs/storage-backend/cassandra.md
Labels: cla: external
