Repository JanusGraph/janusgraph, pull requests merged in 2022-12, with the labels that each got.

#3358 [v0.6] Bump netty4.version from 4.1.82.Final to 4.1.85.Final
  pom.xml
Labels: cla: external, backport/skip

#3339 Use graph name for ES indices if index name is not configured
  docs/changelog.md
  docs/operations/configured-graph-factory.md
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/configuration/converter/ReadConfigurationConverter.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java
  janusgraph-es/src/test/java/org/janusgraph/core/es/ElasticsearchConfiguredGraphFactoryTest.java
  janusgraph-test/src/test/java/org/janusgraph/diskstorage/configuration/converter/ReadConfigurationConverterTest.java
Labels: cla: external

#3342 Do not store distinct elements when single iterator processed
  janusgraph-core/src/main/java/org/janusgraph/graphdb/util/MultiDistinctOrderedIterator.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/util/MultiDistinctUnorderedIterator.java
Labels: kind/performance, cla: external

#3350 JanusGraph release candidate 1.0.0-rc1 [cql-tests] [tp-tests]
  cassandra-hadoop-util/pom.xml
  janusgraph-all/pom.xml
  janusgraph-backend-testutils/pom.xml
  janusgraph-benchmark/pom.xml
  janusgraph-berkeleyje/pom.xml
  janusgraph-bigtable/pom.xml
  janusgraph-core/pom.xml
  janusgraph-cql/pom.xml
  janusgraph-dist/pom.xml
  janusgraph-doc/pom.xml
  janusgraph-driver/pom.xml
  janusgraph-es/pom.xml
  janusgraph-examples/example-berkeleyje/pom.xml
  janusgraph-examples/example-common/pom.xml
  janusgraph-examples/example-cql/pom.xml
  janusgraph-examples/example-hbase/pom.xml
  janusgraph-examples/example-remotegraph/pom.xml
  janusgraph-examples/example-tinkergraph/pom.xml
  janusgraph-examples/pom.xml
  janusgraph-grpc/pom.xml
  janusgraph-hadoop/pom.xml
  janusgraph-hbase/pom.xml
  janusgraph-inmemory/pom.xml
  janusgraph-lucene/pom.xml
  janusgraph-server/pom.xml
  janusgraph-solr/pom.xml
  janusgraph-test/pom.xml
  mkdocs.yml
  pom.xml
Labels: cla: external

#3364 Publish commit packages to Sonatype
  .github/workflows/ci-publish-commit.yml
  .github/workflows/ci-publish-official.yml
  docs/advanced-topics/commit-releases.md
  docs/advanced-topics/github_distribution_builds.png
  docs/advanced-topics/github_expired_distribution_builds.png
  docs/advanced-topics/github_release_ci.png
  docs/development.md
  mkdocs.yml
  pom.xml
Labels: cla: external

#3375 [v0.6] Fix the issue [#3344]
  janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/formats/util/HadoopRecordReader.java
  janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/formats/util/JanusGraphVertexDeserializer.java
Labels: cla: external, backport/skip

#3369 [v0.6] Bump commons-net from 3.8.0 to 3.9.0
  pom.xml
Labels: cla: external, backport/skip

#3370 Apply Dependabot config also for security updates
  .github/dependabot.yml
Labels: cla: external

#3396 Amazon Keyspace: Add hint on full-scan
  docs/storage-backend/cassandra.md
Labels: cla: external

#3402 [v0.6] Bump error_prone_annotations from 2.14.0 to 2.16
  pom.xml
Labels: cla: external, backport/skip

#3401 Add release lessons learned from 1.0.0-rc1
  RELEASING.md
Labels: cla: external

#3405 [v0.6] Bump avro from 1.11.0 to 1.11.1
  pom.xml
Labels: cla: external, backport/skip

#3407 [v0.6] Bump jackson2.version from 2.14.0 to 2.14.1
  pom.xml
Labels: cla: external, backport/skip

#3416 [v0.6] Bump netty4.version from 4.1.85.Final to 4.1.86.Final
  pom.xml
Labels: cla: external, backport/skip

#3419 [v0.6] Bump httpcomponents.httpcore.version from 4.4.15 to 4.4.16
  pom.xml
Labels: cla: external, backport/skip

#3420 [v0.6] Bump httpclient from 4.5.13 to 4.5.14
  pom.xml
Labels: cla: external, backport/skip

#3430 [v0.6] Bump maven-jar-plugin from 3.2.2 to 3.3.0
  pom.xml
Labels: cla: external, backport/skip
