Repository JanusGraph/janusgraph, pull requests merged in 2023-08, with the labels that each got.

#3902 [v0.6] Bump cassandra-driver.version from 4.16.0 to 4.17.0
  pom.xml
Labels: cla: external, backport/skip

#3842 Re-tag images after release mark ready
  .github/workflows/ci-backend-cql-dummy.yml
  .github/workflows/ci-backend-cql.yml
  .github/workflows/ci-backend-hbase-dummy.yml
  .github/workflows/ci-backend-hbase.yml
  .github/workflows/ci-backend-scylla-dummy.yml
  .github/workflows/ci-backend-scylla.yml
  .github/workflows/ci-benchmark.yml
  .github/workflows/ci-core-dummy.yml
  .github/workflows/ci-core.yml
  .github/workflows/ci-docs.yml
  .github/workflows/ci-index-es-dummy.yml
  .github/workflows/ci-index-es.yml
  .github/workflows/ci-index-solr-dummy.yml
  .github/workflows/ci-index-solr.yml
  .github/workflows/ci-publish-commit.yml
  .github/workflows/ci-publish-official.yml
  .github/workflows/ci-release-dummy.yml
  .github/workflows/ci-release.yml
  .github/workflows/docker-release-tags.yml
  RELEASING.md
  janusgraph-dist/docker/Dockerfile
  janusgraph-dist/docker/build-and-push-image.sh
  janusgraph-dist/pom.xml
Labels: cla: external, backport/v0.6

#3906 [v0.6] Re-tag images after release mark ready
  .github/workflows/ci-backend-cql-dummy.yml
  .github/workflows/ci-backend-cql.yml
  .github/workflows/ci-backend-hbase-dummy.yml
  .github/workflows/ci-backend-hbase.yml
  .github/workflows/ci-core-dummy.yml
  .github/workflows/ci-core.yml
  .github/workflows/ci-docs.yml
  .github/workflows/ci-index-es-dummy.yml
  .github/workflows/ci-index-es.yml
  .github/workflows/ci-index-solr-dummy.yml
  .github/workflows/ci-index-solr.yml
  .github/workflows/ci-java-11.yml
  .github/workflows/ci-publish-commit.yml
  .github/workflows/ci-publish-official.yml
  .github/workflows/ci-release-dummy.yml
  .github/workflows/ci-release.yml
  .github/workflows/docker-release-tags.yml
  RELEASING.md
  janusgraph-dist/docker/Dockerfile
  janusgraph-dist/docker/build-and-push-image.sh
  janusgraph-dist/pom.xml
Labels: backport/skip

#3879 Group CQL keys into a single query [cql-tests] [tp-tests]
  docs/changelog.md
  docs/configs/janusgraph-cfg.md
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/EntryMetaData.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/CompletableFutureUtil.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/StaticArrayEntryList.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLColValGetter.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/QueryGroups.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/function/slice/AsyncCQLFunction.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/function/slice/AsyncCQLMultiKeyMultiColumnFunction.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/function/slice/AsyncCQLMultiKeySliceFunction.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/function/slice/AsyncCQLSingleKeyMultiColumnFunction.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/function/slice/AsyncCQLSingleKeySliceFunction.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/query/MultiKeysMultiColumnQuery.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/query/MultiKeysSingleSliceQuery.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/query/SingleKeyMultiColumnQuery.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/service/AsyncQueryExecutionService.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/service/GroupingAsyncQueryExecutionService.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/strategy/GroupedExecutionStrategy.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/strategy/GroupedExecutionStrategyBuilder.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/strategy/ReplicasAwareGroupedExecutionStrategy.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/strategy/ResultFiller.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/strategy/TokenRangeAwareGroupedExecutionStrategy.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/util/CQLSliceQueryUtil.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/util/KeysGroup.java
  janusgraph-cql/src/test/java/org/janusgraph/JanusGraphCassandraContainer.java
  janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/strategy/GroupedExecutionStrategyBuilderTest.java
  janusgraph-cql/src/test/java/org/janusgraph/graphdb/cql/CQLGraphTest.java
Labels: cla: external

#3897 Update Guava to 32.1.1-jre and protobuf to 3.23.4 [cql-tests] [tp-tests]
  pom.xml
Labels: cla: external

#3907 Document textContainsPhrase
  docs/index-backend/text-search.md
Labels: cla: external

#3912 [v0.6] Document textContainsPhrase (#3907)
  docs/index-backend/text-search.md
Labels: cla: external, backport/skip

#3914 Upgrade TinkerPop version to 3.7.0 [cql-tests][tp-tests]
  docs/changelog.md
  docs/interactions/connecting/java.md
  docs/operations/dynamic-graphs.md
  janusgraph-backend-testutils/src/main/java/org/janusgraph/olap/OLAPTest.java
  janusgraph-core/src/main/java/org/janusgraph/core/JanusGraph.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/computer/FulgoraGraphComputer.java
  janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-berkeleyje-es.yaml
  janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-berkeleyje.yaml
  janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-configuration.yaml
  janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-cql-es.yaml
  janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-cql.yaml
  janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-hbase-es.yaml
  janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server-hbase.yaml
  janusgraph-dist/src/assembly/static/conf/gremlin-server/gremlin-server.yaml
  janusgraph-dist/src/assembly/static/conf/remote-graph-binary.yaml
  janusgraph-dist/src/assembly/static/conf/remote-objects.yaml
  janusgraph-dist/src/assembly/static/conf/remote.yaml
  janusgraph-dist/src/test/java/org/janusgraph/pkgtest/AbstractJanusGraphAssemblyIT.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/query/JanusGraphPredicate.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/JanusGraphP.java
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/GeoshapeGraphBinarySerializer.java
  janusgraph-driver/src/test/java/org/janusgraph/graphdb/tinkerpop/JanusGraphIoRegistryTest.java
  janusgraph-driver/src/test/java/org/janusgraph/graphdb/tinkerpop/io/binary/GeoshapeGraphBinarySerializerTest.java
  janusgraph-driver/src/test/java/org/janusgraph/graphdb/tinkerpop/io/binary/JanusGraphPGraphBinarySerializerTest.java
  janusgraph-driver/src/test/java/org/janusgraph/graphdb/tinkerpop/io/binary/RelationIdentifierGraphBinarySerializerTest.java
  janusgraph-examples/example-remotegraph/conf/remote-objects.yaml
  janusgraph-server/pom.xml
  janusgraph-server/src/main/java/org/janusgraph/graphdb/server/util/JanusGraphSettingsUtils.java
  janusgraph-server/src/test/java/org/janusgraph/graphdb/server/util/JanusGraphSettingsUtilsTest.java
  janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/io/JanusGraphBinaryModuleIT.java
  janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/io/JanusGraphSONModuleIT.java
  janusgraph-server/src/test/resources/janusgraph-server-custom-id.yaml
  janusgraph-server/src/test/resources/janusgraph-server-integration.yaml
  janusgraph-server/src/test/resources/janusgraph-server-with-grpc.yaml
  janusgraph-server/src/test/resources/janusgraph-server-with-serializers.yaml
  mkdocs.yml
  pom.xml
Labels: area/tinkerpop, cla: external

#3919 [v0.6] Bump netty4.version from 4.1.94.Final to 4.1.96.Final
  pom.xml
Labels: cla: external, backport/skip

#3920 [v0.6] Bump grpc.version from 1.56.1 to 1.57.1
  pom.xml
Labels: cla: external, backport/skip

#3915 Add multi-query support to label step
  docs/changelog.md
  docs/configs/janusgraph-cfg.md
  docs/operations/batch-processing.md
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-benchmark/src/main/java/org/janusgraph/CQLMultiQueryBenchmark.java
  janusgraph-core/src/main/java/org/janusgraph/core/TransactionBuilder.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphLabelStep.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/JanusGraphLocalQueryOptimizerStrategy.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/MultiQueryLabelStepStrategyMode.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardTransactionBuilder.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/TransactionConfiguration.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphStepStrategyTest.java
Labels: kind/performance, cla: external

#3918 Let Dependabot update JUnit dependencies together
  .github/dependabot.yml
Labels: cla: external

#3938 [v0.6] Bump grpc.version from 1.57.1 to 1.57.2
  pom.xml
Labels: cla: external, backport/skip

#3939 [v0.6] Bump org.xerial.snappy:snappy-java from 1.1.10.1 to 1.1.10.3
  pom.xml
Labels: cla: external, backport/skip
