Repository JanusGraph/janusgraph, pull requests merged in 2023-04, with the labels that each got.

#3687 Profiler: Display multiKSQ detail
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/MultiKeySliceQuery.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/query/QueryTest.java
Labels: kind/enhancement, area/core, cla: external, backport/v0.6

#3713 Partitioning: Discourage usage of vertex cut feature
  docs/advanced-topics/partitioning.md
Labels: cla: external, backport/v0.6

#3727 [v0.6] Bump grpc.version from 1.54.0 to 1.54.1
  pom.xml
Labels: cla: external, backport/skip

#3730 [v0.6] Bump testcontainers.version from 1.17.6 to 1.18.0
  pom.xml
Labels: cla: external, backport/skip

#3731 [v0.6] Partitioning: Discourage usage of vertex cut feature
  docs/advanced-topics/partitioning.md
Labels: cla: external

#3706 Refactors Iterable to Stream usage and fix Stream to Iterable conversion usages
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphBaseTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/index/AbstractIndexSelectionStrategy.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/BasicVertexCentricQueryBuilder.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/MultiVertexCentricQueryBuilder.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/types/vertices/EdgeLabelVertex.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/types/vertices/RelationTypeVertex.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/util/StreamIterable.java
  janusgraph-core/src/main/java/org/janusgraph/util/datastructures/IterablesUtil.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java
  janusgraph-examples/example-common/src/test/java/org/janusgraph/example/JanusGraphAppTest.java
  janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/config/HadoopConfiguration.java
  janusgraph-test/src/test/java/org/janusgraph/diskstorage/configuration/ConfigurationTest.java
Labels: kind/bug/confirmed, cla: external, backport/v0.6

#3705 Reduce redundant operations in MultiVertexCentricQueryBuilder
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/BasicVertexCentricQueryBuilder.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/MultiVertexCentricQueryBuilder.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/VertexCentricQueryBuilder.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java
Labels: cla: external

#3711 Fix potential lost exception during multi-query properties or vertex steps
  janusgraph-core/pom.xml
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphEdgeVertexStep.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphPropertiesStep.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphVertexStep.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/fetcher/FetchQueryBuildFunction.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/fetcher/MultiQueriableStepBatchFetcher.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/fetcher/PropertiesStepBatchFetcher.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/fetcher/VertexStepBatchFetcher.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java
  janusgraph-core/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/step/fetcher/MultiQueriableStepBatchFetcherTest.java
Labels: cla: external

#3748 Fix typo in java.md
  docs/interactions/connecting/java.md
Labels: cla: external

#3755 Backport #3706
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphBaseTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/indexing/IndexTransaction.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/IndexQueryBuilder.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/index/AbstractIndexSelectionStrategy.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/BasicVertexCentricQueryBuilder.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/MultiVertexCentricQueryBuilder.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/types/vertices/EdgeLabelVertex.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/types/vertices/RelationTypeVertex.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/util/StreamIterable.java
  janusgraph-core/src/main/java/org/janusgraph/util/datastructures/IterablesUtil.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java
  janusgraph-examples/example-common/src/test/java/org/janusgraph/example/JanusGraphAppTest.java
  janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/config/HadoopConfiguration.java
  janusgraph-test/src/test/java/org/janusgraph/diskstorage/configuration/ConfigurationTest.java
Labels: kind/bug/confirmed, cla: external, backport

#3756 Backport #3711
  janusgraph-core/pom.xml
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphEdgeVertexStep.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphPropertiesStep.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphVertexStep.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/fetcher/FetchQueryBuildFunction.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/fetcher/MultiQueriableStepBatchFetcher.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/fetcher/PropertiesStepBatchFetcher.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/fetcher/VertexStepBatchFetcher.java
  janusgraph-core/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/step/fetcher/MultiQueriableStepBatchFetcherTest.java
Labels: kind/bug/confirmed, cla: external, backport
