Repository JanusGraph/janusgraph, pull requests merged in 2023-10, with the labels that each got.

#3992 [v0.6] Merge pull request #3972 from mad/fix-ordered-iterator
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/util/MultiDistinctOrderedIterator.java
Labels: cla: external, backport/skip

#4013 [v0.6] Upgrade TinkerPop version to 3.5.7 [cql-tests][tp-tests]
  docs/changelog.md
  janusgraph-backend-testutils/src/main/java/org/janusgraph/olap/OLAPTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/computer/FulgoraGraphComputer.java
  janusgraph-server/pom.xml
  pom.xml
Labels: cla: external

#4014 [v0.6] Bump com.google.errorprone:error_prone_annotations from 2.21.1 to 2.22.0
  pom.xml
Labels: cla: external, backport/skip

#4004 Add Graphlytic visualization tool #3964
  README.md
Labels: area/docs, cla: external

#4017 [v0.6] Bump netty4.version from 4.1.97.Final to 4.1.99.Final
  pom.xml
Labels: cla: external, backport/skip

#4025 [v0.6] Bump metrics.version from 4.2.19 to 4.2.20
  pom.xml
Labels: cla: external, backport/skip

#4018 [v0.6] Bump org.xerial.snappy:snappy-java from 1.1.10.3 to 1.1.10.5
  pom.xml
Labels: cla: external, backport/skip

#4023 Remove dangling netty dependency management
  pom.xml
Labels: dependencies, cla: external, backport/v0.6

#4024 Bump avro to 1.11.3
  pom.xml
Labels: dependencies, cla: external, backport/v0.6

#4027 Update commons-compress to 1.24.0
  pom.xml
Labels: dependencies, cla: external, java, backport/v0.6

#4029 [v0.6] Update commons-compress to 1.24.0
  pom.xml
Labels: cla: external, backport/skip

#4030 [v0.6] Bump avro to 1.11.3
  pom.xml
Labels: dependencies, cla: external, backport/skip

#4026 [v0.6] Bump testcontainers.version from 1.19.0 to 1.19.1
  pom.xml
Labels: cla: external, backport/skip

#3990 Handle interruption for BerkeleyJE backend
  janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJEKeyValueStore.java
  janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJEStoreManager.java
  janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJETx.java
  janusgraph-berkeleyje/src/test/java/org/janusgraph/BerkeleyInterruptionTest.java
  janusgraph-berkeleyje/src/test/java/org/janusgraph/blueprints/process/BerkeleyJanusGraphComputerTest.java
  janusgraph-berkeleyje/src/test/java/org/janusgraph/blueprints/process/BerkeleyJanusGraphProcessTest.java
  janusgraph-berkeleyje/src/test/java/org/janusgraph/blueprints/process/BerkeleyMultiQueryJanusGraphProcessTest.java
  janusgraph-berkeleyje/src/test/java/org/janusgraph/blueprints/process/BerkeleyProcessComputerSuite.java
  janusgraph-berkeleyje/src/test/java/org/janusgraph/blueprints/process/BerkeleyProcessStandardSuite.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/BackendOperation.java
Labels: cla: external

#4028 [v0.6] Remove dangling netty dependency management
  pom.xml
Labels: cla: external, backport/skip

#4037 Revert "Handle interruption for BerkeleyJE backend [tp-tests]"
  janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJEKeyValueStore.java
  janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJEStoreManager.java
  janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJETx.java
  janusgraph-berkeleyje/src/test/java/org/janusgraph/BerkeleyInterruptionTest.java
  janusgraph-berkeleyje/src/test/java/org/janusgraph/blueprints/process/BerkeleyJanusGraphComputerTest.java
  janusgraph-berkeleyje/src/test/java/org/janusgraph/blueprints/process/BerkeleyJanusGraphProcessTest.java
  janusgraph-berkeleyje/src/test/java/org/janusgraph/blueprints/process/BerkeleyMultiQueryJanusGraphProcessTest.java
  janusgraph-berkeleyje/src/test/java/org/janusgraph/blueprints/process/BerkeleyProcessComputerSuite.java
  janusgraph-berkeleyje/src/test/java/org/janusgraph/blueprints/process/BerkeleyProcessStandardSuite.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/BackendOperation.java
Labels: cla: external

#4038 [v0.6] Revert "Bump metrics.version from 4.2.19 to 4.2.20"
  pom.xml
Labels: cla: external

#4039 JanusGraph release 0.6.4 [cql-tests][tp-tests]
  docs/changelog.md
  janusgraph-all/pom.xml
  janusgraph-backend-testutils/pom.xml
  janusgraph-berkeleyje/pom.xml
  janusgraph-bigtable/pom.xml
  janusgraph-core/pom.xml
  janusgraph-cql/pom.xml
  janusgraph-dist/pom.xml
  janusgraph-doc/pom.xml
  janusgraph-driver/pom.xml
  janusgraph-es/pom.xml
  janusgraph-examples/example-berkeleyje/pom.xml
  janusgraph-examples/example-common/pom.xml
  janusgraph-examples/example-cql/pom.xml
  janusgraph-examples/example-hbase/pom.xml
  janusgraph-examples/example-remotegraph/pom.xml
  janusgraph-examples/example-tinkergraph/pom.xml
  janusgraph-examples/pom.xml
  janusgraph-grpc/pom.xml
  janusgraph-hadoop/pom.xml
  janusgraph-hbase/pom.xml
  janusgraph-inmemory/pom.xml
  janusgraph-lucene/pom.xml
  janusgraph-server/pom.xml
  janusgraph-solr/pom.xml
  janusgraph-test/pom.xml
  mkdocs.yml
  pom.xml
Labels: cla: external

#4031 [Doc] Rename 'Interactions with JanusGraph' section to 'JanusGraph Basics'
  docs/advanced-topics/eventual-consistency.md
  docs/advanced-topics/technical-limitations.md
  docs/basics/connecting/dotnet.md
  docs/basics/connecting/index.md
  docs/basics/connecting/java.md
  docs/basics/connecting/python.md
  docs/basics/search-predicates.md
  docs/basics/transactions.md
  docs/changelog.md
  docs/common-questions.md
  docs/getting-started/gremlin.md
  docs/operations/configured-graph-factory.md
  docs/operations/container.md
  docs/operations/server.md
  docs/schema/index-management/index-performance.md
  mkdocs.yml
Labels: area/docs, cla: external

#4049 Fix configuration reference documentation where wrong next line representation was used CTR
  docs/configs/janusgraph-cfg.md
  janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java
Labels: cla: external

#4051 Reorder and polish change log for 1.0.0 release
  docs/changelog.md
Labels: cla: external

#4053 fix docker-release-tags action
  .github/workflows/docker-release-tags.yml
Labels: cla: external, backport/v0.6

#4052 Set version to 0.6.5-SNAPSHOT
  janusgraph-all/pom.xml
  janusgraph-backend-testutils/pom.xml
  janusgraph-berkeleyje/pom.xml
  janusgraph-bigtable/pom.xml
  janusgraph-core/pom.xml
  janusgraph-cql/pom.xml
  janusgraph-dist/pom.xml
  janusgraph-doc/pom.xml
  janusgraph-driver/pom.xml
  janusgraph-es/pom.xml
  janusgraph-examples/example-berkeleyje/pom.xml
  janusgraph-examples/example-common/pom.xml
  janusgraph-examples/example-cql/pom.xml
  janusgraph-examples/example-hbase/pom.xml
  janusgraph-examples/example-remotegraph/pom.xml
  janusgraph-examples/example-tinkergraph/pom.xml
  janusgraph-examples/pom.xml
  janusgraph-grpc/pom.xml
  janusgraph-hadoop/pom.xml
  janusgraph-hbase/pom.xml
  janusgraph-inmemory/pom.xml
  janusgraph-lucene/pom.xml
  janusgraph-server/pom.xml
  janusgraph-solr/pom.xml
  janusgraph-test/pom.xml
  mkdocs.yml
  pom.xml
Labels: cla: external

#4054 [v0.6] fix docker-release-tags action
  .github/workflows/docker-release-tags.yml
Labels: cla: external, backport/skip

#4050 Add possibility to build JanusGraph Scylla Release
  docs/storage-backend/scylladb.md
  janusgraph-dist/pom.xml
Labels: cla: external, backport/skip

#4064 Update Guava to 32.1.3-jre [cql-tests][tp-tests]
  pom.xml
Labels: cla: external

#4066 [v0.6] Merge pull request #4063 from JanusGraph/dependabot/maven/org.jacoco-org.jacoco.ant-0.8.11
  pom.xml
Labels: cla: external, backport/skip

#4059 Use fixed Java versions for releases
  .github/workflows/ci-publish-commit.yml
  .github/workflows/ci-publish-official.yml
  .github/workflows/ci-release.yml
Labels: cla: external, java

#4056 add trivy scan to docker
  .github/workflows/ci-release.yml
Labels: cla: external, backport/v0.6

#4074 JanusGraph release 1.0.0 [cql-tests][tp-tests]
  .github/workflows/docker-release-tags.yml
  RELEASING.md
  cassandra-hadoop-util/pom.xml
  docs/changelog.md
  janusgraph-all/pom.xml
  janusgraph-backend-testutils/pom.xml
  janusgraph-benchmark/pom.xml
  janusgraph-berkeleyje/pom.xml
  janusgraph-bigtable/pom.xml
  janusgraph-core/pom.xml
  janusgraph-cql/pom.xml
  janusgraph-dist/pom.xml
  janusgraph-doc/pom.xml
  janusgraph-driver/pom.xml
  janusgraph-es/pom.xml
  janusgraph-examples/example-berkeleyje/pom.xml
  janusgraph-examples/example-common/pom.xml
  janusgraph-examples/example-cql/pom.xml
  janusgraph-examples/example-hbase/pom.xml
  janusgraph-examples/example-remotegraph/pom.xml
  janusgraph-examples/example-tinkergraph/pom.xml
  janusgraph-examples/pom.xml
  janusgraph-grpc/pom.xml
  janusgraph-hadoop/pom.xml
  janusgraph-hbase/pom.xml
  janusgraph-inmemory/pom.xml
  janusgraph-lucene/pom.xml
  janusgraph-mixed-index-utils/pom.xml
  janusgraph-scylla/pom.xml
  janusgraph-server/pom.xml
  janusgraph-solr/pom.xml
  janusgraph-test/pom.xml
  mkdocs.yml
  pom.xml
  scylla-hadoop-util/pom.xml
Labels: cla: external

#4075 Restore snapshot version to 1.0.1-SNAPSHOT CTR
  cassandra-hadoop-util/pom.xml
  janusgraph-all/pom.xml
  janusgraph-backend-testutils/pom.xml
  janusgraph-benchmark/pom.xml
  janusgraph-berkeleyje/pom.xml
  janusgraph-bigtable/pom.xml
  janusgraph-core/pom.xml
  janusgraph-cql/pom.xml
  janusgraph-dist/pom.xml
  janusgraph-doc/pom.xml
  janusgraph-driver/pom.xml
  janusgraph-es/pom.xml
  janusgraph-examples/example-berkeleyje/pom.xml
  janusgraph-examples/example-common/pom.xml
  janusgraph-examples/example-cql/pom.xml
  janusgraph-examples/example-hbase/pom.xml
  janusgraph-examples/example-remotegraph/pom.xml
  janusgraph-examples/example-tinkergraph/pom.xml
  janusgraph-examples/pom.xml
  janusgraph-grpc/pom.xml
  janusgraph-hadoop/pom.xml
  janusgraph-hbase/pom.xml
  janusgraph-inmemory/pom.xml
  janusgraph-lucene/pom.xml
  janusgraph-mixed-index-utils/pom.xml
  janusgraph-scylla/pom.xml
  janusgraph-server/pom.xml
  janusgraph-solr/pom.xml
  janusgraph-test/pom.xml
  mkdocs.yml
  pom.xml
  scylla-hadoop-util/pom.xml
Labels: cla: external

#4076 Restore snapshot version to 1.1.0-SNAPSHOT CTR
  .backportrc.json
  RELEASING.md
  cassandra-hadoop-util/pom.xml
  janusgraph-all/pom.xml
  janusgraph-backend-testutils/pom.xml
  janusgraph-benchmark/pom.xml
  janusgraph-berkeleyje/pom.xml
  janusgraph-bigtable/pom.xml
  janusgraph-core/pom.xml
  janusgraph-cql/pom.xml
  janusgraph-dist/pom.xml
  janusgraph-doc/pom.xml
  janusgraph-driver/pom.xml
  janusgraph-es/pom.xml
  janusgraph-examples/example-berkeleyje/pom.xml
  janusgraph-examples/example-common/pom.xml
  janusgraph-examples/example-cql/pom.xml
  janusgraph-examples/example-hbase/pom.xml
  janusgraph-examples/example-remotegraph/pom.xml
  janusgraph-examples/example-tinkergraph/pom.xml
  janusgraph-examples/pom.xml
  janusgraph-grpc/pom.xml
  janusgraph-hadoop/pom.xml
  janusgraph-hbase/pom.xml
  janusgraph-inmemory/pom.xml
  janusgraph-lucene/pom.xml
  janusgraph-mixed-index-utils/pom.xml
  janusgraph-scylla/pom.xml
  janusgraph-server/pom.xml
  janusgraph-solr/pom.xml
  janusgraph-test/pom.xml
  mkdocs.yml
  pom.xml
  scylla-hadoop-util/pom.xml
Labels: cla: external

#4077 Change dependabot default backport label to v1.0 CTR
  .github/dependabot.yml
  RELEASING.md
Labels: cla: external

#4081 Move 0.6 branch to EOL
  docs/changelog.md
Labels: area/docs, cla: external, backport, backport/v0.6, backport/v1.0

#4083 [v1.0] Move 0.6 branch to EOL
  docs/changelog.md
Labels: backport/v0.6
