Repository JanusGraph/janusgraph, pull requests merged in 2023-01, with the labels that each got.

#3432 [v0.6] Bump mockito.version from 4.8.1 to 4.10.0
  pom.xml
Labels: cla: external, backport/skip

#3372 Remove Bigtable as tested compatibility
  docs/changelog.md
Labels: storage/bigtable, cla: external, backport, backport/v0.6

#3443 [v0.6] Remove Bigtable as tested compatibility
  docs/changelog.md
Labels: storage/bigtable, cla: external, backport/skip

#3011 Add get vertex composite index support to grpc
  janusgraph-core/src/main/java/org/janusgraph/core/schema/JanusGraphIndex.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/JanusGraphIndexWrapper.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/util/IndexRecordUtil.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/job/IndexRemoveJob.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/lock/IndexLockTuple.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/types/CompositeIndexType.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/types/IndexType.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/types/indextype/IndexTypeWrapper.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/types/system/BaseKey.java
  janusgraph-grpc/src/main/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerClient.java
  janusgraph-grpc/src/main/proto/janusgraph/schema/v1/schema_manager.proto
  janusgraph-grpc/src/main/proto/janusgraph/types/v1/schema_types.proto
  janusgraph-server/src/main/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerImpl.java
  janusgraph-server/src/main/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerProvider.java
  janusgraph-server/src/main/java/org/janusgraph/graphdb/grpc/schema/util/GrpcUtils.java
  janusgraph-server/src/test/java/org/janusgraph/graphdb/grpc/JanusGraphGrpcServerBaseTest.java
  janusgraph-server/src/test/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerClientTest.java
  janusgraph-server/src/test/java/org/janusgraph/graphdb/grpc/schema/SchemaManagerImplTest.java
  janusgraph-server/src/test/java/org/janusgraph/graphdb/server/TestingServerClosable.java
Labels: cla: external

#3446 JanusGraphSerializerBaseIT: run against latest code
  janusgraph-driver/src/test/java/org/janusgraph/core/JanusGraphContainer.java
  janusgraph-server/pom.xml
  janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/JanusGraphSerializerBaseIT.java
  janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/io/JanusGraphBinaryModuleIT.java
  janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/gremlin/server/io/JanusGraphSONModuleIT.java
  janusgraph-server/src/test/resources/empty-sample.groovy
  janusgraph-server/src/test/resources/janusgraph-server-with-serializers.yaml
Labels: area/testing, cla: external, backport, backport/v0.6

#3297 refactor backport
  .backportrc.json
  .github/dependabot.yml
  .github/workflows/backport.yml
Labels: cla: external

#3377 Fix edgeID inconsistency between OLAP and OLTP queries
  janusgraph-hadoop/pom.xml
  janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/formats/util/JanusGraphVertexDeserializer.java
  janusgraph-hadoop/src/test/java/org/janusgraph/hadoop/AbstractInputFormatIT.java
  janusgraph-hadoop/src/test/java/org/janusgraph/hadoop/formats/util/HadoopRecordReaderTest.java
Labels: cla: external, backport, backport/v0.6

#3455 RelationIdentifierGraphBinarySerializer: Fix property serialization
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/io/binary/RelationIdentifierGraphBinarySerializer.java
  janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/JanusGraphSerializerBaseIT.java
Labels: cla: external

#3451 Improve docker section in installation guide
  docs/getting-started/installation.md
Labels: cla: external, backport, backport/v0.6

#3362 Refactor Index Management and support removal of Mixed Indexes
  docs/changelog.md
  docs/schema/index-management/index-lifecycle.md
  docs/schema/index-management/index-lifecycle.png
  docs/schema/index-management/index-lifecycle.svg
  docs/schema/index-management/index-reindexing.md
  docs/schema/index-management/index-removal.md
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphBaseTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/TestMockIndexProvider.java
  janusgraph-benchmark/src/main/java/org/janusgraph/MgmtOlapJobBenchmark.java
  janusgraph-core/src/main/java/org/janusgraph/core/schema/JanusGraphManagement.java
  janusgraph-core/src/main/java/org/janusgraph/core/schema/SchemaAction.java
  janusgraph-core/src/main/java/org/janusgraph/core/schema/SchemaStatus.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/indexing/IndexProvider.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/indexing/IndexTransaction.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/MetricInstrumentedIndexProvider.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/IndexSerializer.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ManagementSystem.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/job/IndexRemoveJob.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchClient.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestElasticSearchClient.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticsearchJanusGraphIndexTest.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/JanusGraphElasticsearchContainer.java
  janusgraph-hadoop/src/main/java/org/janusgraph/hadoop/MapReduceIndexManagement.java
  janusgraph-hadoop/src/test/java/org/janusgraph/hadoop/AbstractIndexManagementIT.java
  janusgraph-hadoop/src/test/java/org/janusgraph/hadoop/MapReduceRemoveIndexApp.java
  janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java
  janusgraph-lucene/src/test/java/org/janusgraph/diskstorage/lucene/BerkeleyLuceneTest.java
  janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java
  janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/BerkeleySolrTest.java
  janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/CQLSolrTest.java
  mkdocs.yml
Labels: index/elasticsearch, area/schema, area/index, cla: external, backport/skip

#3466 Fix broken performance test
  janusgraph-benchmark/src/main/java/org/janusgraph/MgmtOlapJobBenchmark.java
  janusgraph-core/src/main/java/org/janusgraph/core/schema/SchemaAction.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/job/IndexRemoveJob.java
Labels: cla: external, backport/skip

#3478 [v0.6] Bump graalvm-nativeimage.version from 22.2.0 to 22.3.1
  pom.xml
Labels: backport/skip

#3485 [v0.6] Bump jacoco-maven-plugin from 0.8.6 to 0.8.8
  pom.xml
Labels: backport/skip

#3469 Document JanusGraph.Net
  docs/interactions/connecting/dotnet.md
  mkdocs.yml
Labels: area/docs, cla: external, backport/v0.6

#3468 Let required checks pass for doc PRs
  .github/workflows/ci-backend-cql-dummy.yml
  .github/workflows/ci-backend-hbase-dummy.yml
  .github/workflows/ci-core-dummy.yml
  .github/workflows/ci-index-es-dummy.yml
  .github/workflows/ci-index-solr-dummy.yml
  .github/workflows/ci-release-dummy.yml
Labels: cla: external, backport/v0.6

#3495 [v0.6] Bump netty4.version from 4.1.86.Final to 4.1.87.Final
  pom.xml
Labels: cla: external, backport/skip

#3268 Add support for ElasticSearch 8
  .github/workflows/ci-index-es.yml
  docs/changelog.md
  docs/configs/janusgraph-cfg.md
  docs/index-backend/text-search.md
  janusgraph-all/pom.xml
  janusgraph-backend-testutils/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
  janusgraph-core/pom.xml
  janusgraph-core/src/main/java/org/janusgraph/core/schema/Mapping.java
  janusgraph-core/src/main/java/org/janusgraph/core/util/ReflectiveConfigOptionLoader.java
  janusgraph-core/src/main/java/org/janusgraph/util/system/ConfigurationUtil.java
  janusgraph-core/src/test/java/org/janusgraph/util/system/ConfigurationUtilTest.java
  janusgraph-dist/pom.xml
  janusgraph-driver/src/main/java/org/janusgraph/core/attribute/Geoshape.java
  janusgraph-es/pom.xml
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticMajorVersion.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/compat/ES8Compat.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/compat/ESCompatUtils.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestElasticSearchClient.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticsearchConfigTest.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticsearchIndexTest.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticsearchJanusGraphIndexTest.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/JanusGraphElasticsearchContainer.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/TestCircleProcessor.java
  janusgraph-lucene/src/test/java/org/janusgraph/diskstorage/lucene/BerkeleyLuceneTest.java
  janusgraph-lucene/src/test/java/org/janusgraph/diskstorage/lucene/LuceneIndexTest.java
  janusgraph-mixed-index-utils/pom.xml
  janusgraph-mixed-index-utils/src/main/java/org/janusgraph/diskstorage/mixed/utils/CircleUtils.java
  janusgraph-mixed-index-utils/src/main/java/org/janusgraph/diskstorage/mixed/utils/MixedIndexUtilsConfigOptions.java
  janusgraph-mixed-index-utils/src/main/java/org/janusgraph/diskstorage/mixed/utils/processor/CircleProcessor.java
  janusgraph-mixed-index-utils/src/main/java/org/janusgraph/diskstorage/mixed/utils/processor/DynamicErrorDistanceCircleProcessor.java
  janusgraph-mixed-index-utils/src/main/java/org/janusgraph/diskstorage/mixed/utils/processor/ErrorDistanceCircleProcessor.java
  janusgraph-mixed-index-utils/src/main/java/org/janusgraph/diskstorage/mixed/utils/processor/FixedErrorDistanceCircleProcessor.java
  janusgraph-mixed-index-utils/src/main/java/org/janusgraph/diskstorage/mixed/utils/processor/NoTransformCircleProcessor.java
  janusgraph-mixed-index-utils/src/test/java/org/janusgraph/diskstorage/mixed/utils/CircleUtilsTest.java
  janusgraph-mixed-index-utils/src/test/java/org/janusgraph/diskstorage/mixed/utils/processor/DynamicErrorDistanceCircleProcessorTest.java
  janusgraph-mixed-index-utils/src/test/java/org/janusgraph/diskstorage/mixed/utils/processor/ErrorDistanceCircleProcessorTest.java
  janusgraph-mixed-index-utils/src/test/java/org/janusgraph/diskstorage/mixed/utils/processor/FixedErrorDistanceCircleProcessorTest.java
  janusgraph-mixed-index-utils/src/test/java/org/janusgraph/diskstorage/mixed/utils/processor/NoTransformCircleProcessorTest.java
  janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/SolrIndexTest.java
  janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/SolrJanusGraphIndexTest.java
  pom.xml
Labels: cla: external

#3502 Let ES 8 checks pass for doc PRs CTR
  .github/workflows/ci-index-es-dummy.yml
Labels: cla: external

#3505 [v0.6] Bump maven-javadoc-plugin from 3.4.0 to 3.4.1
  pom.xml
Labels: backport/skip

#3409 Document new backporting strategy
  CONTRIBUTING.md
  docs/development.md
Labels: cla: external

#3487 Fix index name in Changelog CTR
  docs/changelog.md
Labels: cla: external

#3506 [v0.6] Bump gson from 2.9.1 to 2.10.1
  pom.xml
Labels: backport/skip

#3521 [v0.6] Bump junit.version from 5.9.1 to 5.9.2 | Also bump junit-platform to 1.9.2
  pom.xml
Labels: backport/skip
