Repository JanusGraph/janusgraph, pull requests merged in 2023-06, with the labels that each got.

#3780 Bump TinkerPop to 3.6.4 [cql-tests] [tp-tests]
  docs/changelog.md
  janusgraph-core/src/main/java/org/janusgraph/core/JanusGraph.java
  mkdocs.yml
  pom.xml
Labels: cla: external

#3782 Move Janusgraph docker into main repo
  .github/workflows/ci-publish-commit.yml
  .github/workflows/ci-publish-official.yml
  BUILDING.md
  README.md
  docs/operations/container.md
  janusgraph-dist/README.md
  janusgraph-dist/docker/.dockerignore
  janusgraph-dist/docker/Dockerfile
  janusgraph-dist/docker/build-and-push-image.sh
  janusgraph-dist/docker/conf/janusgraph-berkeleyje-es-server.properties
  janusgraph-dist/docker/conf/janusgraph-berkeleyje-lucene-server.properties
  janusgraph-dist/docker/conf/janusgraph-berkeleyje-server.properties
  janusgraph-dist/docker/conf/janusgraph-cql-es-server.properties
  janusgraph-dist/docker/conf/janusgraph-cql-server.properties
  janusgraph-dist/docker/conf/janusgraph-inmemory-server.properties
  janusgraph-dist/docker/docker-entrypoint.sh
  janusgraph-dist/docker/examples/docker-compose-cql-es.yml
  janusgraph-dist/docker/examples/docker-compose-mount.yml
  janusgraph-dist/docker/examples/docker-compose.yml
  janusgraph-dist/docker/load-initdb.sh
  janusgraph-dist/docker/scripts/remote-connect.groovy
  janusgraph-dist/docker/test-image.sh
  janusgraph-dist/pom.xml
  mkdocs.yml
Labels: cla: external, backport/v0.6

#3795 [v0.6] Move Janusgraph docker into main repo
  .github/workflows/ci-publish-commit.yml
  .github/workflows/ci-publish-official.yml
  BUILDING.md
  README.md
  docs/operations/container.md
  janusgraph-dist/README.md
  janusgraph-dist/docker/.dockerignore
  janusgraph-dist/docker/Dockerfile
  janusgraph-dist/docker/build-and-push-image.sh
  janusgraph-dist/docker/conf/janusgraph-berkeleyje-es-server.properties
  janusgraph-dist/docker/conf/janusgraph-berkeleyje-lucene-server.properties
  janusgraph-dist/docker/conf/janusgraph-berkeleyje-server.properties
  janusgraph-dist/docker/conf/janusgraph-cql-es-server.properties
  janusgraph-dist/docker/conf/janusgraph-cql-server.properties
  janusgraph-dist/docker/conf/janusgraph-inmemory-server.properties
  janusgraph-dist/docker/docker-entrypoint.sh
  janusgraph-dist/docker/examples/docker-compose-cql-es.yml
  janusgraph-dist/docker/examples/docker-compose-mount.yml
  janusgraph-dist/docker/examples/docker-compose.yml
  janusgraph-dist/docker/load-initdb.sh
  janusgraph-dist/docker/scripts/remote-connect.groovy
  janusgraph-dist/docker/test-image.sh
  janusgraph-dist/pom.xml
  mkdocs.yml
Labels: cla: external, backport/skip

#3783 Revamp JanusGraphMultiQueryStrategy for better parent step usage [cql-tests] [tp-tests]
  docs/changelog.md
  docs/configs/janusgraph-cfg.md
  docs/operations/batch-processing.md
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/testutil/JanusGraphAssert.java
  janusgraph-benchmark/src/main/java/org/janusgraph/CQLMultiQueryBenchmark.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/ConfigName.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphTraversalUtil.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/MultiQueryPositions.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphMultiQueryStep.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphPropertiesStep.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphVertexStep.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/MultiQueriable.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/fetcher/BatchProcessingQueue.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/fetcher/MultiQueriableStepBatchFetcher.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/fetcher/PropertiesStepBatchFetcher.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/fetcher/VertexStepBatchFetcher.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/JanusGraphLocalQueryOptimizerStrategy.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/JanusGraphMultiQueryStrategy.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/JanusGraphUnusedMultiQueryRemovalStrategy.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/MultiQueriableStepRegistrationConsumer.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/MultiQueryStrategyRepeatStepMode.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/util/JanusGraphTraverserUtil.java
  janusgraph-core/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/step/fetcher/BatchProcessingQueueTest.java
  janusgraph-core/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/step/fetcher/MultiQueriableStepBatchFetcherTest.java
  janusgraph-core/src/test/java/org/janusgraph/graphdb/util/JanusGraphTraverserUtilTest.java
  janusgraph-core/src/test/java/org/janusgraph/graphdb/util/TestTraverserWithoutLoopsSupport.java
  janusgraph-inmemory/src/test/java/org/janusgraph/graphdb/inmemory/InMemoryGraphTest.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphMultiQueryStepTest.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphMultiQueryStrategyTest.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphStepStrategyTest.java
Labels: kind/performance, area/core, cla: external

#3802 Refactor JanusGraphHasStep strategy and fix documentation misspell CTR
  docs/configs/janusgraph-cfg.md
  janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphHasStep.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/JanusGraphHasStepStrategy.java
  janusgraph-core/src/test/java/org/janusgraph/util/datastructures/ExceptionUtilTest.java
Labels: cla: external

#3817 Backport Jackson 2.15.2 update #3804
  pom.xml
Labels: dependencies, cla: external

#3828 [v0.6] Bump testcontainers.version from 1.18.0 to 1.18.3
  pom.xml
Labels: cla: external, backport/skip

#3822 Remove Gitter from docs
  .github/ISSUE_TEMPLATE/bug-report.md
  README.md
Labels: area/docs, cla: external

#3838 [v0.6] Bump junit.version from 5.9.2 to 5.9.3 | Also bump junit-platform to 1.9.3
  pom.xml
Labels: cla: external, backport/skip

#3803 Enable multiQuery optimization for PropertyMapStep and ElementMapStep [cql-tests] [tp-tests]
  docs/changelog.md
  docs/configs/janusgraph-cfg.md
  docs/operations/batch-processing.md
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-benchmark/src/main/java/org/janusgraph/BenchmarkRunner.java
  janusgraph-benchmark/src/main/java/org/janusgraph/CQLMultiQueryPropertiesBenchmark.java
  janusgraph-core/src/main/java/org/janusgraph/core/TransactionBuilder.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/StandardJanusGraph.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphElementMapStep.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphPropertiesStep.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphPropertyMapStep.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/fetcher/LabelStepBatchFetcher.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/service/DirectPropertiesFetchingService.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/service/PropertiesFetchingService.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/service/TraversalPropertiesFetchingService.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/util/PropertiesFetchingUtil.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/JanusGraphLocalQueryOptimizerStrategy.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/JanusGraphMultiQueryStrategy.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/MultiQueryPropertiesStrategyMode.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardTransactionBuilder.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/TransactionConfiguration.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphMultiQueryStrategyTest.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphStepStrategyTest.java
Labels: cla: external

#3850 [v0.6] Bump build-helper-maven-plugin from 3.3.0 to 3.4.0
  pom.xml
Labels: cla: external, backport/skip

#3825 Add possibility to execute multiple slice queries together to KeyColumnValueStore [cql-tests] [tp-tests]
  docs/changelog.md
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphBaseTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-benchmark/src/main/java/org/janusgraph/CQLMultiQueryMultiSlicesBenchmark.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/BackendTransaction.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/KCVSProxy.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/KCVSUtil.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/KeyColumnValueStore.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/KeyMultiQuery.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/KeyRangeQuery.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/KeySliceQuery.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/KeysQueriesGroup.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/MultiKeyMultiQuery.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/MultiKeysQueryGroups.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/MultiQueriesByKeysGroupsContext.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/SliceQuery.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/StoreFeatures.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/cache/ExpirationKCVSCache.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/cache/KCVSCache.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/CompletableFutureUtil.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/MetricInstrumentedStore.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/StandardJanusGraph.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/BackendQueryHolder.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/profile/QueryProfiler.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/profile/QueryProfilerUtil.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/MultiVertexCentricQueryBuilder.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/VertexCentricQueryBuilder.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/util/MultiSliceQueriesGroupingUtil.java
  janusgraph-core/src/test/java/org/janusgraph/graphdb/util/MultiSliceQueriesGroupingUtilTest.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java
  janusgraph-inmemory/src/test/java/org/janusgraph/graphdb/inmemory/InMemoryGraphTest.java
  janusgraph-test/src/main/java/org/janusgraph/diskstorage/cache/KCVSCacheTest.java
Labels: kind/performance, cla: external, backport/skip

#3851 Refactoring: remove unused classes from #3825 CTR
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/KeyColumnValueStore.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/KeyMultiQuery.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/MultiKeyMultiQuery.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/StoreFeatures.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/util/CompletableFutureUtil.java
  janusgraph-core/src/test/java/org/janusgraph/graphdb/util/MultiSliceQueriesGroupingUtilTest.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java
Labels: cla: external

#3846 Trigger Actions for Backport PRs
  .github/workflows/backport.yml
Labels: cla: external, backport/v0.6

#3854 [v0.6] Bump grpc.version from 1.54.1 to 1.56.0
  pom.xml
Labels: cla: external, backport/skip

#3855 [v0.6] Bump snappy-java from 1.1.9.1 to 1.1.10.1
  pom.xml
Labels: cla: external, backport/skip

#3856 [v0.6] Bump netty-handler from 4.1.93.Final to 4.1.94.Final
  pom.xml
Labels: cla: external, backport/skip

#3852 Remove unnecessary Guice dependencies [tp-tests]
  pom.xml
Labels: kind/cleanup, cla: external, backport/skip

#3853 Remove 2 unused dependencies
  pom.xml
Labels: kind/cleanup, cla: external, backport/v0.6

#3865 [v0.6] Bump error_prone_annotations from 2.18.0 to 2.20.0
  pom.xml
Labels: cla: external, backport/skip

#3866 Update ci-publish Java to 8.0.372+7
  .github/workflows/ci-publish-commit.yml
  .github/workflows/ci-publish-official.yml
Labels: cla: external, backport/v0.6

#3868 [v0.6] Update ci-publish Java to 8.0.372+7
  .github/workflows/ci-publish-commit.yml
  .github/workflows/ci-publish-official.yml
Labels: cla: external, backport/skip

#3319 mark flaky tests
  janusgraph-cql/src/test/java/org/janusgraph/core/cql/CQLConfiguredGraphFactoryTest.java
  janusgraph-cql/src/test/java/org/janusgraph/graphdb/cql/CQLGraphTest.java
  janusgraph-cql/src/test/java/org/janusgraph/hadoop/CQLIndexManagementIT.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/CQLElasticsearchTest.java
  janusgraph-test/src/test/java/org/janusgraph/diskstorage/cache/ExpirationCacheTest.java
Labels: cla: external, backport, backport/v0.6

#3869 [v0.6] mark flaky tests
  janusgraph-cql/src/test/java/org/janusgraph/core/cql/CQLConfiguredGraphFactoryTest.java
  janusgraph-cql/src/test/java/org/janusgraph/graphdb/cql/CQLGraphTest.java
  janusgraph-cql/src/test/java/org/janusgraph/hadoop/CQLIndexManagementIT.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/CQLElasticsearchTest.java
  janusgraph-test/src/test/java/org/janusgraph/diskstorage/cache/ExpirationCacheTest.java
Labels: cla: external, backport/skip

#3870 Increase wait time for slow ConfigurationManagementGraphServerTest
  janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/ConfigurationManagementGraphServerTest.java
Labels: testing/flaky, cla: external, backport, backport/v0.6

#3871 [v0.6] Increase wait time for slow test run
  janusgraph-server/src/test/java/org/janusgraph/graphdb/tinkerpop/ConfigurationManagementGraphServerTest.java
Labels: testing/flaky, cla: external, backport/skip
