Repository JanusGraph/janusgraph, pull requests merged in 2023-09, with the labels that each got.

#3943 [v0.6] Bump testcontainers.version from 1.18.3 to 1.19.0
  pom.xml
Labels: cla: external, backport/skip

#3944 [v0.6] Bump org.easymock:easymock from 5.1.0 to 5.2.0
  pom.xml
Labels: cla: external, backport/skip

#3950 [v0.6] Bump junit.version from 5.9.3 to 5.10.0 | Also bump junit-platform to 1.10.0
  pom.xml
Labels: cla: external, backport/skip

#3949 [v0.6] Bump com.googlecode.maven-download-plugin:download-maven-plugin
  janusgraph-dist/pom.xml
Labels: cla: external, backport/skip

#3957 [v0.6] Bump com.google.errorprone:error_prone_annotations from 2.20.0 to 2.21.1
  pom.xml
Labels: cla: external, backport/skip

#3975 Rename Linkurious to Ogma
  README.md
Labels: area/docs, cla: external

#3982 [v0.6] Mark more tests as flaky
  TESTING.md
  janusgraph-backend-testutils/src/main/java/org/janusgraph/diskstorage/indexing/IndexProviderTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/diskstorage/log/LogTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphOperationCountingTest.java
  janusgraph-berkeleyje/src/test/java/org/janusgraph/graphdb/berkeleyje/BerkeleyOperationCountingTest.java
  janusgraph-cql/src/test/java/org/janusgraph/core/cql/CQLConfiguredGraphFactoryTest.java
  janusgraph-cql/src/test/java/org/janusgraph/graphdb/cql/CQLGraphCacheTest.java
  janusgraph-cql/src/test/java/org/janusgraph/graphdb/cql/CQLGraphTest.java
  janusgraph-cql/src/test/java/org/janusgraph/graphdb/cql/CQLOLAPTest.java
  janusgraph-cql/src/test/java/org/janusgraph/hadoop/CQLIndexManagementIT.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/BerkeleyElasticsearchTest.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/CQLElasticsearchTest.java
  janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/CQLSolrTest.java
  janusgraph-solr/src/test/java/org/janusgraph/diskstorage/solr/SolrJanusGraphIndexTest.java
  janusgraph-test/src/test/java/org/janusgraph/diskstorage/cache/ExpirationCacheTest.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/vertices/StandardVertexTest.java
Labels: area/testing, testing/flaky, cla: external, backport/skip

#3981 Remove minSuccess arguments from remaining tests
  janusgraph-cql/src/test/java/org/janusgraph/graphdb/cql/CQLGraphCacheTest.java
  janusgraph-cql/src/test/java/org/janusgraph/graphdb/cql/CQLGraphTest.java
Labels: testing/flaky, cla: external

#3989 Fix backport of: Mark more tests as flaky
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/BerkeleyElasticsearchTest.java
Labels: area/testing, testing/flaky, cla: external

#3986 [v0.6] Bump docker/setup-qemu-action from 2 to 3
  .github/workflows/ci-publish-commit.yml
  .github/workflows/ci-publish-official.yml
Labels: cla: external, backport/skip

#3988 [v0.6] Bump docker/setup-buildx-action from 2 to 3
  .github/workflows/ci-publish-commit.yml
  .github/workflows/ci-publish-official.yml
Labels: cla: external, backport/skip

#3987 [v0.6] Bump docker/login-action from 2 to 3
  .github/workflows/ci-publish-commit.yml
  .github/workflows/ci-publish-official.yml
Labels: cla: external, backport/skip

#3972 Fix ordered iterator
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/util/MultiDistinctOrderedIterator.java
Labels: cla: external, backport/v0.6
