Repository JanusGraph/janusgraph, pull requests merged in 2023-05, with the labels that each got.

#3745 Use Reload4j as the default logging implementation
  docs/changelog.md
  janusgraph-dist/src/assembly/static/bin/gremlin.sh
  janusgraph-dist/src/assembly/static/bin/janusgraph-server.sh
Labels: cla: external, area/logs

#3743 Remove unused JanusGraphMultiQueryStep when possible [tp-tests][cql-tests]
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/StandardJanusGraph.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/step/JanusGraphMultiQueryStep.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/JanusGraphMultiQueryStrategy.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/JanusGraphUnusedMultiQueryRemovalStrategy.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphMultiQueryStrategyTest.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphStepStrategyTest.java
Labels: cla: external

#3754 Update org.jacoco.ant to 0.8.10 [cql-tests] [tp-tests]
  pom.xml
Labels: dependencies, cla: external, backport, backport/v0.6

#3761 Add 0.6.4 Changelog from v0.6 branch
  docs/changelog.md
Labels: cla: external

#3764 Fix snakeyaml NoSuchMethodError in remote console
  janusgraph-dist/src/test/expect/remote-console.expect.vm
  janusgraph-dist/src/test/java/org/janusgraph/pkgtest/AbstractJanusGraphAssemblyIT.java
  pom.xml
Labels: cla: external, backport/v0.6

#3775 Use default limited batch size even when LazyBarrierStrategy not applies
  docs/changelog.md
  docs/configs/janusgraph-cfg.md
  docs/operations/batch-processing.md
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/JanusGraphMultiQueryStrategy.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphMultiQueryStrategyTest.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphStepStrategyTest.java
Labels: cla: external
