Repository JanusGraph/janusgraph, pull requests merged in 2023-12, with the labels that each got.

#4158 Enable janusgraph-core unit tests in CI
  .github/workflows/ci-core.yml
Labels: backport/v1.0

#4162 [v1.0] Enable janusgraph-core unit tests in CI
  .github/workflows/ci-core.yml
Labels: backport/skip

#4143 [v1.0] Bump jackson2.version from 2.15.3 to 2.16.0
  pom.xml
Labels: cla: external, backport/skip

#4145 [v1.0] Bump protobuf.version from 3.25.0 to 3.25.1
  pom.xml
Labels: cla: external, backport/skip

#4146 [v1.0] Bump org.checkerframework:checker-qual from 3.39.0 to 3.40.0
  pom.xml
Labels: cla: external, backport/skip

#4144 [v1.0] Bump testcontainers.version from 1.19.1 to 1.19.3
  pom.xml
Labels: cla: external, backport/skip

#4187 [v1.0] Bump actions/setup-python from 4 to 5
  .github/workflows/ci-benchmark.yml
  .github/workflows/ci-publish-official.yml
Labels: cla: external, backport/skip

#4197 [v1.0] Bump actions/setup-java from 3 to 4
  .github/workflows/ci-backend-cql.yml
  .github/workflows/ci-backend-hbase.yml
  .github/workflows/ci-backend-scylla-dummy.yml
  .github/workflows/ci-backend-scylla.yml
  .github/workflows/ci-benchmark.yml
  .github/workflows/ci-core.yml
  .github/workflows/ci-docs.yml
  .github/workflows/ci-index-es.yml
  .github/workflows/ci-index-solr.yml
  .github/workflows/ci-publish-commit.yml
  .github/workflows/ci-publish-official.yml
  .github/workflows/ci-release.yml
Labels: cla: external, backport/skip
