Repository JanusGraph/janusgraph, pull requests merged in 2023-02, with the labels that each got.

#3525 Fix Curl version not found
  janusgraph-hbase/docker/Dockerfile
Labels: backport/v0.6

#3513 Reduce Guava usage in StandardJanusGraph.prepareCommit
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/StandardJanusGraph.java
Labels: kind/cleanup

#3504 Avoid copying all properties and edges into memory for IndexRepairJob
  janusgraph-core/src/main/java/org/janusgraph/graphdb/olap/job/IndexRepairJob.java
Labels: cla: external

#3503 Should not retry CQL ServerErrors for large key values
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java
  janusgraph-cql/src/test/java/org/janusgraph/graphdb/cql/CQLGraphTest.java
Labels: storage/scylladb, cla: external, backport/v0.6

#3527 Update TinkerPop to 3.6.2
  docs/changelog.md
  mkdocs.yml
  pom.xml
Labels: area/tinkerpop, dependencies, java

#3533 [v0.6] Bump jackson2.version from 2.14.1 to 2.14.2
  pom.xml
Labels: backport/skip

#3526 Update TinkerPop to 3.5.5
  docs/changelog.md
  mkdocs.yml
  pom.xml
Labels: area/tinkerpop, dependencies, cla: external, java

#3450 Enable Limited Batch Processing by default
  docs/changelog.md
  docs/configs/janusgraph-cfg.md
  docs/operations/batch-processing.md
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/IndexMetricTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/AbstractJanusGraphMixedIndexAggStrategy.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/AdjacentVertexHasUniquePropertyOptimizerStrategy.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/optimize/strategy/AdjacentVertexOptimizerStrategy.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/AdjacentVertexHasUniquePropertyOptimizerStrategyTest.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/JanusGraphStepStrategyTest.java
Labels: kind/performance, cla: external, backport/skip

#3543 [v0.6] Bump snappy-java from 1.1.7.6 to 1.1.9.1
  pom.xml
Labels: cla: external, backport/skip

#3550 [v0.6] Bump maven-dependency-plugin from 3.3.0 to 3.5.0
  pom.xml
Labels: cla: external, backport/skip

#3573 [v0.6] Bump mockito.version from 4.10.0 to 4.11.0
  pom.xml
Labels: cla: external, backport/skip

#3569 Remove dead links from README.md
  README.md
Labels: area/docs, cla: external

#3575 [v0.6] Bump jna from 5.7.0 to 5.13.0
  pom.xml
Labels: cla: external, backport/skip

#3570 Fix Index Providers limited count
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/QueryUtil.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java
  janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java
  janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java
Labels: cla: external, backport/v0.6

#3598 [v0.6] Fix Index Providers limit on aggregated count
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/QueryUtil.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java
  janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java
  janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java
Labels: cla: external

#3341 Fix NO_LIMIT handling for key-value stores
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/keyvalue/KeySelector.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/LimitAdjustingIterator.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/ResultSetIterator.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/MultiKeySliceQuery.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/BasicVertexCentricQueryBuilder.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/util/MultiDistinctOrderedIterator.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/util/MultiDistinctUnorderedIterator.java
Labels: cla: external, backport/v0.6

#3606 JanusGraph release 0.6.3 [cql-tests] [tp-tests]
  docs/changelog.md
  janusgraph-all/pom.xml
  janusgraph-backend-testutils/pom.xml
  janusgraph-berkeleyje/pom.xml
  janusgraph-bigtable/pom.xml
  janusgraph-core/pom.xml
  janusgraph-cql/pom.xml
  janusgraph-dist/pom.xml
  janusgraph-doc/pom.xml
  janusgraph-driver/pom.xml
  janusgraph-es/pom.xml
  janusgraph-examples/example-berkeleyje/pom.xml
  janusgraph-examples/example-common/pom.xml
  janusgraph-examples/example-cql/pom.xml
  janusgraph-examples/example-hbase/pom.xml
  janusgraph-examples/example-remotegraph/pom.xml
  janusgraph-examples/example-tinkergraph/pom.xml
  janusgraph-examples/pom.xml
  janusgraph-grpc/pom.xml
  janusgraph-hadoop/pom.xml
  janusgraph-hbase/pom.xml
  janusgraph-inmemory/pom.xml
  janusgraph-lucene/pom.xml
  janusgraph-server/pom.xml
  janusgraph-solr/pom.xml
  janusgraph-test/pom.xml
  mkdocs.yml
  pom.xml
Labels: cla: external

#3579 Doc: fix CQL replication config documentation to be more explicit
  docs/configs/janusgraph-cfg.md
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java
Labels: cla: external, backport/v0.6

#3608 Doc: Explain custom User Transaction Log implementation
  docs/advanced-topics/transaction-log.md
  docs/configs/janusgraph-cfg.md
  janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java
Labels: area/docs, cla: external, backport/v0.6

#3572 Apply limit and offset to IndexProvider.totals method
  docs/changelog.md
  docs/index-backend/direct-index-query.md
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphIndexTest.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/indexing/IndexProvider.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/QueryUtil.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/graph/IndexQueryBuilder.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java
  janusgraph-lucene/src/main/java/org/janusgraph/diskstorage/lucene/LuceneIndex.java
  janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java
Labels: cla: external, backport/skip

#3607 Disable CQL ExecutorService by default
  docs/changelog.md
  docs/configs/janusgraph-cfg.md
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java
  janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLConfigTest.java
Labels: kind/enhancement, cla: external

#3625 Doc: fix maven search link to Sonatype central CTR
  README.md
Labels: backport/v0.6
