Repository JanusGraph/janusgraph, pull requests merged in 2023-11, with the labels that each got.

#4094 Add INIT_WAIT_TIME CQL option to sleep after table creation
  docs/configs/janusgraph-cfg.md
  docs/storage-backend/cassandra.md
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java
  janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLConfigTest.java
Labels: backport/v1.0

#4090 [v1.0] Bump protobuf.version from 3.24.3 to 3.25.0
  pom.xml
Labels: cla: external, backport/skip

#4097 revert menu.js and update ci-docs
  .github/workflows/ci-docs.yml
  docs/theme/structor-menu.js.gotmpl
Labels: backport/v1.0

#4098 fix update mkdocs
  docs.Dockerfile
  docs/advanced-topics/commit-releases.md
  docs/advanced-topics/hadoop.md
  docs/basics/connecting/java.md
  docs/basics/search-predicates.md
  docs/changelog.md
  docs/configs/configuration-reference.md
  docs/getting-started/installation.md
  docs/storage-backend/scylladb.md
  mkdocs.yml
  requirements.txt
Labels: backport/v1.0

#4099 [Doc] Introduce Gremlin parser in embedded JanusGraph mode
  docs/operations/deployment.md
Labels: area/docs, backport/v1.0

#4104 fix structur failure
  mkdocs.yml
Labels: backport/v1.0

#4101 [v1.0] revert menu.js and update ci-docs
  .github/workflows/ci-docs.yml
Labels: backport/skip

#4102 [v1.0] fix update mkdocs
  docs.Dockerfile
  docs/advanced-topics/commit-releases.md
  docs/advanced-topics/hadoop.md
  docs/basics/connecting/java.md
  docs/basics/search-predicates.md
  docs/changelog.md
  docs/configs/configuration-reference.md
  docs/getting-started/installation.md
  docs/storage-backend/scylladb.md
  mkdocs.yml
  requirements.txt
Labels: backport/skip

#4106 [v0.6] fix structur failure
  mkdocs.yml
Labels: backport/skip

#4107 [v0.6] fix update mkdocs
  docs.Dockerfile
  docs/advanced-topics/commit-releases.md
  docs/advanced-topics/hadoop.md
  docs/changelog.md
  docs/configs/configuration-reference.md
  docs/getting-started/installation.md
  docs/interactions/connecting/java.md
  docs/interactions/search-predicates.md
  mkdocs.yml
  requirements.txt
Labels: backport/skip

#4108 [v0.5] fix update mkdocs
  docs.Dockerfile
  docs/advanced-topics/hadoop.md
  docs/basics/configuration-reference.md
  docs/changelog.md
  docs/connecting/java.md
  docs/getting-started/installation.md
  docs/index-backend/search-predicates.md
  mkdocs.yml
  requirements.txt
Labels: cla: external, backport/skip

#4109 [v0.4] fix update mkdocs
  docs.Dockerfile
  docs/advanced-topics/hadoop.md
  docs/basics/configuration-reference.md
  docs/changelog.md
  docs/getting-started/installation.md
  docs/index-backend/search-predicates.md
  mkdocs.yml
  requirements.txt
Labels: cla: external, backport/skip

#4110 [v0.3] fix update mkdocs
  docs.Dockerfile
  docs/advanced-topics/hadoop.md
  docs/basics/configuration-reference.md
  docs/changelog.md
  docs/getting-started/installation.md
  docs/index-backend/search-predicates.md
  docs/storage-backend/cassandra.md
  mkdocs.yml
  requirements.txt
Labels: cla: external, backport/skip

#4111 [v0.2] fix update mkdocs
  docs.Dockerfile
  docs/advanced-topics/hadoop.md
  docs/basics/configuration-reference.md
  docs/changelog.md
  docs/index-backend/search-predicates.md
  mkdocs.yml
  requirements.txt
Labels: cla: external, backport/skip

#4112 fix ci-docs with typo repository-name
  .github/workflows/ci-docs.yml
Labels: backport/v1.0

#4113 [v1.0] fix ci-docs with typo repository-name
  .github/workflows/ci-docs.yml
Labels: backport/skip

#4115 [v0.5] fix version handler for new mkdocs
  docs/theme/js/.gitkeep
  docs/theme/structor-menu.css
  docs/theme/structor-menu.js.gotmpl
  mkdocs.yml
Labels: backport/skip

#4116 [v0.4] fix version handler for new mkdocs
  docs/theme/js/.gitkeep
  docs/theme/structor-menu.css
  docs/theme/structor-menu.js.gotmpl
  mkdocs.yml
Labels: backport/skip

#4117 [v0.3] fix version handler for new mkdocs
  docs/theme/js/.gitkeep
  docs/theme/structor-menu.css
  docs/theme/structor-menu.js.gotmpl
  mkdocs.yml
Labels: backport/skip

#4118 [v0.2] fix version handler for new mkdocs
  docs/theme/js/.gitkeep
  docs/theme/structor-menu.css
  docs/theme/structor-menu.js.gotmpl
  mkdocs.yml
Labels: backport/skip

#4120 [v0.6] fix version handler for new mkdocs
  .github/workflows/ci-backend-cql-dummy.yml
  .github/workflows/ci-backend-cql.yml
  .github/workflows/ci-backend-hbase-dummy.yml
  .github/workflows/ci-backend-hbase.yml
  .github/workflows/ci-core-dummy.yml
  .github/workflows/ci-core.yml
  .github/workflows/ci-index-es-dummy.yml
  .github/workflows/ci-index-es.yml
  .github/workflows/ci-index-solr-dummy.yml
  .github/workflows/ci-index-solr.yml
  .github/workflows/ci-java-11.yml
  .github/workflows/ci-release-dummy.yml
  .github/workflows/ci-release.yml
  docs/theme/js/.gitkeep
  docs/theme/structor-menu.css
  docs/theme/structor-menu.js.gotmpl
  mkdocs.yml
Labels: backport/skip

#4119 [v1.0] fix version handler for new mkdocs
  .github/workflows/ci-backend-cql-dummy.yml
  .github/workflows/ci-backend-cql.yml
  .github/workflows/ci-backend-hbase-dummy.yml
  .github/workflows/ci-backend-hbase.yml
  .github/workflows/ci-backend-scylla-dummy.yml
  .github/workflows/ci-backend-scylla.yml
  .github/workflows/ci-benchmark.yml
  .github/workflows/ci-core-dummy.yml
  .github/workflows/ci-core.yml
  .github/workflows/ci-index-es-dummy.yml
  .github/workflows/ci-index-es.yml
  .github/workflows/ci-index-solr-dummy.yml
  .github/workflows/ci-index-solr.yml
  .github/workflows/ci-release-dummy.yml
  .github/workflows/ci-release.yml
  docs/theme/js/.gitkeep
  docs/theme/structor-menu.css
  docs/theme/structor-menu.js.gotmpl
  mkdocs.yml
Labels: backport/skip

#4103 [v1.0] [Doc] Introduce Gremlin parser in embedded JanusGraph mode
  docs/operations/deployment.md
Labels: cla: external, backport/skip

#4125 [v1.0] get rid of htrace cves
  janusgraph-hbase/pom.xml
  pom.xml
Labels: backport/skip

#4129 [v1.0] Bump metrics.version from 4.2.21 to 4.2.22
  pom.xml
Labels: backport/skip

#4128 [v1.0] Bump aquasecurity/trivy-action from 0.12.0 to 0.14.0
  .github/workflows/ci-release.yml
Labels: backport/skip

#4096 [v1.0] Add INIT_WAIT_TIME CQL option to sleep after table creation
  docs/configs/janusgraph-cfg.md
  docs/storage-backend/cassandra.md
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLConfigOptions.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLKeyColumnValueStore.java
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java
  janusgraph-cql/src/test/java/org/janusgraph/diskstorage/cql/CQLConfigTest.java
Labels: cla: external, backport/skip

#4130 Update Zookeeper to fix cve [cql-tests][tp-tests]
  cassandra-hadoop-util/pom.xml
  janusgraph-hadoop/pom.xml
  pom.xml
Labels: backport/v1.0

#4134 [v1.0] Update Zookeeper to fix cve [cql-tests][tp-tests]
  cassandra-hadoop-util/pom.xml
  janusgraph-hadoop/pom.xml
  pom.xml
Labels: backport/skip

#4140 Fix two unit tests failing locally
  janusgraph-core/src/test/java/org/janusgraph/diskstorage/util/CompletableFutureUtilTest.java
  janusgraph-core/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/step/fetcher/MultiQueriableStepBatchFetcherTest.java
Labels: cla: external, backport/v1.0

#4159 [v1.0] Fix two unit tests failing locally
  janusgraph-core/src/test/java/org/janusgraph/diskstorage/util/CompletableFutureUtilTest.java
  janusgraph-core/src/test/java/org/janusgraph/graphdb/tinkerpop/optimize/step/fetcher/MultiQueriableStepBatchFetcherTest.java
Labels: backport/skip
