Repository JanusGraph/janusgraph, pull requests merged in 2024-11, with the labels that each got.

#4711 Fix doc formatting for schema-init-strategies CTR
  docs/schema/schema-init-strategies.md
Labels: area/docs

#4712 Add link to the janusgraph-visualizer
  README.md
Labels: area/docs

#4714 Fix doc formatting: JSON schema initialization flow CTR
  docs/schema/schema-init-strategies.md
Labels: area/docs

#4713 Update ElasticSearch to 8.15.3
  docs/changelog.md
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/JanusGraphElasticsearchContainer.java
  pom.xml
Labels: index/elasticsearch, dependencies

#4717 Make trivy scan tentative to overcome rate limits
  .github/workflows/ci-release.yml
Labels: kind/security, testing/flaky, backport/v1.0

#4718 [v1.0] Make trivy scan tentative to overcome rate limits
  .github/workflows/ci-release.yml
Labels: backport/skip

#4716 [Backport] Update TinkerPop to 3.7.3 [tp-tests][cql-tests]
  docs/changelog.md
  mkdocs.yml
  pom.xml
Labels: area/tinkerpop, dependencies

#4719 Backport ElasticSearch 8.15.3 update to v1.0
  docs/changelog.md
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/JanusGraphElasticsearchContainer.java
  pom.xml
Labels: index/elasticsearch, dependencies, backport/skip

#4715 [v1.0] Bump com.google.protobuf:protobuf-java from 3.25.4 to 3.25.5
  pom.xml
Labels: backport/skip

#4720 Updarte ScyllaDB testing version to 6.2.0
  docs/changelog.md
  pom.xml
Labels: storage/scylladb, dependencies, backport/skip

#4735 [v1.1] Bump io.netty:netty-common from 4.1.112.Final to 4.1.115.Final
  pom.xml
Labels: backport/skip
