Repository JanusGraph/janusgraph, pull requests merged in 2024-08, with the labels that each got.

#4612 [v1.0] Bump protobuf.version from 3.25.3 to 3.25.4
  pom.xml
Labels: cla: external, backport/skip

#4616 [v1.0] Bump org.apache.maven.plugins:maven-release-plugin from 3.0.1 to 3.1.1
  pom.xml
Labels: backport/skip

#4613 [v1.0] Bump org.checkerframework:checker-qual from 3.43.0 to 3.45.0
  pom.xml
Labels: cla: external, backport/skip

#4617 [v1.0] Bump scylla-driver.version from 4.17.0.1 to 4.18.0.1
  pom.xml
Labels: backport/skip

#4618 [v1.0] Bump org.apache.commons:commons-lang3 from 3.14.0 to 3.15.0
  pom.xml
Labels: backport/skip

#4624 [v1.0] Bump com.fasterxml.woodstox:woodstox-core from 6.6.2 to 7.0.0
  pom.xml
Labels: backport/skip

#4628 [v1.0] Bump grpc.version from 1.65.1 to 1.66.0
  pom.xml
Labels: cla: external, backport/skip

#4629 [v1.0] Bump testcontainers.version from 1.20.0 to 1.20.1
  pom.xml
Labels: cla: external, backport/skip

#4631 [v1.0] Bump commons-net:commons-net from 3.10.0 to 3.11.1
  pom.xml
Labels: cla: external, backport/skip

#4630 Document changes for inmemory backend with Janusgraph 0.5.0 upgrade
  docs/changelog.md
Labels: area/docs, cla: external, storage/inmemory, backport/v1.0

#4637 [v1.0] Document changes for inmemory backend with Janusgraph 0.5.0 upgrade
  docs/changelog.md
Labels: area/docs, backport/skip

#4506 Disable vertex cache for cardinality checks
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphFeatures.java
Labels: cla: external

#4635 [v1.0] Bump the junit group with 6 updates
  pom.xml
Labels: backport/skip

#4640 [v1.0] Bump org.checkerframework:checker-qual from 3.45.0 to 3.46.0
  pom.xml
Labels: backport/skip

#4639 [v1.0] Bump commons-cli:commons-cli from 1.8.0 to 1.9.0
  pom.xml
Labels: backport/skip

#4638 [v1.0] Bump commons-logging:commons-logging from 1.3.1 to 1.3.3
  pom.xml
Labels: backport/skip

#4647 [v1.0] Bump org.apache.commons:commons-lang3 from 3.15.0 to 3.16.0
  pom.xml
Labels: backport/skip

#4645 [v1.0] Bump org.apache.kerby:kerb-simplekdc from 2.0.3 to 2.1.0
  janusgraph-solr/pom.xml
Labels: backport/skip

#4646 [v1.0] Bump metrics.version from 4.2.26 to 4.2.27
  pom.xml
Labels: backport/skip

#4651 [v1.0] Bump org.cyclonedx:cyclonedx-maven-plugin from 2.8.0 to 2.8.1
  pom.xml
Labels: backport/skip

#4653 [v1.0] Bump commons-logging:commons-logging from 1.3.3 to 1.3.4
  pom.xml
Labels: backport/skip

#4654 [v1.0] Bump com.google.errorprone:error_prone_annotations from 2.29.2 to 2.30.0
  pom.xml
Labels: backport/skip

#4661 [v1.0] Bump org.apache.maven.plugins:maven-deploy-plugin from 3.1.2 to 3.1.3
  pom.xml
Labels: backport/skip
