Repository JanusGraph/janusgraph, pull requests merged in 2024-09, with the labels that each got.

#4669 [v1.0] Bump net.bytebuddy:byte-buddy from 1.14.18 to 1.15.1
  pom.xml
Labels: backport/skip

#4672 [v1.0] Bump org.apache.maven.plugins:maven-dependency-plugin
  pom.xml
Labels: backport/skip

#4675 [v1.0] Bump org.apache.maven.plugins:maven-javadoc-plugin from 3.8.0 to 3.10.0
  pom.xml
Labels: backport/skip

#4674 [v1.0] Bump com.google.guava:guava from 33.2.1-jre to 33.3.0-jre
  pom.xml
Labels: backport/skip

#4678 [v1.0] Bump org.easymock:easymock from 5.3.0 to 5.4.0
  pom.xml
Labels: backport/skip

#4664 Fix the circular initialization dependency #4658
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ModifierType.java
  janusgraph-core/src/test/java/org/janusgraph/graphdb/TestModifierType.java
Labels: backport/v0.6

#4687 Backport #4664 to v1.0
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/management/ModifierType.java
  janusgraph-core/src/test/java/org/janusgraph/graphdb/TestModifierType.java
Labels: kind/bug/confirmed, backport/skip
