Repository JanusGraph/janusgraph, pull requests merged in 2024-05, with the labels that each got.

#4427 [v1.0] Bump com.google.errorprone:error_prone_annotations from 2.26.1 to 2.27.0
  pom.xml
Labels: cla: external, backport/skip

#4431 [v1.0] Bump org.javassist:javassist from 3.29.2-GA to 3.30.2-GA
  pom.xml
Labels: backport/skip

#4426 Drop optimization
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-benchmark/src/main/java/org/janusgraph/CQLMultiQueryDropBenchmark.java
  janusgraph-core/src/main/java/org/janusgraph/core/JanusGraphMultiVertexQuery.java
  janusgraph-core/src/main/java/org/janusgraph/core/JanusGraphVertex.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/internal/InternalVertex.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/BasicVertexCentricQueryBuilder.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/query/vertex/MultiVertexCentricQueryBuilder.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/types/system/EmptyVertex.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/vertices/AbstractVertex.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/vertices/PreloadedVertex.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/vertices/StandardVertex.java
Labels: kind/performance, area/core, cla: external

#4435 Drop benchmark graph data after CQLMultiQueryDropBenchmark
  .gitignore
  janusgraph-benchmark/src/main/java/org/janusgraph/CQLMultiQueryDropBenchmark.java
Labels: cla: external

#4437 [v1.0] Bump jinja2 from 3.1.3 to 3.1.4
  requirements.txt
Labels: backport/skip

#4439 [v1.0] Bump hbase2.version from 2.5.6-hadoop3 to 2.5.8-hadoop3
  pom.xml
Labels: backport/skip

#4445 [v1.0] Bump aquasecurity/trivy-action from 0.19.0 to 0.20.0
  .github/workflows/ci-release.yml
Labels: backport/skip

#4441 [v1.0] Bump org.jacoco:org.jacoco.ant from 0.8.11 to 0.8.12
  pom.xml
Labels: backport/skip

#4444 [v1.0] Bump curator.version from 5.5.0 to 5.6.0
  pom.xml
Labels: backport/skip

#4428 fix: chown fail when OS create folders or files with root only permission
  janusgraph-dist/docker/docker-entrypoint.sh
Labels: cla: external, area/docker

#4451 [v1.0] fix: chown fail when OS create folders or files with root only permission
  janusgraph-dist/docker/docker-entrypoint.sh
Labels: backport/skip

#4448 [v1.0] Bump sqren/backport-github-action from 9.3.1 to 9.5.1
  .github/workflows/backport.yml
Labels: backport/skip

#4425 fix: handle BerkeleyJE DB interruption [tp-tests]
  janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJEKeyValueStore.java
  janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJEStoreManager.java
  janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJETx.java
  janusgraph-berkeleyje/src/test/java/org/janusgraph/BerkeleyInterruptionTest.java
  janusgraph-berkeleyje/src/test/java/org/janusgraph/blueprints/process/BerkeleyJanusGraphComputerTest.java
  janusgraph-berkeleyje/src/test/java/org/janusgraph/blueprints/process/BerkeleyJanusGraphProcessTest.java
  janusgraph-berkeleyje/src/test/java/org/janusgraph/blueprints/process/BerkeleyMultiQueryJanusGraphProcessTest.java
  janusgraph-berkeleyje/src/test/java/org/janusgraph/blueprints/process/BerkeleyProcessComputerSuite.java
  janusgraph-berkeleyje/src/test/java/org/janusgraph/blueprints/process/BerkeleyProcessStandardSuite.java
Labels: cla: external, backport/v1.0

#4450 [v1.0] Bump org.apache.hbase.thirdparty:hbase-noop-htrace from 4.1.6 to 4.1.7
  pom.xml
Labels: backport/skip

#4454 [v1.0] Bump testcontainers.version from 1.19.7 to 1.19.8
  pom.xml
Labels: cla: external, backport/skip

#4457 [v1.0] Bump jackson2.version from 2.17.0 to 2.17.1
  pom.xml
Labels: backport/skip

#4462 [v1.0] Bump org.projectlombok:lombok from 1.18.30 to 1.18.32
  pom.xml
Labels: backport/skip

#4466 [v1.0] Bump commons-codec:commons-codec from 1.16.1 to 1.17.0
  pom.xml
Labels: backport/skip

#4458 Bump lucene-solr.version from 8.11.2 to 8.11.3
  pom.xml
Labels: index/solr, index/lucene, dependencies, cla: external, java, backport/v1.0

#4471 [v1.0] Bump org.apache.maven.plugins:maven-failsafe-plugin from 3.0.0 to 3.2.5
  pom.xml
Labels: cla: external, backport/skip

#4465 [v1.0] Bump org.apache.maven.plugins:maven-surefire-plugin from 3.0.0 to 3.2.5
  pom.xml
Labels: cla: external, backport/skip

#4472 [v1.0] Bump org.objenesis:objenesis from 3.3 to 3.4
  pom.xml
Labels: cla: external, backport/skip

#4476 [v1.0] Bump lucene-solr.version from 8.11.2 to 8.11.3
  pom.xml
Labels: cla: external, backport/skip

#4480 [v1.0] ---
  pom.xml
Labels: cla: external, backport/skip

#4478 [v1.0] ---
  pom.xml
Labels: cla: external, backport/skip

#4479 [v1.0] ---
  pom.xml
Labels: cla: external, backport/skip

#4449 [v1.0] Bump net.bytebuddy:byte-buddy from 1.14.13 to 1.14.15
  pom.xml
Labels: cla: external, backport/skip
