Repository JanusGraph/janusgraph, pull requests merged in 2024-02, with the labels that each got.

#4222 [v1.0] Bump netty4.version from 4.1.101.Final to 4.1.105.Final
  pom.xml
Labels: cla: external, backport/skip

#4231 [v1.0] Bump actions/cache from 3 to 4
  .github/workflows/ci-backend-cql.yml
  .github/workflows/ci-backend-hbase.yml
  .github/workflows/ci-backend-scylla-dummy.yml
  .github/workflows/ci-backend-scylla.yml
  .github/workflows/ci-benchmark.yml
  .github/workflows/ci-core.yml
  .github/workflows/ci-docs.yml
  .github/workflows/ci-index-es.yml
  .github/workflows/ci-index-solr.yml
  .github/workflows/ci-publish-commit.yml
  .github/workflows/ci-release.yml
Labels: backport/skip

#4232 [v1.0] Bump org.apache.maven.plugins:maven-checkstyle-plugin
  pom.xml
Labels: backport/skip

#4242 [v1.0] Bump org.apache.commons:commons-lang3 from 3.12.0 to 3.14.0
  pom.xml
Labels: backport/skip

#4235 [v1.0] Bump metrics.version from 4.2.22 to 4.2.23
  pom.xml
Labels: backport/skip

#4247 [v1.0] Bump org.apache.maven.plugins:maven-compiler-plugin
  pom.xml
Labels: backport/skip

#4248 [v1.0] Bump metrics.version from 4.2.23 to 4.2.25
  pom.xml
Labels: backport/skip

#4249 [v1.0] Bump netty4.version from 4.1.105.Final to 4.1.106.Final
  pom.xml
Labels: backport/skip

#4251 [v1.0] Bump aquasecurity/trivy-action from 0.16.1 to 0.17.0
  .github/workflows/ci-release.yml
Labels: cla: external, backport/skip

#4245 [v1.0] Bump org.apache.maven.plugins:maven-source-plugin from 3.2.1 to 3.3.0
  pom.xml
Labels: cla: external, backport/skip

#4252 [v1.0] Bump org.apache.maven.plugins:maven-enforcer-plugin from 3.3.0 to 3.4.1
  pom.xml
Labels: cla: external, backport/skip

#4268 Fix HBase test Dockerfile
  janusgraph-hbase/docker/Dockerfile
Labels: area/testing, storage/hbase, backport/v1.0

#4270 [v1.0] Fix HBase test Dockerfile
  janusgraph-hbase/docker/Dockerfile
Labels: backport/skip

#4262 Fix missing setuptools package for regression test
  .github/workflows/ci-benchmark.yml
Labels: cla: external, backport/v1.0

#4271 [v1.0] Fix missing setuptools package for regression test
  .github/workflows/ci-benchmark.yml
Labels: cla: external, backport/skip

#4273 [v1.0] Bump the junit group with 6 updates
  pom.xml
Labels: backport/skip
