Repository JanusGraph/janusgraph, pull requests merged in 2024-03, with the labels that each got.

#4276 [v1.0] Bump grpc.version from 1.61.0 to 1.61.1
  pom.xml
Labels: backport/skip

#4278 Fix io step read path for string-type vertex ID
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphCustomIdTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphFeatures.java
Labels: backport/v1.0

#4279 Support new text predicates via JanusGraph Server
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphPSerializer.java
  janusgraph-driver/src/test/java/org/janusgraph/graphdb/tinkerpop/io/binary/JanusGraphPGraphBinarySerializerTest.java
  janusgraph-driver/src/test/java/org/janusgraph/graphdb/tinkerpop/io/graphson/JanusGraphSONModuleTest.java
Labels: area/core, cla: external, backport/v1.0

#4282 [v1.0] Bump aquasecurity/trivy-action from 0.17.0 to 0.18.0
  .github/workflows/ci-release.yml
Labels: cla: external, backport/skip

#4284 [v1.0] Fix io step read path for string-type vertex ID
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphCustomIdTest.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphFeatures.java
Labels: cla: external, backport/skip

#4283 [v1.0] Bump org.apache.commons:commons-compress from 1.24.0 to 1.26.0
  pom.xml
Labels: cla: external, backport/skip

#4285 [v1.0] Support new text predicates via JanusGraph Server
  janusgraph-driver/src/main/java/org/janusgraph/graphdb/tinkerpop/JanusGraphPSerializer.java
  janusgraph-driver/src/test/java/org/janusgraph/graphdb/tinkerpop/io/binary/JanusGraphPGraphBinarySerializerTest.java
  janusgraph-driver/src/test/java/org/janusgraph/graphdb/tinkerpop/io/graphson/JanusGraphSONModuleTest.java
Labels: backport/skip

#4287 [v1.0] Bump com.google.errorprone:error_prone_annotations from 2.23.0 to 2.25.0
  pom.xml
Labels: backport/skip

#4291 [v1.0] Returning a copied collection to avoid corrupted iterator by multiple threads
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/addedrelations/AddedRelationsContainer.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/addedrelations/ConcurrentAddedRelations.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/addedrelations/EmptyAddedRelations.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/addedrelations/SimpleAddedRelations.java
  janusgraph-test/src/test/java/org/janusgraph/graphdb/transaction/addedrelations/EmptyAddedRelationsTest.java
Labels: backport/skip

#4294 [v1.0] Bump org.apache.maven.plugins:maven-gpg-plugin from 3.0.1 to 3.1.0
  pom.xml
Labels: backport/skip

#4293 [v1.0] Bump org.jctools:jctools-core from 4.0.1 to 4.0.3
  pom.xml
Labels: backport/skip

#4292 Optimization for adding new vertex and updating vertex properties
  docs/configs/janusgraph-cfg.md
  janusgraph-backend-testutils/src/main/java/org/janusgraph/diskstorage/MultiWriteKeyColumnValueStoreTest.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/Backend.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/cache/CacheTransaction.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/configuration/GraphDatabaseConfiguration.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/StandardJanusGraph.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/database/util/IndexRecordUtil.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/internal/InternalVertex.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/relations/CacheEdge.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/relations/CacheVertexProperty.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/StandardJanusGraphTx.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/addedrelations/AddedPropertiesListValue.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/addedrelations/AddedPropertiesSetValue.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/addedrelations/AddedPropertiesSingleValue.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/addedrelations/AddedPropertiesValue.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/addedrelations/AddedRelationsContainer.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/addedrelations/ConcurrentAddedRelations.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/addedrelations/EmptyAddedRelations.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/transaction/addedrelations/SimpleAddedRelations.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/types/system/EmptyVertex.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/vertices/AbstractVertex.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/vertices/PreloadedVertex.java
  janusgraph-core/src/main/java/org/janusgraph/graphdb/vertices/StandardVertex.java
  janusgraph-hadoop/src/test/java/org/janusgraph/hadoop/formats/util/HadoopRecordReaderTest.java
  janusgraph-test/src/main/java/org/janusgraph/diskstorage/cache/KCVSCacheTest.java
Labels: kind/performance, area/core, backport/skip

#4298 [v1.0] Bump org.checkerframework:checker-qual from 3.40.0 to 3.42.0
  pom.xml
Labels: backport/skip

#4301 [v1.0] Bump com.fasterxml.woodstox:woodstox-core from 6.5.1 to 6.6.1
  pom.xml
Labels: cla: external, backport/skip

#4309 Mark test as flaky for all backends
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphCustomIdTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-cql/src/test/java/org/janusgraph/graphdb/cql/CQLGraphCacheTest.java
Labels: area/testing, testing/flaky, backport/v1.0

#4303 [v1.0] Bump testcontainers.version from 1.19.3 to 1.19.7
  pom.xml
Labels: cla: external, backport/skip

#4310 [v1.0] Bump codecov/codecov-action from 3 to 4 | Add Codecov token (required in v4)
  .github/workflows/ci-backend-cql.yml
  .github/workflows/ci-backend-hbase.yml
  .github/workflows/ci-backend-scylla.yml
  .github/workflows/ci-core.yml
  .github/workflows/ci-index-es.yml
  .github/workflows/ci-index-solr.yml
Labels: backport/skip

#4304 [v1.0] Bump commons-codec:commons-codec from 1.15 to 1.16.1
  pom.xml
Labels: cla: external, backport/skip

#4308 [v1.0] Bump graalvm-nativeimage.version from 23.1.1 to 23.1.2
  pom.xml
Labels: backport/skip

#4313 [v1.0] Mark test as flaky for all backends
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphCustomIdTest.java
  janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java
  janusgraph-cql/src/test/java/org/janusgraph/graphdb/cql/CQLGraphCacheTest.java
Labels: backport/skip

#4316 [v1.0] Bump netty4.version from 4.1.106.Final to 4.1.107.Final
  pom.xml
Labels: backport/skip

#4317 [v1.0] Bump org.apache.maven.plugins:maven-javadoc-plugin from 3.5.0 to 3.6.3
  pom.xml
Labels: backport/skip

#4323 [v1.0] Bump grpc.version from 1.61.1 to 1.62.2
  pom.xml
Labels: backport/skip

#4325 [v1.0] Bump org.json:json from 20231013 to 20240303
  pom.xml
Labels: backport/skip

#4322 [v1.0] Bump log4j2.version from 2.22.1 to 2.23.1
  pom.xml
Labels: backport/skip
