Repository JanusGraph/janusgraph, pull requests merged in 2024-04, with the labels that each got.

#4353 [v1.0] Bump org.apache.maven.plugins:maven-release-plugin from 3.0.0 to 3.0.1
  pom.xml
Labels: cla: external, backport/skip

#4355 [v1.0] Bump netty4.version from 4.1.107.Final to 4.1.108.Final
  pom.xml
Labels: backport/skip

#4356 [v1.0] Bump aquasecurity/trivy-action from 0.18.0 to 0.19.0
  .github/workflows/ci-release.yml
Labels: backport/skip

#4360 [v1.0] Merge pull request #4345 from JanusGraph/dependabot/maven/org.apache.commons-commons-configuration2-2.10.1
  pom.xml
Labels: backport/skip

#4100 add sbom to release process
  .github/workflows/ci-publish-official.yml
  pom.xml
Labels: cla: external, backport/v1.0

#4199 Bump TinkerPop from 3.7.0 to 3.7.1 [tp-tests][cql-tests]
  pom.xml
Labels: cla: external, backport/v1.0

#4369 [v1.0] Bump TinkerPop from 3.7.0 to 3.7.1 [tp-tests][cql-tests]
  mkdocs.yml
  pom.xml
Labels: backport/skip

#4361 [v1.0] Bump graalvm-nativeimage.version from 23.1.2 to 24.0.0
  pom.xml
Labels: backport/skip

#4366 [v1.0] Add CycloneDX SBOM to release process
  .github/workflows/ci-publish-official.yml
  pom.xml
Labels: kind/security, backport/skip

#4373 [v1.0] Bump org.apache.hbase.thirdparty:hbase-noop-htrace from 4.1.5 to 4.1.6
  pom.xml
Labels: backport/skip

#4372 [v1.0] Bump org.apache.rat:apache-rat-plugin from 0.15 to 0.16.1
  pom.xml
Labels: backport/skip

#4377 [v1.0] Bump org.apache.maven.plugins:maven-compiler-plugin
  pom.xml
Labels: cla: external, backport/skip

#4383 [v1.0] Bump jetty.version from 9.4.53.v20231009 to 9.4.54.v20240208
  pom.xml
Labels: backport/skip

#4381 [v1.0] Bump grpc.version from 1.62.2 to 1.63.0
  pom.xml
Labels: cla: external, backport/skip

#4384 [v1.0] Bump commons-io:commons-io from 2.15.1 to 2.16.1
  pom.xml
Labels: backport/skip

#4391 [v1.0] Bump netty4.version from 4.1.108.Final to 4.1.109.Final
  pom.xml
Labels: backport/skip

#4385 [v1.0] Bump jackson2.version from 2.16.1 to 2.17.0
  pom.xml
Labels: backport/skip

#4392 [v1.0] Bump com.googlecode.maven-download-plugin:download-maven-plugin
  janusgraph-dist/pom.xml
Labels: backport/skip

#4393 [v1.0] Bump org.apache.commons:commons-exec from 1.3 to 1.4.0
  janusgraph-benchmark/pom.xml
Labels: backport/skip

#4397 [v1.0] Bump actions/upload-artifact from 3 to 4
  .github/workflows/ci-backend-cql.yml
  .github/workflows/ci-backend-hbase.yml
  .github/workflows/ci-backend-scylla.yml
  .github/workflows/ci-core.yml
  .github/workflows/ci-docs.yml
  .github/workflows/ci-index-es.yml
  .github/workflows/ci-index-solr.yml
  .github/workflows/ci-release.yml
Labels: backport/skip

#4399 [v1.0] Bump org.cyclonedx:cyclonedx-maven-plugin from 2.7.10 to 2.8.0
  pom.xml
Labels: backport/skip

#4398 [v1.0] Bump org.apache.maven.plugins:maven-clean-plugin from 3.2.0 to 3.3.2
  pom.xml
Labels: backport/skip

#4400 [v1.0] Bump org.apache.commons:commons-compress from 1.26.0 to 1.26.1
  pom.xml
Labels: cla: external, backport/skip

#4414 [v1.0] Bump com.google.guava:guava from 32.1.3-jre to 33.1.0-jre
  pom.xml
Labels: backport/skip

#4402 Fixing Issue #4401
  janusgraph-berkeleyje/src/test/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyVariableLengthKCVSTest.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/keyvalue/OrderedKeyValueStoreAdapter.java
Labels: cla: external, backport/v1.0

#4416 [v1.0] Bump org.ow2.asm:asm from 9.6 to 9.7
  pom.xml
Labels: backport/skip

#4409 Added retry logic if client request returns an error code that is configured for retrying
  docs/configs/janusgraph-cfg.md
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestClientSetup.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestElasticSearchClient.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/rest/RestClientRetryTest.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/rest/RestClientSetupTest.java
Labels: cla: external

#4417 [v1.0] Fix OrderedKeyValueStoreAdapter ArrayIndexOutOfBoundsIssue with test
  janusgraph-berkeleyje/src/test/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyVariableLengthKCVSTest.java
  janusgraph-core/src/main/java/org/janusgraph/diskstorage/keycolumnvalue/keyvalue/OrderedKeyValueStoreAdapter.java
Labels: backport/skip

#4418 [v1.0] Bump org.apache.maven.plugins:maven-gpg-plugin from 3.1.0 to 3.2.4
  pom.xml
Labels: backport/skip

#4419 Increase maven wget timeout for ElasticSearch and Cassandra to 30 minutes
  janusgraph-dist/pom.xml
Labels: backport/v1.0

#4424 [v1.0] Increase maven wget timeout for ElasticSearch and Cassandra to 30 minutes
  janusgraph-dist/pom.xml
Labels: backport/skip
