Repository JanusGraph/janusgraph, pull requests merged in 2024-07, with the labels that each got.

#4523 [v1.0] Bump aquasecurity/trivy-action from 0.22.0 to 0.23.0
  .github/workflows/ci-release.yml
Labels: cla: external, backport/skip

#4539 Improve flaky test QueryBackPressureTest to throw an exception faster on unexpected behavior
  janusgraph-core/src/test/java/org/janusgraph/diskstorage/util/backpressure/QueryBackPressureTest.java
Labels: kind/bug/possible, backport/v1.0

#4536 [v1.0] Bump netty4.version from 4.1.110.Final to 4.1.111.Final
  pom.xml
Labels: backport/skip

#4526 [v1.0] Fix NPE on keyspace creation
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java
Labels: cla: external, backport/skip

#4542 [v1.0] Improve flaky test QueryBackPressureTest to throw an exception faster on unexpected behaviour
  janusgraph-core/src/test/java/org/janusgraph/diskstorage/util/backpressure/QueryBackPressureTest.java
Labels: backport/skip

#4528 [v1.0] halve docker image size
  janusgraph-dist/docker/Dockerfile
Labels: cla: external, backport/skip

#4545 [v1.0] Bump aquasecurity/trivy-action from 0.23.0 to 0.24.0
  .github/workflows/ci-release.yml
Labels: cla: external, backport/skip

#4541 [v1.0] Bump the junit group with 6 updates
  pom.xml
Labels: cla: external, backport/skip

#4546 [v1.0] Bump jackson2.version from 2.17.1 to 2.17.2
  pom.xml
Labels: cla: external, backport/skip

#4549 [v1.0] Bump org.jctools:jctools-core from 4.0.3 to 4.0.5
  pom.xml
Labels: backport/skip

#4551 [v1.0] Bump net.bytebuddy:byte-buddy from 1.14.17 to 1.14.18
  pom.xml
Labels: backport/skip

#4553 [v1.0] Bump org.apache.maven.plugins:maven-jar-plugin from 3.4.1 to 3.4.2
  pom.xml
Labels: backport/skip

#4555 [v1.0] Bump commons-cli:commons-cli from 1.6.0 to 1.8.0
  pom.xml
Labels: backport/skip

#4558 [v1.0] Bump com.google.errorprone:error_prone_annotations from 2.28.0 to 2.29.0
  pom.xml
Labels: backport/skip

#4570 [v1.0] Bump org.hdrhistogram:HdrHistogram from 2.1.12 to 2.2.2
  pom.xml
Labels: backport/skip

#4562 [v1.0] Bump org.apache.maven.plugins:maven-source-plugin from 3.3.0 to 3.3.1
  pom.xml
Labels: cla: external, backport/skip

#4563 [v1.0] Bump grpc.version from 1.64.0 to 1.65.1
  pom.xml
Labels: cla: external, backport/skip

#4566 [v1.0] Bump org.apache.maven.plugins:maven-failsafe-plugin from 3.2.5 to 3.3.1
  pom.xml
Labels: backport/skip

#4567 [v1.0] Bump org.projectlombok:lombok from 1.18.32 to 1.18.34
  pom.xml
Labels: backport/skip

#4571 [v1.0] Bump org.easymock:easymock from 5.2.0 to 5.3.0
  pom.xml
Labels: backport/skip

#4572 [v1.0] Bump netty4.version from 4.1.111.Final to 4.1.112.Final
  pom.xml
Labels: backport/skip

#4557 Remove 2 unused Maven plugins
  pom.xml
Labels: cla: external, backport/v1.0

#4578 [v1.0] Bump commons-codec:commons-codec from 1.17.0 to 1.17.1
  pom.xml
Labels: backport/skip

#4582 [v1.0] Bump curator.version from 5.6.0 to 5.7.0
  pom.xml
Labels: backport/skip

#4585 [v1.0] Remove 2 unused Maven plugins
  pom.xml
Labels: backport/skip

#4588 [v1.0] Bump org.apache.maven.plugins:maven-javadoc-plugin from 3.6.3 to 3.8.0
  pom.xml
Labels: backport/skip

#4586 [v1.0] Bump graalvm-nativeimage.version from 24.0.0 to 24.0.2
  pom.xml
Labels: cla: external, backport/skip

#4589 [v1.0] Bump com.google.guava:guava from 33.1.0-jre to 33.2.1-jre
  pom.xml
Labels: cla: external, backport/skip

#4597 [v1.0] Bump metrics.version from 4.2.25 to 4.2.26
  pom.xml
Labels: backport/skip

#4598 [v1.0] Bump org.apache.maven.plugins:maven-surefire-plugin from 3.2.5 to 3.3.1
  pom.xml
Labels: backport/skip

#4599 [v1.0] Bump org.sonatype.plugins:nexus-staging-maven-plugin
  pom.xml
Labels: backport/skip

#4604 [v1.0] Bump com.google.code.gson:gson from 2.10.1 to 2.11.0
  pom.xml
Labels: backport/skip

#4605 [v1.0] Bump net.java.dev.jna:jna from 5.13.0 to 5.14.0
  pom.xml
Labels: backport/skip
