Repository JanusGraph/janusgraph, pull requests merged in 2024-06, with the labels that each got.

#4492 [v1.0] Bump org.checkerframework:checker-qual from 3.42.0 to 3.43.0
  pom.xml
Labels: backport/skip

#4494 [v1.0] Bump aquasecurity/trivy-action from 0.20.0 to 0.21.0
  .github/workflows/ci-release.yml
Labels: backport/skip

#4493 [v1.0] Bump org.apache.maven.plugins:maven-dependency-plugin
  pom.xml
Labels: backport/skip

#4498 [v1.0] Bump org.apache.commons:commons-compress from 1.26.1 to 1.26.2
  pom.xml
Labels: cla: external, backport/skip

#4502 [v1.0] Bump org.apache.maven.plugins:maven-deploy-plugin from 3.1.1 to 3.1.2
  pom.xml
Labels: backport/skip

#4509 [v1.0] Bump org.ow2.asm:asm-commons from 9.6 to 9.7
  pom.xml
Labels: backport/skip

#4510 [v1.0] Bump net.bytebuddy:byte-buddy from 1.14.15 to 1.14.17
  pom.xml
Labels: backport/skip

#4508 [v1.0] Bump org.apache.maven.plugins:maven-enforcer-plugin from 3.4.1 to 3.5.0
  pom.xml
Labels: backport/skip

#4505 [v1.0] Bump com.google.errorprone:error_prone_annotations from 2.27.0 to 2.28.0
  pom.xml
Labels: cla: external, backport/skip

#4512 [v1.0] Bump aquasecurity/trivy-action from 0.21.0 to 0.22.0
  .github/workflows/ci-release.yml
Labels: cla: external, backport/skip

#4518 [v1.0] Bump org.apache.maven.plugins:maven-dependency-plugin
  pom.xml
Labels: backport/skip

#4521 [v1.0] Bump org.apache.commons:commons-text from 1.11.0 to 1.12.0
  pom.xml
Labels: cla: external, backport/skip

#4516 Fix NPE on keyspace creation
  janusgraph-cql/src/main/java/org/janusgraph/diskstorage/cql/CQLStoreManager.java
Labels: cla: external, backport/v1.0

#4527 halve docker image size
  janusgraph-dist/docker/Dockerfile
Labels: backport/v1.0

#4489 Retry bulk request if all errors are configured retry error codes & Split large bulk requests
  docs/configs/janusgraph-cfg.md
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestClientSetup.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestElasticSearchClient.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/ElasticsearchJanusGraphIndexTest.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/rest/RestClientBulkRequestsTest.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/rest/RestClientRetryTest.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/rest/RestClientSetupTest.java
Labels: index/elasticsearch, cla: external

#4530 ES Bulk Retry Follow-up Items
  docs/configs/janusgraph-cfg.md
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java
  janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/rest/RestElasticSearchClient.java
  janusgraph-es/src/test/java/org/janusgraph/diskstorage/es/rest/RestClientBulkRequestsTest.java
Labels: cla: external, backport/skip
