Repository JanusGraph/janusgraph, pull requests merged in 2024-01, with the labels that each got.

#4188 [v1.0] Bump ch.qos.logback:logback-classic from 1.2.11 to 1.2.13
  pom.xml
Labels: cla: external, backport/skip

#4198 [v1.0] Bump com.nimbusds:nimbus-jose-jwt from 9.37 to 9.37.3
  pom.xml
Labels: cla: external, backport/skip

#4192 [v1.0] Bump grpc.version from 1.59.0 to 1.59.1
  pom.xml
Labels: cla: external, backport/skip

#4189 [v1.0] Bump org.codehaus.mojo:exec-maven-plugin from 3.1.0 to 3.1.1
  janusgraph-dist/pom.xml
  janusgraph-examples/pom.xml
  pom.xml
Labels: cla: external, backport/skip

#4191 [v1.0] Bump org.codehaus.mojo:build-helper-maven-plugin from 3.4.0 to 3.5.0
  pom.xml
Labels: cla: external, backport/skip

#4204 [v1.0] Bump aquasecurity/trivy-action from 0.14.0 to 0.16.1
  .github/workflows/ci-release.yml
Labels: backport/skip

#4207 [v1.0] Bump jinja2 from 3.1.2 to 3.1.3
  requirements.txt
Labels: backport/skip

#4208 [v1.0] Bump log4j2.version from 2.20.0 to 2.22.1
  pom.xml
Labels: backport/skip

#4209 [v1.0] Bump commons-net:commons-net from 3.9.0 to 3.10.0
  pom.xml
Labels: cla: external, backport/skip

#4210 [v1.0] Bump commons-io:commons-io from 2.11.0 to 2.15.1
  pom.xml
Labels: cla: external, backport/skip

#4225 fix index-name config option name
  docs/index-backend/elasticsearch.md
Labels: area/docs, index/elasticsearch, backport/v1.0

#4226 [v1.0] fix index-name config option name
  docs/index-backend/elasticsearch.md
Labels: backport/skip
